### ISSUE TITLE
Update languages used by PINN project (based on NOOBS languages)

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#10]
Hi.

I rebuild the NOOBS project regarding the languages.
And I decided to do it also for PINN project.
The original language files included into PIIN repository are (an the status of trnaslation)

DE - 42 of 146 strings
FI - 42 of 146 strings
FR - 25 of 146 strings
HU - 113 of 146 strings
JA - 21 of 146 strings
NL - 99 of 146 strings
PT - 42 of 146 strings
RU - 123 of 126 strings

that seems the same files of NOOBS project.

The files are not updated basing on PINN recovery.pro file.
I made the command

**_lupdate -no-obsolete -disable-heuristic similartext recovery/recovery.pro_**

and then the strings for the languages were updated to 184 (original NOOBS are 147).

I completed/aligned/repacked all languages available. 

Now the language status is

ca = Catalan (37/184 strings)
de = German (136/184 strings)
es = Spanish (134/146 strings)
es_XA = Asturian (111/184)
eu = Basque (138/184 strings)
fi = Finnish (45/184 strings)
fr = French (135/184 strings)
hu = Hungarian (107/184 strings)
it = Italian (184/184 strings)
ja = Japanese (107/184 strings)
ko = Korean (107/184 strings)
nl = Dutch (136/184 strings)
pl = Polish (108/184 strings)
pt = Portuguese (45/184 strings)
ru = Russian (108/184 strings)
sv = Swedish (108/184 strings)
tr = Turkish (134/184 strings)
zh_TW = Taiwanese (134/184 strings)

Here

https://github.com/raspberrypi/noobs/issues/364

you can find also the info about the necessary changes for Korean language (add fonts/keyboard layout)

**** Korean patches info start

Make sure you do not just copy the .ts file, but apply all changes in the PR including the ones that cause the extra .ttf font files to be added at the right locations: https://github.com/raspberrypi/noobs/pull/199/files

One way to do that is to download all changes as .patch file: https://github.com/raspberrypi/noobs/pull/199.patch

**** Korean patches info end

@procount 

Could you please update PINN with

- all languages available (and updated) got from my kit
- include the changes for Korean language in the code?

Info for translators

## ***************** QTLinguist (.TS file editor)

You can find QTLinguist (for editing) standalone (not required an installation) here (for Windows 32bit version)

**_QTLinguist (standalone)_** - https://drive.google.com/open?id=0ByL-fx0GbfuiRnJ5XzBCOVpNNjg

## ***************** PINN changes vs. repository

This the test build with theese changes (vs. stable 2.1.2 version)

The language are  based on original NOOBS languages files with these changes
- Added all new language reported in first posts
- Updated language strings for all languages with lupdate command
- Add flag images (for language selection)
- Patch for Korean fonts
- Enlarge window width for drop down language list
- Added fixes for Asturian language
- Added new strings for Clone window and Security level for Wi-Fi password.

**_PINN test build (trans2)_** - https://github.com/procount/pinn/tree/trans2

## ***************** PINN rebuild image file

This the image based on latest source (test2) compiled and ready to copy on SD.

**_PINN image test rebuild (2.1.2f)_** - https://sourceforge.net/projects/pinn/files/testing/pinn-2121f.zip/download

@softastur
@aldatsa
@cescp
@qsypoq
@qsypoq
@fonic
@sople1
@Akkiesoft
@kadamski
@ResonantWave
@Mangero
@diorray
@s8321414

Could you please update your translation?

Thanks.

**Comment by procount** [comment]
I have been following that issue on Noobs. It will be easier for me to include it once it has been updated in Noobs, rather than doing the work twice.

**Comment by bovirus** [comment]
@procount

I should develop NOOBS package myself because the original developers of NOOBS received many languages file from contributors but no one of the author answered to the people that want to contribute with new language files.
I believe that is not correct no answer to the people that want to contribute.
The authors can  write "No thanks I didn't want a new language" but no answer is not correct.
The original author (lurch) didn't answered at any requests.
The other authors (XECDesign) answered 5 days ago but no changed were made.
I develop myself anew build with all languages and with the patch for Korean fonts.
The new NOOBS build (R07)  is now operative.
 If you don't want to develop a new build until NOOBS implement his build (could be possible? when?) please authorize me to make a new build myself with all languages and Korean patch.

**Comment by bovirus** [comment]
@procount 

Using the command

**lupdate recovery/recovery.pro -no-obsolete -disable-heuristic similartext**

I got the error message

Could not find qmake configuration directoryCould not find qmake configuration fileUsing OS scope before setting MAKEFILE_GENERATORProject MESSAGE: Disabling CEC support for Raspberry Pi - rpi-userland headers not found at ../../staging/usr/home/ubuntu/Desktop/pinn/recovery/recovery.pro(25): Function 'system' is not implemented

I found that your translation contains more strinfgs (184) than NOOBS (147).

then for the reason that I explained befroe (different struccture/different language files) I believe that you can develop the project without waiting NOOBS updates.

@softastur
@aldatsa
@cescp
@qsypoq
@qsypoq
@fonic
@sople1
@Akkiesoft
@kadamski
@ResonantWave
@Mangero
@diorray
@s8321414

It's available in first post the release of PINN language files with update with lupdate.

Please revsie your langauge and post it here.

Thanks.

**Comment by s8321414** [comment]
hmm, so which file should I download to translate?

**Comment by procount** [comment]
@bovirus - thanks for doing this work. The translation side of QT is all new to me, but it wiuld be nice to include this.

To fix the CEC error abive you need to build rpi-userland. Just build all of PINN first or see workaround in #7.

Are your translations based on p2.1.2? Is there any possibility to do a pull request instead of posting patches? It is easier to integrate the changes this way.

**Comment by bovirus** [comment]
@s8321414 

You can find the languages file in 

PINN language files (now is R02) - https://drive.google.com/open?id=0ByL-fx0GbfuidTM5WjIxUjlGQlE

The additional strings (vs. NOOBS language file) that you should translate is about 36.

Thanks.

**Comment by bovirus** [comment]
@procount 

I installed the qt-sdk with 

**_sudo apt-get install qt-sdk_** 

and I solved the problem

**_Could not find qmake configuration directory
Could not find qmake configuration file
Using OS scope before setting MAKEFILE_GENERATOR 

now using 

ubuntu@ubuntu:~/Desktop/pinn$ lupdate recovery/recovery.pro -no-obsolete -disable-heuristic similartext

I got

**_/home/ubuntu/Desktop/pinn/recovery/recovery.pro(26): Function 'system' is not implemented_**

**_Project MESSAGE: Disabling CEC support for Raspberry Pi - rpi-userland headers not found at ../../staging/usr/home/ubuntu/Desktop/pinn/recovery/recovery.pro(25):_** 

Updating 
'recovery/translation_ca.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_de.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_es.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_es_XA.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_eu.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_fi.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_fr.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_hu.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_it.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_ja.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_ko.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_nl.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_pl.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_pt.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_ru.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_sv.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_tr.ts'...
    Found 184 source text(s) (0 new and 184 already existing)
Updating 'recovery/translation_zh_TW.ts'...
    Found 184 source text(s) (0 new and 184 already existing)

It means that in the recovery.pro

the hardcode string

**_message(Disabling CEC support for Raspberry Pi - rpi-userland headers not found at $${RPI_USERLAND_DIR})_**

should be included in language files

Ex. you could change in recovery.pro

**_message(Disabling CEC support for Raspberry Pi - rpi-userland headers not found at $${RPI_USERLAND_DIR})_**

in a string like

**_QMessageBox::information(this, "Disabling CEC support for Raspberry Pi - rpi-userland headers not found at ", $${RPI_USERLAND_DIR});_**

If is not important you can leave it unchanged.

**Comment by bovirus** [comment]
@procount 

The translation files is based on PINN 2.1.2.
I got also the latest source by GitHub reopository.

**Comment by procount** [comment]
The CEC message is a compile time message, not a user displayable message, so I don't think it is necessary to translate that.

**Comment by bovirus** [comment]
@procount 
I didn't have a big knowledge about repository and make pull request
Ina  few days I hope that I will receive new language updates then if you can you can get download and apply it to your repository.

**Comment by bovirus** [comment]
@aldatsa 
Could you please update Basque translation?

@s8321414 
Could you please update Taiwanese translation?

@Akkiesoft
Could you please update Japanese translation?

I'm sorry but you are the only translators that helped me in NOOBS project to complete your translations.

**Comment by s8321414** [comment]
OK, I will do it recently when I have free time.

**Comment by aldatsa** [comment]
I have updated the Basque translation. It's attached to this message
[translation_eu.zip](https://github.com/procount/pinn/files/706638/translation_eu.zip)

**Comment by aldatsa** [comment]
I created a pull request for the Basque translation as well: #11

**Comment by bovirus** [comment]
@procount 

Pull request: https://github.com/procount/pinn/pull/12

Pullr request (I forgot my language): https://github.com/procount/pinn/pull/13

**Comment by s8321414** [comment]
@procount 
[translation_zh_TW.zip](https://github.com/procount/pinn/files/708302/translation_zh_TW.zip)

**Comment by procount** [comment]
I added most of these translations and put a beta version on sourceforge for testing.
https://sourceforge.net/projects/pinn/files/testing/    pinn-1212a.zip
The additional Korean fonts are quite big so it is a bigger download.
Still basque, zh_tw and IT translations to add......

Thanks to everyone who contributed to the translations. 
I would add that I rely totally on your support for these and there is no way for me to validate them all. Therefore I accept no responsibility whatsoever for any incorrect translations.

**Comment by bovirus** [comment]
@procount

Thanks for the updates.

Of course you are ABSOLUTELY any responsability for all translations.

I believe that just need three other steps

-Add recovery.changes (https://github.com/procount/pinn/pull/12 - second post) to enable use of Korean fonts (sorry I forget it in my previous build request)
- Add Basque language (thanks @aldatsa)
- Add Taiwanese language (thanks @s8321414)

I contacted some my friends that have a contact with some translators to finalize (as much as possible) the other languages.

**Comment by procount** [comment]
@bovirus - I noticed your omission and already added Korean fonts in previous release 2.1.2.1a.
I have now added Italian, Basque and Chinese (Taiwanese) translations in testing/pinn-2121b.zip

I notice there is a ca.png flag but no translation_cs.ts file - is that correct?

**Comment by bovirus** [comment]
@procount 

Sorry but I didn't understand. Are available (for ca=catalan language)

**recovery/translation_ca.ts
recovery/icons/ca.png**

but is not available any language/icon file for cs language like

**recovery/translation_cs.ts**

**Comment by procount** [comment]
Sorry, my typing error!
I have no recovery/translation_ca.ts file (catalan ?) to match the ca.png file. Should there be one?
I think you forgot to include it in your commit.

**Comment by procount** [comment]
It's OK, I found a copy in your bovirus-1 branch.
Now available in testing/pinn-2121c.zip

**Comment by bovirus** [comment]
@procount 
Please take care that you will find always all files in first post of this discussion.

Question1: where the PINN program get the language name? Spanish (es) and Basque (eu) language fiels seems have the same language description in drop down list in main PINN window.

Question2: which is the file that contains WiFi settings (to avoid to overwrite it during different build test?
WPS

Question3: could be possible to add "Build xxxx" (main window) in language file (to have it multilanguage) and with a european date like dd.mm.yyyy?

**Comment by procount** [comment]
@bovirus, I compared the files you posted in the first post of this discussion with those in the pull request. There are some minor differences that might have resulted in minor problems.

**Translation_it.ts:**
Needed = Necessario or **Necessari** ?
Available = Disponibile or Disponibili ?

**Translation_eu.ts:**
language=eu or eu_ES ?

Q1: I was wondering that myself. Maybe changing the language to "eu_ES" will fix it? I will try in next release.

Q2: /settings/wpa_supplicant.conf

Q3: I will try.....

**Comment by bovirus** [comment]
@procount 
Thanks.

The right term ise "Necessario" and "Disponibile" because are related to Spazio (Space) that is singular.

Q1: please test as eu_ES.

Q2: thanks

Q3: I will wait... Thanks.

**Comment by aldatsa** [comment]
eu is part of the ISO 639-1 standard. There are two regional subdivisions: eu_ES and eu_FR. I used Standard Basque in my translation so I thought the best option was to use eu without country codes. I have used eu in many projects without issues, but if that causes problems in this project you can use eu_ES.

**Comment by bovirus** [comment]
@aldatsa 
Did you check with test image or my custom build when your run it on main window which is the name of your language in drop-down list?

@procount
Where did PINN (and NOOBS) get the language name showed in the drop down language list in main window?

**Comment by procount** [comment]
Q1 - Actually it is the ES (Spanish) and es_XA (Asturian) languages that show the same native language text names. The eu (Basque) language shows "euskara" and changing from eu to eu_ES makes no difference.
When I select Asturian, many if not all translations are still in English. So I think the es_XA files need reviewing.

**Comment by bovirus** [comment]
I will trying to rename translation_es-XA.ts (and relative icon) to translation_ast.ts and build it

**Comment by procount** [comment]
I discovered that QT uses the 2 letter language codes as defined in ISO639-1.  Asturian is not listed in this set, but in the ISO 639-2 set of 3 letter language codes as 'ast' . So it is not supported and we would need a workaround for such languages.

**Comment by bovirus** [comment]
@procount

Could you please provide link for 2 letter table ISO639-1?
It's quite strange. In some QT project is se file as xxx_ru-ru.ts (for russian).

I believe that the best way is to add in each language file a strings like "LanguageName" and use it.

In the first step we can remove Asturian language (that is not complete) but it's important to enlarge the width of drop down language selection window

**Comment by procount** [comment]
Q3 answer: "Build" is already in the translation file and can be translated. But it may not be refreshed immediately in the title bar when the language is changed. Likewise for any translations done in the main list view of OSes such as [RECOMMENDED] or [INSTALLED]. These items of text will be correctly translated the next time PINN is rebooted. Not a high priority to change at the moment.

The format of the build date in the title is fixed by the compiler and is not readily changed without a great deal of effort, so I am not likely to fix this in the short term.

I added a workaround for Asturian (and a guess at what the language name should be called)

**Comment by bovirus** [comment]
@procount 
Ok. Thanks.
Could you please tell me what files did you change and where can I get them?

**Comment by procount** [comment]
When I'm happy with them I will post an update on github here.
(I just spotted a problem putting unicode text in the source code for Asturian)

I didn't try es-XA as opposed to es_XA. 
I think it's only the countries in the ISO639-2 table that are a problem, so I'm not too worried about a proper fix at the moment.

Language box is expanded.

Re: ISO639 - Is your google-foo letting you down? 
    https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
    http://www.loc.gov/standards/iso639-2/php/English_list.php

I put a copy of pinn-2121d.zip on sourceforge so I would be grateful if you could review it for any other issues,

**Comment by softastur** [comment]
Ok, after 2 years of the first Asturian translation for NOOBS I have to say that Asturian has actually a only 639-2 ISO code "ast". I used es_XA for compatibility and because Android 4.4 (and below) didn't allow three-letter code languages. So use es_XA for Asturian is completely wrong, Asturian is a different language and not a variation of Spanish.

I should re-translate the software ASAP.

Finally, Asturian has these special characters áÁéÉiÍoÓuÚüÜñÑḷḶḥḤ

**Comment by bovirus** [comment]
@softastur 
Thanks for your translation.
I propose if you are agree that you can start finalizing the Asturian translation for NOOBS (that is the first step) then I will apply the master english template that will update teh strings for PINN.
As you can see in NOOBS project site I restarted myself the project (as localization) collectiong all translation incluse yours).

You can find more info here: https://github.com/raspberrypi/noobs/issues/364

You can find language files inside this archive: https://drive.google.com/open?id=0ByL-fx0GbfuiNGRWcVpqdE5FUVE

If you are using Windows, you can use QTLinguist to translate your .ts language file

 QTLinguist 32bit standalone: https://drive.google.com/open?id=0ByL-fx0GbfuiRnJ5XzBCOVpNNjg

Thanks for your activities.

**Comment by procount** [comment]
@softastur 
Is there a particular keyboard code used for Asturian? Do you have a special 'ast' style keyboard, or do most people use 'es' or 'us'?

**Comment by bovirus** [comment]
@procount 

I believe that you could add for any language file two new fields

NativeLanguageName
KeyboardLayout

and use it to define for each language the name that appear in dropdown language selection list and relative keyboard layout.

**Comment by procount** [comment]
I posted a question on the NOOBS github asking what format extended country codes should use - For example whether we should use es_XA, es-XA or ast for Asturian.
I have chosen 'ast' at the moment in order to display a specific Language name, as it is from the ISO639-2 list, but that doesn't really match with the format of zh_TW for Taiwan. So this might change and I'm open to further input, but I want to maintain compatibility with NOOBS too.

**Comment by softastur** [comment]
@procount Asturian uses a variation of the spanish keyboard which includes the Ḷḷ and Ḥḥ characters as you can see on the majority of Linux distros.

As I said before, Asturian cannot use es_XA as its language code because that code is invented and also Asturian has not any ISO639-1 code, only the ISO639-2 "ast" code. NOOBS must be compatible with ISO639-2 standart and deprecate the old ISO639-1 which has a limited number of languages.

Finally, I was able to update the Asturian translation for NOOBS but i have some strings untranslated because i need to see their context. I'll keep you updated.

**Comment by procount** [comment]
I have released PINN p2.1.3 which includes all the updated translations so far. 
If anyone has any additional translations I will endeavour to include them in the next subsequent release.

(I have used the code 'ast' for Asturian)

**Comment by procount** [comment]
PINN updated to v2.2 and I found a few more text items that need translating.
If anyone has the time/inclination to add them, I will accept Pull Requests or simple attachments of the translation_XX.ts files. Thanks in advance.

**Comment by procount** [comment]
PINN 2.4 is available on github for translation.

**Comment by bovirus** [comment]
@softastur
@aldatsa
@cescp
@qsypoq
@qsypoq
@fonic
@sople1
@Akkiesoft
@kadamski
@ResonantWave
@Mangero
@diorray

Could you please update your translation for new PINN release (2.4.2)?
Thanks.

@procount 

Could you please include zh_TW new language version (pull request)? Thanks.
