### ISSUE TITLE
Adding LineageOS (Question, Not an Issue)

### ISSUE THREAD

**Issue by charbeltrad** [procount/pinn#102]
Is it possible to add LineageOS v.RPI to the os list. I've tryed RTAndroid but it  reboots after 4 days and it's an "evaluation version" I like LineageOS because it seems to work fine. Thank you in advance if you do add it 👍 

Link: http://konstakang.com/devices/rpi3/CM14.1/ (or to be more specific: https://androidfilehost.com/?fid=889964283620766870)

**Comment by procount** [comment]
I have messaged the maintainer, so we'll see.....

**Comment by charbeltrad** [comment]
Alright, Thanks :)

**Comment by procount** [comment]
done
