### ISSUE TITLE
Arch download still references remote files

### ISSUE THREAD

**Issue by procount** [procount/pinn#105]
From symbios24 on sourceforge review:

About the ArchLinux both versions Arch1 and Arch2 i have downloaded all the files required for an offline installation from the sd card and it ask for a file/s between the installation from the internet, as i did my research i found out that the partitions.json file includes in the tarball section this two entry`s ---githubusercontent.com/procount/pinn-os/master/os/Arch2/boot.tar.xz--- ---archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz--- So it requires an internet connection even you you have downloaded all the necessary files for offline installation can you fix that please? as i see now the archlinux os from the OS folder is not there anymore,i will appreciate if you can make both archlinux versions totally offline like the other os Thank you

**Comment by jkw** [comment]
I did not even get Arch 1 nor 2 in the list even WITH a connection. :|

**Comment by procount** [comment]
Did you look on the "minimal" tab group?

**Comment by jkw** [comment]
I managed to get it work in latest update. 👍

**Comment by symbios24** [comment]
Has this issue fixed yet?

**Comment by symbios24** [comment]
Hello, has the issue of downloading the arch files from internet fixed?

**Comment by procount** [comment]
Not yet. Arch was done differently because it is a "rolling release" and continually updated. If I cache a copy it will soon get out of date. I will look into it in the New Year

**Comment by symbios24** [comment]
Thanks Merry Christmas

**Comment by procount** [comment]
I must have forgotten I'd fixed this because I just tried it on Arch2 and it worked fine (I've not tested Arch1)
Please re-download Arch2 with the latest PINN version and then try to install it. You should disconnect the PI from the internet when installing Arch to ensure it is getting it from your local source.

**Comment by procount** [comment]
Assuming this is now fixed
