### ISSUE TITLE
Manage pull request

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#106]
@procount 

There are 4 pull requests about language updates (2 quite old - 2 quite new).

Please process as soon as possible the pullup request, expeccially about language updates, because otherwise the translator have to start again to revise the translation.

Thanks.

**Comment by procount** [comment]
I'll try my best to do them soon.  very busy at the moment, but I appreciate all the hard work of the translators.

**Comment by bovirus** [comment]
@procount 

Please use highest priority for language updates.
Probably the 2 old requests are too old because there were many changes to the languages.
But the recent two requests (it/fr) should be applied as soon as.

Thanks.

**Comment by procount** [comment]
merged
