### ISSUE TITLE
[Question] Can I put the OSes I want to install on SD card for no downloading

### ISSUE THREAD

**Issue by ajhyperbit** [procount/pinn#116]
I’m just wondering if your can download the OSes on a computer that has a better WiFi chip (no offense to RPi3) so that I can have it just configure them instantly?

**Comment by procount** [comment]
Yes, of course. See around https://github.com/procount/pinn/blob/master/README_PINN.md#local-images-on-sd-card in the documentation. But you'll need to find where the OSes are stored.

The main list of repositories is at https://github.com/procount/pinn-os/blob/master/os/repo_list.json . 
If you load each os_list json file referenced from there, they will point to the location of the download files. In the case of RaspberryPi foundation and PINN sources, each OS is mostly located in the same directory, so you can just download the folder contents. Matt's distributions are split between sourceforge and github, so you may have to download the files individually. (The download option in PINN will do all this for you and ensure all the correct files are downloaded.)

Just put each OS in its own folder (e.g. "Raspbian") under a "/os" folder on your PINN SD card or USB stick and install them from your local source.
