### ISSUE TITLE
Uninstall OS

### ISSUE THREAD

**Issue by ghost** [procount/pinn#117]
How can I uninstall an OS I previously selected to free up space on the SD card?

**Comment by procount** [comment]
I'm afraid that is not supported.
You have 2 options: 1) delete everything by reinstalling only the OSes you need. 2) manually remove and resize partitions using a tool such as gparted and adjust /settings/installed_os.json accordingly. The 2nd option is an advanced operation though.

**Comment by ghost** [comment]
@procount How might I do this? I have Raspbian and Arch. Would I erase the `boot` partition, leaving `boot_arch` and `RECOVERY`? Or would I need to do something with `disk2s7` or `disk2s9`, shown below? 
![screen shot 2](https://user-images.githubusercontent.com/19980290/35372340-aee6068a-0199-11e8-89cb-b95e88d8bc8d.png)

**Comment by procount** [comment]
I'm sorry but I have no experience on Apple products so I don't know how to help on that platform.
This is quite an advanced topic, so I would seriously recommend backing up whatever partitions you want to keep to a USB stick (using tar, cp or rsync), re-install whichever OS you want afresh, then restore your backed up partitions over the top of it. (You may want to keep the/etc/fstab from the new installation and restore that after restoring your backup to ensure your OS works with the new partition numbering).

If you _really_ want to delete the unwanted partitions, then you  will have a lot of "googling" to do to understand how to mess about with partitions and learn the tools to do it on a Mac.  And also understand how to edit /settings/installed_os.json (not so difficult). You should have a look at https://github.com/raspberrypi/noobs/wiki/NOOBS-partitioning-explained, especially noting the partition layout _after_ v1.5.
