### ISSUE TITLE
Custom Rasplex problem

### ISSUE THREAD

**Issue by dazWiLLiE** [procount/pinn#118]
I followed the guide [here](https://github.com/procount/pinn/wiki/How-to-Create-a-Multi-Boot-SD-card-out-of-2-existing-OSes-using-PINN), making backups of existing RetroPie and Rasplex installs.

I came so far as to  "Step 2 - Add OS Meta Data".. there is no Rasplex at [sourceforge](https://sourceforge.net/projects/pinn/files/os/).

However, Rasplex is installable so these files should downloadable from somewhere? Or atleast someone can tell me what to put in the os.json file?

**Comment by procount** [comment]
Rasplex is one of Matt Huisman's conversions.
Easiest way is to use Pinn to download Rasplex to a usb stick then you will get all the meta files. Or follow the trail of json files from recovery.cmdline to find the download location.
