### ISSUE TITLE
No Network Available with LAN

### ISSUE THREAD

**Issue by MartinX3** [procount/pinn#129]
I get the "No Network Available" message.
But the Raspi 3B is connected with an Ethernet cable.
LibreElec and Raspbian both have Internet access.

_Sent from my Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by procount** [comment]
Go to recovery console with
Ctrl-alt-f2 login root password raspberry.
What is the result of ifconfig?

**Comment by procount** [comment]
@MartinX3 - Are you reporting that the "No network available" message is appearing when it shouldn't, because the Pi is connected to the network over Ethernet and PINN has downloaded the list of OSes?
Or are you reporting that the network is not connecting, even though the network cable is physically connected, so you don't get a list of OSes?

**Comment by MartinX3** [comment]
Sorry for the delay @procount .

5 Seconds after the error appears, i get the list of the images, because the box is connected with the ethernet cable.

After i closed the error message, it told me to choose a WLAN network.

The raspberry pi 3 has network over ethernet.
ifconfig is fine.

Maybe it looks too fast for a connection before giving me this error? 

_Sent from my Nexus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by procount** [comment]
Yes it looks like a timing problem.
Ethernet connections usually connect a lot faster than that. The time is extended if a wifi dongle is detected. Maybe a configurable time delay would be better so you can adapt it for your network speed.

**Comment by MartinX3** [comment]
That would be nice.
It is connected with a Fritz!Box 7170, which is connected via CAT6 Ethernet with the Router (Fritz!Box 7490).

**Comment by MartinX3** [comment]
Will that be a "wait"- or a "timeout"-timer?
I would prefer the Timeout-Timer. :)

**Comment by procount** [comment]
'networktimeout` added to PINN 2.8.3
