### ISSUE TITLE
DietPi update to 6.0 (1.6.0)

### ISSUE THREAD

**Issue by MaciekTalaska** [procount/pinn#134]
I would like to request for a fresh DietPi image.

Recently (end of January 2018) there was a new version of DietPi released  (1.6.0). Version provided by Pinn is 158. 
Unfortunately, it is not possible to update the 1.5.8 to 1.6.0 - [DietPi v6.0 | FAQ](https://github.com/Fourdee/DietPi/issues/1355) 

Could you update DietPi's image to 6.0?
Thanks

**Comment by matthuisman** [comment]
Done :)
https://github.com/matthuisman/pinn-os/commit/d134b04409be04491b4fa1353a3dfd03d5799620

**Comment by procount** [comment]
Thanks Matt.
