### ISSUE TITLE
Update PINN Support for Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by tayrayb** [procount/pinn#136]
I tried using PINN on my new RPi, but it just gives me a rainbow screen with the voltage logo on the top right. I've used Arch Linux ARM perfectly fine along with the updated Raspbian on the RPi 3B+.

**Comment by procount** [comment]
It's a work in progress....
You can try pinn-25b2.zip in the testing folder on sourceforge but some wifi drivers are missing. Please provide some feedback if you use it.

**Comment by tayrayb** [comment]
Sure thing, I'll test it out now.

**Comment by tayrayb** [comment]
I just booted it up, Wifi works perfectly fine, even picks up the 5Ghz networks I have.

**Comment by milovanderlinden** [comment]
Works perfect on my Pi 3B + too. Installed Archlinux ARM without any problems.

**Comment by AmedeeBulle** [comment]
I used this 2.5b2 release to upgrade a project running on a 3B to a 3B+ (just kept my recovery.cmdline).
Worked perfectly.
