### ISSUE TITLE
Multiple ext4 Root Partition

### ISSUE THREAD

**Issue by cb3hn** [procount/pinn#14]
Hi,

I have 3 different independent Root ext4-Partition on my big SD-Card. Is there a way to setup PINN to
boot of this Partition direct, like a x86 Grub2 bootloader? The trick is only I have to change manually any time the "cmdline.txt" the root=/dev/mmcblk0pX parameter.

Regards...

**Comment by procount** [comment]
So you mean you only have 1 boot partition that is shared between the 3 root partitions?

Pinn is not setup to manage or switch between these partitions. It switches between the boot partitions which each reference their own root partitions.

So to use PINN you would need to create 3 identical boot partitions- one for each root.

What you describe is how Berryboot works. Perhaps that would be better for your needs?

**Comment by procount** [comment]
Closing
