### ISSUE TITLE
config.txt inside raspbian

### ISSUE THREAD

**Issue by OxygenGS** [procount/pinn#145]
Ok so i installed PINN, did add lcd_rotate=2 and now the screen is good!
However, i install raspbian within it, and then wen it runs raspbian the screen goes upside down. When i try to open this in the terminal:
sudo nano /boot/config.txt
I see an empty file and cannot add lcd_rotate=2 tot he line or what so ever, how to do this?

**Comment by procount** [comment]
Once you have booted into Raspbian, it is just plain Raspbian. Nothing different to the standard image.
/boot/config.txt should still be present and should definitely not be blank. 
I can only suggest that you check your typing.

Alternatively, you can edit Raspbian's config.txt file from within PINN.
Boot into PINN and hold 'shift' to get to the menus.
Press the More button to get to the Maintenance menu, select Raspbian and press the button to Edit config. From there you can edit config.txt and cmdline.txt.

**Comment by OxygenGS** [comment]
Nice! damn i love PINN now already :D now i just need to w8 for Retropi and i am super happy!

**Comment by procount** [comment]
If you have already installed Raspbian, you'll have to remove it and install it again with the new retropie when its available.

If you want to avoid that, you can add 'showall' to pinn's recovery.cmdline to show all oses and install raspbian and the old retropie now. Retropie won't run, but when the new one is available, you could REINSTALL the new retropie over the top of the old one, therefore not trashing your current Raspbian. - just another option.
