### ISSUE TITLE
Reinstall fails with "Partition not big enough for new image" at 2nd reinstall

### ISSUE THREAD

**Issue by AmedeeBulle** [procount/pinn#152]
PINN Version: v2.8.1

When you reinstall an image, the reinstall process updates `installed_os.json` from (in my case)
```
  "partitions" : [
"/dev/mmcblk0p7",
"/dev/sda7"
  ],
```
into
```
  "partitions" : [
"/dev/mmcblk0p7",
"PARTUUID=3be488f6-07"
  ],
```

If after that you attempt to re-install a second time the same image, it will fail with `Partition not big enough for new image`.

Workaround is to manually fix/revert the partition name in  `installed_os.json`

(My partition is Raspbian Lite)

**Comment by procount** [comment]
That's interesting/odd/unexpected !
I'll take a look.

**Comment by procount** [comment]
Fixed in p2.8.2
