### ISSUE TITLE
Pinn Add Volume

### ISSUE THREAD

**Issue by dschamal** [procount/pinn#154]
Hello,
I have an Raspberry 3B + with 230GB SSD to boot
Pinn version is 2.8
Now in the Pinn Install menu some OS version but the Volumio 2 not
I have change in the recovery.cmdline showall and add
repo://...matthuisman..staging.json
no error! Message
how can i enable Volume 2 throw the select menu???
if I select RPI3 without Plus in the menu there is Volumio, but after the
install I can Not boot and the SSD must Format new!
Please help me I need contact to Matthuisman but I don't no the way
Thanks
dschamal

**Comment by procount** [comment]
Hi,
You posted this on the forum and Matt already answered you here -> https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&start=375#p1315110

Volumio does not support running from an external ssd. It only works on an SD card.
