### ISSUE TITLE
RecallBox

### ISSUE THREAD

**Issue by Denethor85** [procount/pinn#155]
The RecallBox image is no longer avaiable on PINN?

how can I add it?

**Comment by procount** [comment]
It still seems to be listed for all models EXCEPT the RPI 3B+.
What model do you have?

**Comment by Denethor85** [comment]
3B+.... Isn't supported?

**Comment by procount** [comment]
No.
Recalbox is from Noobs.
The recalbox maintainers need to upgrade it for the 3B+.
When they have done it I'm sure it will be available again.
Meanwhile, Why not try batocera or one of the others?

**Comment by Denethor85** [comment]
I'm using Retropie, but I've heard a lot of good things about RecallBox...I was tempted to try it

**Comment by procount** [comment]
According to this thread on their forum -> https://forum.recalbox.com/topic/13200/raspberry-pi-3b-plus-compatible/216
they are working on it, but have a lot of work to do not to break anything.
Be patient and it will come.
