### ISSUE TITLE
priority of before-reboot.sh vs autoboot.txt

### ISSUE THREAD

**Issue by jovrstra** [procount/pinn#157]
Hello,
Perhaps some strange questions... 
The manual states that before-reboot.sh is executed before the selected operating system is booted. 
1. Is it also executed when there is an autoboot.txt file?
2. (if yes on 1) If the before-reboot.sh modifies autoboot.txt, does it change which OS is booted, or is the choice of what to boot made before before-reboot.sh is executed?

The reason is: I would like to have the option in a Raspbian to allow me to select what to boot next. It could do this by modifying autoboot.txt and rebooting. But that makes the change permanent (every next boot will boot this os). The before-reboot.sh script could  be used to modify or remove autoboot.txt, so that the next reboot is again a normal one (or into that Raspbian). Alternatively, the other OS could also modify autoboot.txt, but a modification of before-reboot.sh - if it would work - seems more robust and constitutes just a single change.

Thanks!

**Comment by procount** [comment]
1. No. Autoboot.txt works at the firmware bootloader level and bypasses PINN altogether.
2. N/A

After selecting the next OS to boot from Raspbian, will you be rebooting immediately? If so, why not just use:
`sudo reboot <n>`  
where n is the boot partition of the OS you want to boot into.
e.g. 
`sudo reboot 8`
for the 2nd OS. That way it will boot directly from Raspbian into the other OS without going through PINN.

> so that the next reboot is again a normal one

That depends what you mean by a `normal` reboot. It normally means the last OS booted from PINN, but if you set a `sticky` boot flag, then it will always boot the sticky OS unless the user intervenes and chooses a different OS to boot for the next boot only.

Does that help at all?

**Comment by jovrstra** [comment]
That really helps...! 
So I can set just autoboot.txt to boot in that Raspbian, and then don't even have to bother with anything else... just use `sudo reboot <n>`. Even better! I did not know `sudo reboot <n>` was possible. 

In case you wonder why I want to do it: it allows me to use an unsupported device (cheap dsi touchscreen) for boot selection: always boot in a Raspbian where it works and then just reboot from there (e.g. using a script launched from a desktop shortcut). It is bit a slower to boot but that is not important to me and it seems the only option when nothing else is connected to the Raspberry to provide an input.
Thanks!

**Comment by procount** [comment]
> cheap dsi touchscreen

I thought the RPF 7" touchscreen was the only one that supported the DSI ribbon connector?
Or you you mean one that is connected to the GPIO pins, like a Waveshare or Adafruit screen?

**Comment by jovrstra** [comment]
Sorry... my mistake... I meant SPI... yes... it is on the GPIO pins, a cheap Waveshare clone. :)
