### ISSUE TITLE
【Feature Request】Add "reboot" button on the bootmenu

### ISSUE THREAD

**Issue by qcsunny** [procount/pinn#159]
I set "remotetimeout=5 forcetrigger vncinstall bootmenutimeout=5" in the recovery.cmdline.

However,when I finished installing "project space" , it would automatically change into bootmenu, there was no system to boot obviously. I had to power off the rpi manually. 

So I guess, is it more convenient while a “reboot” button next “boot” button？It may also potentially save time when reboot it before an OS is booted under the circumstance having no enough time for the user to getin PINN recovery menu

![d0c88aa5feea70eb409ab478e48b1a85.png](https://img.m-team.cc/images/2018/06/08/d0c88aa5feea70eb409ab478e48b1a85.png)

**Comment by procount** [comment]
Ah yes. I haven't documented it but you can just press Esc and it will reboot back into PINN. It probably shouldn't go to the boot menu if there are no bootable OSes installed anyway.

Do you find remoteboottimeout=5 is long enough? I think I had to set mine to 20 to allow me time to get in.

**Comment by qcsunny** [comment]
Thanks for your reminding.
1. Nope, it seems like not work for me.When I only install `project space`，then it shows this picture and I press `Esc`, it still go to the bootmenu
![24c8d6878a7163d652e7392e32f40c93.png](https://img.m-team.cc/images/2018/06/09/24c8d6878a7163d652e7392e32f40c93.png)

2. `remotetimeout=5` may be not enough because I have failed to get in the PINN menu several times. When I get the remote pictures , it has already entered the boot menu. So I would like to reboot it immediately and try it again, instead of booting the system first. 

Normally, I will get the following picture if I connect the pi at the right time (Network ACT led light up or wait for seconds？)
![b3ed0ac620c597807b999091a42452a2.png](https://img.m-team.cc/images/2018/06/09/b3ed0ac620c597807b999091a42452a2.png)

`bootmenutimeout=5` is enough for me. Once I get the remote pictures, the countdown will stop and let me to select the OS.

**Comment by qcsunny** [comment]
Sorry, I misunderstood what you mean
Now it's OK. When I press ESC on the boot menu, it will reboot.

**Comment by qcsunny** [comment]
In general, I can press ESC on the bootmenu to let it reboot, “reboot” button is no need. :smile: I don't notice this feature before.

And, it cannot detect wether the real  OS is already installed and will enter the bootmenu. Is the situation  just for me?

**Comment by procount** [comment]
I have a few things to fix, but you have a workaround, so they will be low priority.
1. document pressing Esc on the bootmenu will reboot into PINN.
2. Add a reboot button to make this more explicit (especially for CEC users)
3. Prevent going to bootmenu after installing OSes, if there are no bootable OSes installed.

**Comment by procount** [comment]
Done in v2.8.5
