### ISSUE TITLE
Reinstall isn't working for Lineage - waveshare

### ISSUE THREAD

**Issue by esoterik-dev** [procount/pinn#162]
Reinstall is not working for lineage - waveshare (maybe for other builds too). Gives an error: 
has incompatable partitons

The Tab containg All he Lineage Builds has no label as well.

**Comment by procount** [comment]
Incompatible partitions is solved.
Discovered why the tab group name is missing.
Should be fixed in next release.

**Comment by procount** [comment]
Fixed in v2.8.5
