### ISSUE TITLE
piCore / TinyCore

### ISSUE THREAD

**Issue by timoteo7** [procount/pinn#165]
This is very good for RPI 0

can support this ?

http://tinycorelinux.net/9.x/armv6/releases/RPi/piCore-9.0.3.zip

**Comment by procount** [comment]
Added

**Comment by timoteo7** [comment]
os_list.json:
            ....
            "tarballs": [
                               "http://downloads.sourceforge.net/project/pinn/os/picore/boot.tar.xz",
                               "http://downloads.sourceforge.net/project/pinn/os/picore/boot.tar.xz"
            ],
            ....

maybe need change to this to work:
 ....
            "tarballs": [
                               "http://downloads.sourceforge.net/project/pinn/os/picore/boot_pic.tar.xz",
                               "http://downloads.sourceforge.net/project/pinn/os/picore/root_pic.tar.xz"
            ],
            ....
