### ISSUE TITLE
Missing function definitions in deploy.sh

### ISSUE THREAD

**Issue by m-roberts** [procount/pinn#166]
Function definitions for things such as `create_etcher_img` ([here](https://github.com/procount/pinn/blob/master/deploy.sh#L50)) appear to be missing.

I am interested to know how you go from a folder with files in it to the pinn-lite.img.zip Etcher image file, so it'd be great to see what is actually happening in this step!

**Comment by procount** [comment]
Hmm. Well, deploy.sh isn't really supposed to be there as it's not a generic solution - it's just for my personal deployment for transferring from one git repo to another (trying to keep compatibility with NOOBS repo, and yet creating my own documentation), so it has a lot of hard coded folders etc. in it. If you've got the PINN git repo, it has already been "deployed"! I think I put the file there just to make sure it got backed up before I created the etcher version. 

Anyway, you're more interested in  `create_etcher_img`, so from one UoS grad to another (:wink: small world!) Here it is:

```
!/bin/bash

image=pinn-lite.img
zippedimage=pinn-lite.img.zip

rm $image
rm $zippedimage
fallocate -l 66M $image
fdisk $image << EOF
n
p
1
8192

t
c
w
EOF

l=$(sudo losetup -f)
echo $l

sudo losetup $l -o 4194304 $image
sudo mkfs.vfat $l -n RECOVERY
mkdir -p img
sudo mount $l img
sudo cp -r dist/* img
sleep 1
sudo umount img
sleep 1
sudo losetup -d $l
sleep 1
zip $zippedimage $image
```

You'll obviously need to adapt it, but you'll see the principle.
