### ISSUE TITLE
Reinstall and Replace Error - Unable to upgrade to the latest release.

### ISSUE THREAD

**Issue by qrao** [procount/pinn#175]
Reinstall and Replace OS feature has been broken. It appears to be writing to the boot partition, rather than the root partition. I noticed you have made a fix to the reinstall problem in P2.8.5.1. However, I am not able to update to this release on my RPi2. How do I get the hotfix release be detected?

**Comment by procount** [comment]
Why can't you upgrade to the new version?

Try going to the maintenance menu. Select PINN as the only checked item then click reinstall. You must be connected to the internet. The new version should be detected and installed.

An alternative is to manually update.
Put your pinn sd card in a PC. Make a copy of recovery.cmdline. dowload pinn-lite.zip and unzip all the contents except recovery.cmdline over the top of your existing pinn installation. If you make a mistake and overwrite recovery.cmdline then restore the copy you made.

Check recovery.cmfline DOES NOT contain 'runinstaller' and delete that option if it exists.

Now put it back in your pi and boot the new version.

**Comment by qrao** [comment]
I will try the manual update method. When I go into the maintenance screen, and update PINN, it said something to the effect that "it is already at the latest version", even though I am still at  P2.8.5. Is the version check not taken into account for the hotfix version number?

**Comment by procount** [comment]
You can check the current version number in /mnt/BUILD-DATA
