### ISSUE TITLE
EmteriaOS for PINN

### ISSUE THREAD

**Issue by wongmisterius** [procount/pinn#177]
will it be possible to add emteria OS (Android 7.1.2 for Rpi3)? what happens is that I have already tried RTAndroid and LineageOS and I did not like it because the first one is an "evaluation test" and the other does not work 100% but emteriaOS I have tried it and it works better than all.
And what I want to do in question, is a dual boot to have Retropie4.4 with EmteriaOS

**Comment by procount** [comment]
It looks like Emteria needs a login to download it, and it uses its own installer, so it may be more tricky to use.
I am currently updating Lineage to a newer version that should work better, so maybe that will solve your issue.

**Comment by wongmisterius** [comment]
Yes, emteria uses its own installer but it leaves the files stored in a folder.
I can upload a copy of emteria to the cloud and I publish the link here.
Also emteria allows to update from the same system.So updates will not be a big problem

**Comment by procount** [comment]
The free version is also an "evaluation test" that reboots every 8 hours.

**Comment by wongmisterius** [comment]
I did not know that, but in the same way, could you do it if I share the image of emteria.
I do not worry about restarting every 8 hours, since the system is better optimized and that matters to me.

**Comment by procount** [comment]
I have asked the maintainer for clarification on their EULA and whether it is permissable.

Emteria looks like a spin-off from RTAndroid anyway.

**Comment by wongmisterius** [comment]
ok i will wait for your answer

**Comment by wongmisterius** [comment]
EDIT: Link deleted

**Comment by procount** [comment]
Thanks.
Looks like it might be possible. Stay tuned....

**Comment by lurch** [comment]
Hopefully the Emteria maintainer won't get upset about you publicly sharing a link to their image...

**Comment by procount** [comment]
Actually, I don't need the link because I already downloaded the files. 
It's the free evaluation version, so it shouldn't matter, but I deleted it just in case.

**Comment by lurch** [comment]
IMHO it's always best to err on the side of caution :wink:

**Comment by procount** [comment]
UPDATE: unfortunately, Emteria uses the uboot boot-loader, so for now it will not be included (until we work out a way to replace uboot with the standard boot loader method)

**Comment by procount** [comment]
Emteria OS is now available.
