### ISSUE TITLE
OpenWRT updated for RPi 3 B+

### ISSUE THREAD

**Issue by TatharNuar** [procount/pinn#180]
OpenWRT v18.06.0 came out recently, and it adds support for the Raspberry Pi 3 B+.  A previously closed issue mentioned @procount requested to be notified when this became available: #56

**Comment by procount** [comment]
Thanks. 
Yes, I saw your previous post. It is in test now.

**Comment by procount** [comment]
Lede / OpenWRT 18.6.0 is now included.
