### ISSUE TITLE
Does PINN run on Asus Tinker Board?

### ISSUE THREAD

**Issue by Jannis-D** [procount/pinn#181]

**Comment by procount** [comment]
No idea. I don't have one.

**Comment by Jannis-D** [comment]
I need to know, because I'm thinking of buying the Tinker board.

**Comment by procount** [comment]
Why don't you ask on the forums, then?
Maybe someone with a tinkerboard will have tried it.
I will not be adapting pinn to run on it specifically because I don't have one to test.

**Comment by Jannis-D** [comment]
No problem, I will do it
