### ISSUE TITLE
Cannot download DietPi due to certificate error

### ISSUE THREAD

**Issue by d1g33k** [procount/pinn#183]
The DietPi image does not download due to inability to verify the domain certificate (attached image). I am using the latest version of PINN with the Resize webapp from Matt.

![error](https://user-images.githubusercontent.com/30001578/44616916-f6802280-a876-11e8-888d-824a239d2a35.jpg)

**Comment by procount** [comment]
Ping @matthuisman
?

**Comment by matthuisman** [comment]
Just tested, downloaded, installed and ran fine for me.
So maybe was just a glitch with Sourceforce.

**Comment by procount** [comment]
Closing as no more feedback.
