### ISSUE TITLE
RaspArch availability

### ISSUE THREAD

**Issue by dobunzli** [procount/pinn#185]
Hello,

Would it be possible to add http://raspex.exton.se/?p=859 to the list of available OS ?
Is there a way I can do that myself ?

Sorry if I posted in the wrong place, but didn't find a forum.

Thanks in advance.

**Comment by procount** [comment]
Posting here is fine.
Main forum thread is at https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574

I already have lineage and soon emteria. Does this version give anything extra?

You can certainly convert it yourself if you want. Have a look at the wiki and at the lineage version. It is a bit more difficult than a standard linux version but not impossible.

**Comment by dobunzli** [comment]
RaspArch is based on arch linux and comes with a few installed features (Desktop LXDE, browser etc...). 
It is more easy for newbies like me to install Arch Linux ARM than the "standard" version where everything has to be installed and configured. 

So, in my comprehension it is not the same than lineage or emteria...

Maybe an interesting feature for PINN would be the possibility to install "whatever iso" on a prepared "ProjectSpace" by selecting the iso from the user interface ? But I don't know if it is technically "doable"...

I will look at the wiki to see if my computer skills are enough high to try something with the RaspArch image...

Anyway thanks for PINN which is already a great app to help installations on rasperry pi !

**Comment by lurch** [comment]
> It is more easy for newbies like me...

What's wrong with Raspbian? :wink:

**Comment by dobunzli** [comment]
Nothing is wrong with Raspbian but I had problems installing a light version of bitwarden on it:
https://github.com/dani-garcia/bitwarden_rs

I found a package for Arch Linux that works: https://aur.archlinux.org/packages/bitwarden_rs/
