### ISSUE TITLE
Please update Gentoo64 images (v1.3.0 released)

### ISSUE THREAD

**Issue by sakaki-** [procount/pinn#190]
Hi @procount -

I've just released **v1.3.0** of the [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit) image (including Pi-Top variant), and redone the first slide of the marketing deck to match (available [here](https://github.com/sakaki-/resources/blob/master/raspberrypi/pi3/noobs/Slide1.png)).

Whenever you get a chance, would you mind updating the images on PINN?

Many thanks for your help!

sakaki

**Comment by procount** [comment]
Sure thing.

**Comment by procount** [comment]
Done

**Comment by sakaki-** [comment]
Thanks! I've [added a short post noting this](https://www.raspberrypi.org/forums/viewtopic.php?p=1371709#p1371709) to the announce thread.
