### ISSUE TITLE
PINN 2.9.0 development

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#193]
Hello,

Any news about version alignment to NOOBS release (2.9.0)?

**Comment by procount** [comment]
Did you look at the 2.9.0 enhancements? A lot of them are pull requests from PINN to fix some issues in NOOBS and bring it up to date with PINN improvements. So there's nothing to do 😃.

EDIT: There are some minor additional changes and a bump to the firmware, but they'll get included in PINN in the next release.

**Comment by bovirus** [comment]
Thanks. :-)
