### ISSUE TITLE
Add support for gamepad selection of OS

### ISSUE THREAD

**Issue by colinchilds** [procount/pinn#2]
For those of us who have Retropie installed, it would be awesome to be able to select the OS to boot into using the gamepad already plugged into the device, rather than having to plug in a keyboard or mouse.

**Comment by procount** [comment]
Thanks for the suggestion

**Comment by Norde** [comment]
This would be a very nice enhancement !

This requires additional kernel modules (like xpad for xbox controler).
Does addition of such modules is conceivable for PINN?

**Comment by procount** [comment]
PINN does not use a modular kernel, so it's a bit problematic at the moment. But I hope to be able to do something about it at some point, just not immediately.

**Comment by Norde** [comment]
What, not immediately ??? 😡  :smile:



Effectively, without modular kernel, there's no easy implementation possible. Do you know some alternative/ tricky way ?


By the way, thank you for all your work on PINN!

**Comment by andrebadaia** [comment]
I am interested in this solution too! Maybe you can instruct us to recompile PINN for that support! Thanks!

**Comment by procount** [comment]
PINN now includes modular kernel support, so if you have some drivers for your gamepads (preferably in source format) I can take a look at what is needed to include them .

Please note that I cannot support Bluetooth controllers yet,  but USB or gpio drivers should be ok.

**Comment by andrebadaia** [comment]
It's awesome!!! I have various types of joysticks, but the XBOX 360 is OK. It uses the xpad driver on linux, isn't?

**Comment by procount** [comment]
I don't have any gamepads to test his feature, so I'm going to have to rely on everyone else to provide feedback on this.
I've added an xpad and joystick driver to PINN and uploaded a test version to
https://sourceforge.net/projects/pinn/files/testing/joystick-33d.zip/download .

If you want to test it, please download joystick-33d.zip and install it to a blank FAT32 formatted SD-card just as you would pinn-lite.zip.

I haven't added any support into PINN to actually use the driver yet, so at this stage it's just a question of testing whether the gamepad can be detected and is usable.

Please boot PINN with your USB gamepad attached.
Once booted, drop into the recovery shell by pressing the ctrl-alt-f2 combination and login with the username/password of root/raspberry.
At the prompt type 
```
jstest /dev/js0
```
Make a note of any text that is displayed.
Press the buttons on your joystick and make a note of any messages that are created.

**Comment by andrebadaia** [comment]
It's worked! The PINN detects the joystick correctly, and all axes and buttons were detected by jstest on /dev/input/js0. The variations of axes go to -32768 to 32767, and buttons, switch between on and off. Thanks a lot for the effort!!

**Comment by procount** [comment]
@andrebadaia Could you please post some output from jstest so I can see what it produces?
What do you expect the joystick buttons to do in PINN?

**Comment by lurch** [comment]
&lt;tongue-in-cheek&gt; Can you add a game of Tetris to PINN, so that we have something to do while waiting for the OSes to install? &lt;/tongue&gt; :wink:

**Comment by andrebadaia** [comment]
It is just equal to Linux, the same buttons and axes in the same place. I'll map for you:

Axis 0: Left Analog X 
Axis 1: Left Analog Y
Axis 2:  LT 
Axis 3: Right Analog X
Axis 4: Right Analog Y
Axis 5: RT
Axis 6: D-pad X
Axis 7: D-pad Y
Button 0: A
Button 1: B
Button 2: X
Button 3: Y
Button 4: LB
Button 5: RB
Button 6: Back
Button 7: Start
Button 8: Mode
Button 9: Left Analog Click
Button 10:Right Analog Click

![image](https://user-images.githubusercontent.com/42654336/62080880-de9fe400-b227-11e9-8659-f146af00208b.png)

About the use, I expect the behavior is the same when the package xserver-xorg-input-joystick of X, when the left analog controls the mouse pointer, A and B are the left and Right click. The other buttons have other functions, but the minimal usability is enough (just for select OSes).

**Comment by procount** [comment]
> Can you add a game of Tetris to PINN

What? Tetris? What's wrong with Minesweeper? 😉

**Comment by lurch** [comment]
> but the minimal usability is enough (just for select OSes).

Presumably the minimal usability for just selecting which OS to boot is UP, DOWN and SELECT ?
Might be hard to implement xserver-xorg-input-joystick, given that PINN doesn't use X...

**Comment by procount** [comment]
I'll probably do something like duplicating the CEC remote functionality

**Comment by andrebadaia** [comment]
In fact, the joystick replaces the mouse on X, but you can improve the funcionality associating some important functions to the buttons and axes. It's not like a keyboard, but helps a lot!!! I use PINN with Raspbian, Retropie and OSMC, connected on my TV, and all controlled by joystick (I use a virtual keyboard on Raspbian, together with xserver-xorg-input-joystick), but I need the keyboard to choose the OS on PINN.

**Comment by procount** [comment]
I have made a first attempt in https://sourceforge.net/projects/pinn/files/testing/joystick-33e.zip/download 
It compiles, but I've done NO testing whatsoever, so it's probably very buggy at the moment. 
If you have time to try it out and feed back I would appreciate it.
I just mapped left analog to the mouse cursor, A=left click, X =Cancel (Esc).

**Comment by andrebadaia** [comment]
Yes, it didn't work. The gamepad does nothing on GUI (it continues working on jstest).

**Comment by procount** [comment]
Sourceforge has been a bit slow and hasn't indicated anyone had downloaded the file, so I was lazy and pushed up several versions of the same file with various fixes in it. The early ones wouldn't have worked but I thought the last one would have worked. 
Can you check you have the latest one? I pushed it up at 15:16 (BST)

**Comment by andrebadaia** [comment]
I tried again (I've downloaded the last one version presented in sourceforge files) and it doesn't work too.

**Comment by procount** [comment]
OK thanks. I'll create a debug version to display some traces in /tmp/debug and we'll see if we can find out what is going on.
Out of interest, does that file contain anything related to the joystick already?

**Comment by andrebadaia** [comment]
Sorry, I don't understand your question. What do you mean?

**Comment by procount** [comment]
Once booted, drop into the recovery shell by pressing the ctrl-alt-f2 combination and login with the username/password of root/raspberry.
At the prompt type
`less /tmp/debug`
Browse using the cursor keys to see if there is any mention of the joystick.
Press 'q' to quit.

You could also try 
`tail -f /tmp/debug`
And then press the joystick buttons and see if there are any messages displayed.

**Comment by procount** [comment]
I pushed up joystick-33f.zip with more trace & debug messages.

**Comment by andrebadaia** [comment]
less /tmp/debug

It recognizes the joystick (Microsoft X-BOX 360 pad - 8 axes, 11 buttons), load CEC mappings from ":/cec_keys.json" and load joystick mappings from ":/joy_keys.json". No error reported.

Pressing the buttons and axes didn't make any difference.

**Comment by andrebadaia** [comment]
Where are the files cec_keys and joy_keys.json? I didn't find them on PINN or SETTINGS partitions...

**Comment by procount** [comment]
Is that still with v3.3e or the new v3.3.f?

**Comment by andrebadaia** [comment]
3.3e. I'll try the 3.3f.

**Comment by procount** [comment]
> Where are the files cec_keys and joy_keys.json? I didn't find them on PINN or SETTINGS partition..

https://github.com/procount/pinn/blob/master/README_PINN.md#cec-control

**Comment by andrebadaia** [comment]
Do I have to create these files?

**Comment by procount** [comment]
No. Not for this testing - it will just complicate matters. I was just answering your question.

**Comment by andrebadaia** [comment]
The /temp/debug output is here (3.3f):

![image](https://user-images.githubusercontent.com/42654336/62312018-789fa080-b463-11e9-8d2c-4dd0b008311f.png)

**Comment by procount** [comment]
It would be more nteresting to see the log after that, after you have pressed all the buttons on your joystick.

To capture the debug logs you can do the following: Press Ctrl-Alt-F2 to get to the recovery shell. Use the username:root password:raspberry.

```
cd \tmp
mount -o remount,rw /mnt
cp debug /mnt/debug.txt
sync
```
Now you can turn off the Pi, put your SD card in a PC and copy the debug.txt file to your PC.

**Comment by andrebadaia** [comment]
That's it.

[debug.txt](https://github.com/procount/pinn/files/3457988/debug.txt)

**Comment by procount** [comment]
Thanks. Interesting. I assume you pressed joystick buttons during all of that debug capture, so as nothing is being detected I shall have to think again.

**Comment by andrebadaia** [comment]
I did the test again, to be sure... I pressed all gamepad buttons for almost 1 minute. 
[debug.txt](https://github.com/procount/pinn/files/3458387/debug.txt)

**Comment by procount** [comment]
Try Joystick-33g.zip

**Comment by andrebadaia** [comment]
It's a beginning! The mouse pointer started to move in g revision!

Reports:
The Y axis is inverted;
The moviment is not fluid, seems like jumps... If you try to hold the axis, the pointer goes crazy!
The A button is ok, I could navigate on all the PINN windows with it;
The X button closes the window - if you press it on boot window, the PINN reboots.

Well, that's it! You are on the right track!

[debug_g.txt](https://github.com/procount/pinn/files/3459411/debug_g.txt)

**Comment by procount** [comment]
Yay! That's mostly as expected.
The mouse movement will never be smooth like a proper mouse, but I can improve it.

> f you try to hold the axis, the pointer goes crazy!

I'm not sure what you mean by that?

**Comment by andrebadaia** [comment]
When you hold the axis (for the left, for example), the pointer goes to other position, down, or up! You have to "press and leave" the axis to get the right moviment.

**Comment by procount** [comment]
Can you try joystick-33h?
I've added some more buttons etc. Try the left and right analog, plus D-pad.
The right  analog joystick should behave differently and have some acceleration which you can alter by modifying joy_keys.json where you can also see the mappings I added in joy_keys.json. This is similar to the cec_keys.json and documented in the previous link I sent you: https://github.com/procount/pinn/blob/master/README_PINN.md#cec-control
You should be able to map any button onto any of the available keys.
Please try it out and experiment with the key buttons to see which works best with the joystick.

**Comment by procount** [comment]
Do you have any more feedback on this? Does it work better now?

**Comment by andrebadaia** [comment]
I am sorry, I am back to work and I had no time to keep testing...

**Comment by Norde** [comment]
I'll be able to test this during october :)

Just out of curiosity, what prevents / makes complicated the support of gamepad via bluetooth?

**Comment by procount** [comment]
Mainly bluetooth itself.
NOOBS & PINN are designed to be quite small and the bluetooth stack can be quite large.
There are also complications with having to pair devices (and remember them).
I intend to look at it at some point, as I have a bluetooth keyboard I would like to use with PINN myself, but I have more pressing issues to look at first.

**Comment by Norde** [comment]
Ah yes I understand, a lot of work for a non-essential function ^^

Anyway thank you for all the work done on Pinn!

**Comment by RaspberryPiFan** [comment]
@Norde Did you test it?

**Comment by procount** [comment]
Joysticks and gamepads supported in v3.3.2

**Comment by Norde** [comment]
Sorry, I'm arriving a little (a lot) late for the tests.

I'm using an Xbox one controller (rev 1708) with a rpi3B +.

Something strange happen with pinn 3.3.2 (and testing version 33h) :
My controller is detected (in /dev/input/js0).
However the controller seems not "paired" (the home button of the controller light up when pairing is ok, if not controller is just charging).

Most of time light stay off (and not input is detected).
In rare case controller pair well after random time (light is up and inputs works) and launching jstest (on /dev/input/js0) force this pairing and then controller works.

And there's nothing in the debug log about this (only "loading CEC and joystick mapping" when pairing is ok).


Some clue about this strange behavior ?

**Comment by procount** [comment]
What do you mean by "paired"?
PINN dies not support Bluetooth, only USB, and there Is no pairing in USB.

**Comment by Norde** [comment]
I'm using USB of course.
I say "paired" in oposition of "charging" (Xbox One controller has a battery), i misspoke.

The gamepad is recognized under /dev/input/js0 but only charging (input are not listened), except in rare random cases (that I can't reproduce) or when i'm listen with jstest wich seems force the "input listening state".

**Comment by procount** [comment]
Sorry, it's been a while since I did this so I have to remember.... :wink: 
Did I put jstest in PINN? Or are you using it in Raspbian?
If the xboxdrv detects your gamepad it should announce the type and capabilities in the debug log.

**Comment by Norde** [comment]
I understand, no problem :)
But the fact that I misspoke didn't help ^^'

You've put jstest in joystick test release (33h here).
In debug log only a "No joystick found" appears. Yet my gamepad device entry is under /dev/input/js0.
When using jstest nothing more appears in the debug.

**Comment by lurch** [comment]
If the controller has a battery, then I'm guessing it's a wireless controller, which (presumably) connects to a special receiver USB dongle? I know noting about Xboxes :wink: 

Perhaps there's a delay between the controller and/or the dongle powering up (you mentioned "not paired" earlier), and this delay is causing PINN to not see any joysticks when it tries looking for them? :man_shrugging: :man_shrugging:

**Comment by Norde** [comment]
There's no special usb dongle. The controller has  native bluetooth and a usb port for wire connexion.

But you're right, there's a little delay between cable connection/powerup of the controller and the "ready status".

**Comment by procount** [comment]
What is the output from `lsusb` when your joystick is attached?

**Comment by Norde** [comment]
`Bus 001 Devices 005: ID 0a12:0001`
`Bus 001 Devices 001: ID 1d6b:0002`
`Bus 001 Devices 009: ID 045e:02ea`<- joystick (xbox one s controller)
`Bus 001 Devices 003: ID 0424:2514`
`Bus 001 Devices 002: ID 0424:2514`
`Bus 001 Devices 007: ID 0424:7800`
`Bus 001 Devices 004: ID 046d:c316`

I've the got same output wether joystick is "charging" or "connected" (obtained after running jstest) state (only joystick Devices number change).

**Comment by lurch** [comment]
I think the Device number changing indicates that (from the Linux-side of the USB connection) the device appears to have been removed and reconnected (i.e. it's re-enumerated itself when the jstest switches its state).

It might be interesting to get the `lsusb -v -d 045e:02ea` output in both the "charging" and "connected" states?

**Comment by procount** [comment]
You'll get more comprehensive results from `lsusb` in Raspbian. The PINN version is rather limited.
But it's enough to confirm that your controller should be supported:
> 0x045e, 0x02ea, "Microsoft X-Box One S pad", 0, XTYPE_XBOXONE 

So maybe it is a timing issue. I'll have to try re-establishing the joystick later on in the process, somehow....

**Comment by Norde** [comment]
I can't reproduce this bug under raspbian (the xbox one s controller is directly recognized, never only in "charging" state).

And I don't have enough knowledge yet to properly add a complete lsusb/usbutils to Pinn's buildroot, sorry :/

**Comment by lurch** [comment]
I didn't realise that `lsusb` in PINN is a limited version. Sorry for adding confusion to the conversation :confused:

**Comment by procount** [comment]
Not at all. I was going to ask for PID:VID anyway...
`lsusb` symlinks to a busybox implementation in PINN.

**Comment by procount** [comment]
@Norde - I put a new beta version up on sourceforge at https://sourceforge.net/projects/pinn/files/testing/pinn-332b.zip/download

It repeatedly tries looking for a joystick over the first 30 seconds or so.
Don't know if it will fix your problem, so please give it a go and let me know if it is any better.

The other minor change is that '+' and '-' keys on the main recovery menu will change the font size, although it is far from perfect yet.

**Comment by Norde** [comment]
@procount - This fix the problem for Xbox One S gamepad (and certainly for all the other gamepad with a connection delay), thanks a lot !

'+' and '-' keys works well. Although there's some text collision (for the "volume installation" area at the bottom of the recovery menu window)


However there is another problem with the Xbox One S gamepad (and maybe others too): the mouse is uncontrollable with analog sticks.

It's due to the behavior of analog sticks:
They return a value different from 0 when they are in their initial position (checked under jstest). This value changes after each use of the joystick (probably due to small mechanical inaccuracies when returning to initial position) and seems to go from -2500 to +2500.
The only way to avoid this problem is therefore to ignore the values between -3000 and -3000 (maybe 4000 to be sure).

**Comment by procount** [comment]
That's great to hear. How long does it take for the Joystick to be recognised? (Maybe you can take a look at /tmp/debug and see how many "Joystick not found" messages there are?)

The font size is just an experiment. It needs to be smarter.

I've not been able to try any analog joysticks because I don't have any, so it was just a guess. I will add some deadband in the middle and maybe you can help me parameterise it. I think I built in some calibration settings in the joy_keys.json file, so maybe I can add the deadband to that.

**Comment by Norde** [comment]
It's almost instantaneous.
Only one "No Joystick found" in /tmp/debug and the controller is recognized just after "new drive selected" event.

Built in deadband calibration settings in the joy_keys.json file is a good idea.
So everyone can adapt the deadband according to the used gamepad 👍

For the font size what type of graphical interface are you using?
(depending on the limitations I can offer a redesigned graphical interface, but I think that PINN is not intended to embed an advanced graphical server)

**Comment by procount** [comment]
OK. I'll try some adaptions for the analog joystick so you can try them out.

NOOBS & PINN are based on Qt4.8. There are more capabilities in Qt5, but I'm not in a position to change to that yet.

**Comment by procount** [comment]
Actually, if you can edit joy_keys.json, just change the line:
`            "threshold": 1,`
to
`            "threshold": 3000,`
and it should give you the deadband you need.

**Comment by Norde** [comment]
It's works well, thanks :)

I just have strange behavior with the cursor.
Sometimes it goes in one direction (with progressive acceleration). It cannot be canceled (using the analog stick in the opposite direction only blocks the cursor until we release the stick).
You must wait until the cursor has reached one end of the screen to regain control.

Nothing in the values obtained under jstest or displacement method in "joystick.cpp" can explain this.
I'll investigate further.

**Comment by procount** [comment]
Maybe PINN is not processing joystick analog events fast enough so they are building up in a queue. I'm not quite sure why it would be much slower than using a digital joystick though. I'll look into it.

**Comment by Norde** [comment]
This seems to be a good guess since this bug only occurs during a long press on the analog stick.

The difference may be due to the fact that an analog stick sends multiple values ​​(often on several axes) whereas a digital pad sends only one value on a single axis 😶

**Comment by lurch** [comment]
> Sometimes it goes in one direction (with progressive acceleration). It cannot be canceled (using the analog stick in the opposite direction only blocks the cursor until we release the stick).
You must wait until the cursor has reached one end of the screen to regain control.

> This seems to be a good guess since this bug only occurs during a long press on the analog stick.

IIRC I used to get similar behaviour with the 'nipple mouse' joystick on a Windows7 Lenovo Thinkpad laptop I had. IIRC it was something to do with the zero-point auto-calibration getting confused when the joystick was held in the same direction for "too long" (which made the mouse cursor appear to move by itself), and (similarly) the only workaround was to not touch the joystick at all for a couple of seconds, and then it "sorted itself out" and started working again properly.
