### ISSUE TITLE
Add rtandroid

### ISSUE THREAD

**Issue by procount** [procount/pinn#20]
Include rtandroid raspberrypi/noobs#382

**Comment by procount** [comment]
RTAndroid 7.1.1 has been added.
RPF and Waveshare touchscreen support needs to be added manually for now. see #95

**Comment by win8linux** [comment]
I'm encountering an issue with installing RTAndroid. The install fails with this error:
`cpio: invalid option -- o`

This occurs after the following part of the partition setup script:
`cpio -o -H newc`

**Comment by win8linux** [comment]
Closing this issue since RTAndroid is present as of time of posting...

**Comment by procount** [comment]
@win8linux - keeping this open as a reminder to integrate the touchscreen scripts one day...

**Comment by win8linux** [comment]
Maybe that should be a separate issue, @procount ?

**Comment by procount** [comment]
Closed as RTAndroid has been added
