### ISSUE TITLE
No Advanced WiFi Connection

### ISSUE THREAD

**Issue by JeffDann** [procount/pinn#213]
Unable to enter an SSID and password manually for a network not broadcasting it's SSID. Would be nice to select from the list or enter the SSID and password into textboxes and connect.

**Comment by procount** [comment]
You can copy a working wpa_supplicant.conf file to PINN's recovery partition for SSIDs that are not broadcast and PINN will use that.  See  #40 and  https://github.com/procount/pinn/blob/master/README_PINN.md#preconfiguring-a-wifi-network
