### ISSUE TITLE
Unsupported WiFi Password Characters

### ISSUE THREAD

**Issue by JeffDann** [procount/pinn#214]
I was attempting to connect to a WiFi network that had an '@' in the password but it would not accept it. I finally had to temporarily change the password in order to connect to WiFi.

**Comment by procount** [comment]
This could be a keyboard layout/language problem. Did you try checking the "show password" box first to check that the characters you think you are entering are actually being used? For example, on some keyboards, the quote (") and the @ symbol are often interchanged.

Alternatively, you can copy a working wpa_supplicant.conf file to PINN's recovery partition and PINN will use that. See https://github.com/procount/pinn/blob/master/README_PINN.md#preconfiguring-a-wifi-network

**Comment by procount** [comment]
Presuming resolved.
