### ISSUE TITLE
Add Combian 64 to PINN

### ISSUE THREAD

**Issue by mobluse** [procount/pinn#215]
I wonder if you could add Combian 64 to PINN.

Commodore VIC-20, C64, and C128 can be emulated by Combian 64:
https://www.facebook.com/groups/combian64/
I run it on the cheap Raspberry Pi Zero.

Blog with download link:
https://cmaiolino.wordpress.com/

If you search the blog for PINN you see that the developer of Combian 64 gave his permission to include it with PINN on the condition that you link to his blog, which could be done using the info-button in PINN. There is documentation inside Combian 64 that recommends a link to use.

Current download link to a RAR5-file with the "Combian64 V 2.8.1" img-file:
https://drive.google.com/open?id=1sNhrr2u6n48vb5xuOe8P9pTayojQoOc_

I had to unpack the rar-file with unrar-5.3.7-arm on a Raspberry Pi 3B.

Change log for Combian 64:
https://cmaiolino.wordpress.com/combian64-changelog/

I'm just a user of Combian 64 that would like that it becomes easier to try out for beginners.

**Comment by procount** [comment]
I see that blog comment was made by Matt who contributes many of the gaming OSes to PINN, so he might have it in progress anyway. But if not I will take a look.

**Comment by procount** [comment]
Completed (thanks to Matt)

**Comment by mobluse** [comment]
Unfortunately I get a blank/black screen, but it doesn't go into sleep mode, when Combian 64 boots, and then it stays black. I have a screen with HDMI to DVI-D adapter. Amibian and other OS:s work. I can use PINN if I press Shift at boot or if I multiboot. Some other of the games OS:s also boot to black screen, but some work.

**Comment by jgbrwn** [comment]
Not seeing Combian64 in the "Games" List for PINN... was it removed?

**Comment by procount** [comment]
No, it's still there, but it's an old version, so if you have a Pi4 it won't show up for you.

**Comment by procount** [comment]
@matthuisman - Combian64 v3.5.3 is now available for Pi400 (and I therefore assume Pi4). Any chance you could update it please? You might want to keep the old v2.8.1 for the Pi Zero which seems to be excluded from v3.5.3.

**Comment by matthuisman** [comment]
i just tried but seems their .img is corrupt. I couldn't mound the root partition.
https://github.com/matthuisman/pinn-os/blob/combian_update/Combian/HOW-TO.sh#L31 is the line that fails

7zip also complains about unexpected end of part2.img - however it does still allow seeing the files inside and copying them out. However, thats windows so not a solution for preserving symlinks etc

So not sure if I can proceed

**Comment by procount** [comment]
Ok. Thanks for trying.
