### ISSUE TITLE
pinn 3.0.3 - can not backup usb drive not show maintence?

### ISSUE THREAD

**Issue by lpt2007** [procount/pinn#223]
Hi,

I try to backup to usb drive, I try 64Gb and 16Gb formated to fat32. I cen not select destination drive (nothing to select). Why?
![backup_not_working](https://user-images.githubusercontent.com/38924279/51397183-f6900000-1b40-11e9-9998-fbdd2a45f947.jpg)

**Comment by procount** [comment]
Did you create a folder on your USB drive called /os?

**Comment by lpt2007** [comment]
Thanks I add os folder on usb and now I see destination drive.

Now I have another error. What this error menas?
![error_when_try_to_backup](https://user-images.githubusercontent.com/38924279/51407599-9c049d00-1b5c-11e9-971a-5a088907fcda.jpg)

**Comment by procount** [comment]
Ah yes. You picked one of the few OSes I can't back up yet.
Xbian uses a btrfs file system which requires some very special code to back it up. I hope to have that sorted soon but it is a bit tricky.

**Comment by lpt2007** [comment]
Ok, Thanks.

+1 vote for xbian backup solution
