### ISSUE TITLE
RPI3B+: Add Recalbox [BETA]

### ISSUE THREAD

**Issue by CrAazZyMaN21** [procount/pinn#225]
There is Beta out which works with RPI 3B+. I don't know when they will get out of beta but its better than nothing for the RPI 3B+ Owners. 
Forum: https://forum.recalbox.com/topic/15010/testers-wanted-major-system-upgrade-pi3b-kodi-17-and-much-more
Download from Forum: https://mega.nz/#!rRwjFAiI!QgOv3lpiFNvPgm-nbpuWeod-oIUHipIAyrgLTePp53Q

**Comment by procount** [comment]
Ping @matthuisman 
?

**Comment by procount** [comment]
Temporary version of Recalbox 6 now available through PINN.
Will be replaced with the official version when the maintainers have completed it.
