### ISSUE TITLE
Cannot install LibreElec

### ISSUE THREAD

**Issue by jeskata** [procount/pinn#226]
Updated PINN to the latest but it seems LibreElec download URL no longer works.

**Comment by Cyberfly100** [comment]
Same here (maybe). Fresh install shows no LibreElec icon in the selection screen and gives error messages 
(e.g. "Error downloading meta file http://releases.libreelec.tv/noobs/LibreELEC_RPi2/partitions.json") before installation starts.

Edit: Am using freshly downloaded version of PINN on a RPi2 with 32GB FAT32 formatted SD Card. Have tried re-downloading and re-preparing SD Card again without success.

Edit2: works now, seems the links were just down somehow...

**Comment by procount** [comment]
The LibreELEC noobs image does not appear to have been changed or updated since 2018-04-13, so I think it was just a temporary LibreELEC server problem.
