### ISSUE TITLE
PgDown crashes PINN

### ISSUE THREAD

**Issue by dominic-03** [procount/pinn#228]
Yesterday when I was in the PINN menu of operating systems, I pressed PgDown on my keyboard by accident. It cut the display output to my TV and my Pi stopped responding. After trying it again, I can confirm it can be replicated. Pressing PgDown again after the display loses signal does not turn it back on.

Raspberry Pi 3b+
Whatever the latest version is as of downloading from SourceForge yesterday (I forgot the number)
I was in the main menu

This is a odd bug, so I just wanted to write it on here.

**Comment by procount** [comment]
Which model of RPi do you have?
What version of PINN are you using?
Were you in the "Main Menu" menu of PINN (with the tabbed dialog box of categories of OSes, rather than the Boot menu)?

**Comment by dominic-03** [comment]
> Which model of RPi do you have?
> What version of PINN are you using?
> Were you in the "Main Menu" menu of PINN (with the tabbed dialog box of categories of OSes, rather than the Boot menu)?

I edited my post with that information now included.

**Comment by procount** [comment]
I just tried it on mine and it didn't crash, so something funny is going on with yours.
Please have a look on my troubleshooting section to see if you can capture any logs of interest.
https://github.com/procount/pinn/wiki/Troubleshooting

But I see PageDown is doing 2 things: 1) moving the highlight to the bottom of the current list and 2) activating the Next Menu button, so maybe I will remove that functionality in the next version and rely on the 'M' key alone.

**Comment by lurch** [comment]
@dominic-03 What keyboard are you using? What language do you have PINN set to? Is your Pi connected to your TV via HDMI or composite?

**Comment by dominic-03** [comment]
> @dominic-03 What keyboard are you using? What language do you have PINN set to? Is your Pi connected to your TV via HDMI or composite?

I'm using HDMI TV
I have PINN set to United Kingdom English and I have a standard Dell US keyboard. Do I need to set the language to US English?

> I just tried it on mine and it didn't crash, so something funny is going on with yours.
> Please have a look on my troubleshooting section to see if you can capture any logs of interest.
> https://github.com/procount/pinn/wiki/Troubleshooting
> 
> But I see PageDown is doing 2 things: 1) moving the highlight to the bottom of the current list and 2) activating the Next Menu button, so maybe I will remove that functionality in the next version and rely on the 'M' key alone.

I'll try it again tonight, and get more details on it.

**Comment by lurch** [comment]
@dominic-03 That all sounds fine, I just wondered if maybe you were using some obscure keyboard which was sending a non-standard keycode which PINN wasn't expecting. (I think quite a few people use PINN for a media center and use a wireless keyboard, so I was just checking)

**Comment by dominic-03** [comment]
Also, if PINN stands for "PINN Is Not Noobs" then what does PINN stand for in the acronym? (You may be confused, and yeah, this does sound pretty confusing as I type this."

**Comment by lurch** [comment]
It's a recursive acronym - pretty common in the computer world :wink: 
https://en.wikipedia.org/wiki/Recursive_acronym :nerd_face:

**Comment by dominic-03** [comment]
> It's a recursive acronym - pretty common in the computer world 😉
> https://en.wikipedia.org/wiki/Recursive_acronym 🤓

Oh, ok. Cool. (You learn something every day!)
I added PINN to that article, just for the fun of it.

**Comment by procount** [comment]
Credits to Lurch for suggesting the name in the first place. :wink:

**Comment by procount** [comment]
v3.1.1: Using pagedown to cycle the menus has now been removed, as pagedown is also used to move down the list. So it is necessary to use the 'm' key to cycle the menus now.
