### ISSUE TITLE
PINN UPDATE window - button not translated

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#23]
@procount

I tested using PINN 2.1.3 that it found an update (2.1.4).
The windows has a title "PINN UPDATE" not translated. 
There are some button not translated: "Ignore" and "Show Details"
I didn't find theese strings in the language file.
When I select "Yes" in "PINN UPDATE" window to confirm appear the download window.
Could you please add a text like "Press ESC to cancel" (localizable) in this window?

**Comment by procount** [comment]
Thanks for keeping on top of this issue for me!
I will take a look.

**Comment by procount** [comment]
Text made translatable in PINN v2.2.
