### ISSUE TITLE
Retropie2 unable to install.

### ISSUE THREAD

**Issue by Linn97** [procount/pinn#234]
There is an error message which show error downloadng meta file.

**Comment by procount** [comment]
It's probably a temporary problem with the Sourceforge servers where the OS is hosted. I know they suffered from a few DDOS attacks over the weekend. Try again every few hours. If it is not resolved in 24 hours, let me know again.

**Comment by Linn97** [comment]
Thank you for replying, I will check later.

**Comment by procount** [comment]
No further posts, so I assumed it is resolved and closing. Please reopen if it is still an issue.
