### ISSUE TITLE
Proposal for improvements - POWER button to reboot/shutdown

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#24]
@procount 

I used LibreELec and I found that it's available an interesting feature that I hope could implement in PINN interface.
A "POWER" button that enable a menu where the user can reboot or shutdown the Rapsberry (Menu items: Reboot/Shutdown/Cancel).

**Comment by procount** [comment]
Why is this useful in PINN? It is used to start a system, not to shut it down, which is normally a function of the installed OSes (like LibreElec)
It already reboots the PI into a chosen OS.
PINN runs from a ramdisk, so there is no real need for a graceful shutdown. Pulling the power should not harm it.
