### ISSUE TITLE
Recalbox install on RPI 3B (not+)

### ISSUE THREAD

**Issue by ghost** [procount/pinn#240]
Can't install Recalbox, it always says "error downloading meta file".

I've checked installation paths and these files are missing.

http://pinn.mjh.nz/os_list.json?recalboxos-rpi3=50332&osmc_pi2=7168

https://archive.recalbox.com/v1/noobs/partition_setup.sh
https://archive.recalbox.com/v1/noobs/recalboxOS.png
https://archive.recalbox.com/v1/noobs/rpi3/boot.tar.xz
https://archive.recalbox.com/v1/noobs/rpi3/root.tar.xz
https://archive.recalbox.com/v1/noobs/marketing.tar
https://archive.recalbox.com/v1/noobs/rpi3/os.json

Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

**Comment by procount** [comment]
It looks like they've removed the NOOBS install version from their website.
Thanks for letting me know. I'll see if I can find out.
Meanwhile, have you tried Batocera, or one of the other game distros?

**Comment by ghost** [comment]
I tried to put recalbox image in os folder but as soon as it connects to internet it tries to get online version. If i remember well on noobs it priorized offline files.

I'll try batocera this afternoon.

Thanks for the quick answer =D

**Comment by procount** [comment]
PINN also prioritizes the offline version if the date is the same or newer.
Did you download the os files before they disappeared from the recalbox website?

**Comment by ghost** [comment]
I downloaded recalbox files last night.

How does PINN knows that online files are newer, if these are missing?

**Comment by procount** [comment]
It just checks the release date.

I guess if you tried to download them last night then they are incomplete, since they are missing on the website.

I have messaged recalbox to find out what has happened to them.

**Comment by ghost** [comment]
If offline version is priorized then PINN should use offline files for installation. But actually that is not happening.
I downloaded os zip from recalbox github, it's the most up to date, i installed it without pinn and it works like a charm.

**Comment by lurch** [comment]
> i installed it without pinn

The file needed for standalone image-installation is very different to the multiple files needed for a PINN-installation of the same OS.

**Comment by procount** [comment]
OK I remember now!
Recalbox  was removed from NOOBS because it would no longer work with v2.9 due to it using very old firmware, but I managed to keep it going in PINN due to its firmware downgrade facility. See https://github.com/raspberrypi/noobs/issues/520

Recalbox has just moved from github to gitlab and the location of the NOOBS files has changed, so the os_list needs updating. I will get onto this when it is released and then recalbox will be restored to PINN.

The good news is that this version will also includes new firmware so it should be back in NOOBS soon as well.

ping @XECDesign for info ->https://gitlab.com/recalbox/recalbox/tree/master/updatesv2/noobs
(These files still need updating from what I can tell, so not quite ready yet.)

**Comment by procount** [comment]
ping @digitalLumberjack - I'm jumping the gun a bit. Just let me know when the new NOOBS files are ready :wink:

**Comment by XECDesign** [comment]
As far as NOOBS goes, I don't think Recalbox will be added again.

**Comment by daviduco** [comment]
> > i installed it without pinn
> 
> The file needed for standalone image-installation is very different to the multiple files needed for a PINN-installation of the same OS.

Offline install is the same

**Comment by lurch** [comment]
:heart: at the amount of effort @procount puts in to making PINN compatible with various 3rd party OSes.

**Comment by procount** [comment]
Thanks to Matt, a temporary copy of the latest version 6 of recalbox is now available through PINN.
This will be replaced by the official version when it is available.

**Comment by procount** [comment]
solved.
