### ISSUE TITLE
PINN 2.3.0 - Italian language udates

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#26]
@procount

Hi.

This the italian language uopdate for PINN 2.3.0 (200/200 strings translated)

[PINN-2.3.0-translation-it.zip](https://github.com/procount/pinn/files/821754/PINN-2.3.0-translation-it.zip)

**Comment by procount** [comment]
Cool!, thanks.

**Comment by bovirus** [comment]
@procount 

Could you please update the Italian language into the repository? Thanks.

**Comment by procount** [comment]
Source repository updated.
You can test the zip file by downloading https://sourceforge.net/projects/pinn/files/archive/pinn-23a.zip/download

**Comment by bovirus** [comment]
@procount 

Thanks for new build.
I propose you to change filename from "pinn-23a.zip" to "pinn-230a.zip" (to highlight that pinn-23a.zip is version 2.3.0a)
What are the differences between pinn-lite (which version is) and pinn-23a.zip?
Thanks.

**Comment by procount** [comment]
pinn-lite.zip is still p2.3. I haven't updated it yet. But if you are happy with the translations, I will update it.

**Comment by bovirus** [comment]
Thanks. 
For me v. v. 2.3.0a it's OK.
