### ISSUE TITLE
How to run x86 emulation with the Rpi-QEMUx86 image

### ISSUE THREAD

**Issue by 2003emachinesDesktop** [procount/pinn#262]
I have successfully installed the Rpi-QEMUx86 image with PINN on a Pi 3. I have downloaded many different x86 programs and attempted to run them but non work? I figure I must be doing something wrong, but I can’t find any documentation here or on sourceforge. Can someone point me to some instructions or documentation.

Also it would be nice if there was a readme file included with the scrips so we can figure out how to run it successfully.

Thanks in advance

**Comment by procount** [comment]
It comes from here --> https://github.com/mikerr/RPi-QEMU-x86-wine/blob/master/README.md

**Comment by 2003emachinesDesktop** [comment]
Thank You.
