### ISSUE TITLE
Compatibility with pi-top

### ISSUE THREAD

**Issue by dominic-03** [procount/pinn#267]
I noticed that PINN has pi-top OS, and I might get a pi-top at some point. Can anyone confirm if you can:

- Use PINN interface
- Boot to Raspbian
- Boot to OSMC
- Boot to pi-top OS

If you know if any of these work on pi-top, please reply!

**Comment by procount** [comment]
A pitop is just a pi with extra peripherals: keyboard, screen etc. So it runs all the standard OSes.

The pitop os (Polaris) just has extra drivers for the hardware and extra software.

The drivers are available on GitHub to add to most OSes. There is a version of gentoo64 specially built for the pitop that is installable from PINN.
