### ISSUE TITLE
Hyperpixel 4.0 (pimhyp4.dtbo) not working since last update

### ISSUE THREAD

**Issue by Marineflieger** [procount/pinn#268]
The screen stays black. I noticed that the pimhyp4.dtbo within the updated PINN is 1Kb bigger than the one from the previous version. 
So, if I replace it with the older one, it works again.

[Maybe I'm missing something, but haven't read anything about it, in the Change History]

**Comment by procount** [comment]
You did the right thing.
For some reason the pimhyp4.dtbo has been overwritten. Apologies.
I will post a new update to fix it soon.

**Comment by Marineflieger** [comment]
There's no need for an apology. Thank your for your work!

**Comment by procount** [comment]
Fixed in v3.3
