### ISSUE TITLE
Localization - Proposals for typo fixes

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#273]
About the current source file I have some proposals about fixes

Line 246

"Would you like PINN to create one for you?
WARNING: This will erase all data on your SD card"

It's multi-paragraph and should end with"." Like:

"Would you like PINN to create one for you?
WARNING: This will erase all data on your SD card**_._**"

It's the same for 

- Line 774
"OS(es) Downloaded with errors.
See debug log for details"
"OS(es) Downloaded with errors.
See debug log for details**_._**"

- Line 781
"OS(es) Installed with errors.
See debug log for details"
"OS(es) Installed with errors.
See debug log for details**_._**"

- Line 1792
"Enables an SSH connection to the rescueshell in PINN. It cannot be used to control PINN, but having a shell is very useful to perform remote maintenance on any of the SD card partitions"
"Enables an SSH connection to the rescueshell in PINN. It cannot be used to control PINN, but having a shell is very useful to perform remote maintenance on any of the SD card partitions."

and

- Line 1740/1786/1852
Change non-breakable space with standard space.

- Line 1847
This line seem available twice
"To change the background colour for the screen and most windows, add background=r,g,b, where 0,0,0 is black and 255,255,255 is white. I suggest to use values above 127."

- Line 1738/1851
Change **_message utf8="true"_** to  **_message_**
(I believe that it' related to non beakable space).

**Comment by lurch** [comment]
I'm not familiar with QT Linguist (been many years since I last looked at this translation stuff!) but I wonder if
"OS(es) Downloaded with errors.
See debug log for details."
and
"OS(es) Installed with errors.
See debug log for details."

could be split into 3 separate lines:
"OS(es) Downloaded with errors."
"OS(es) Installed with errors."
"See debug log for details."
and then the translator would only need to translate the string "See debug log for details." once, rather than multiple times? :wink:

**Comment by bovirus** [comment]
@lurch 
There are separate string

** String1
"OS(es) Downloaded with errors.
See debug log for details"

** String2
"OS(es) Installed with errors.
See debug log for details"

Each string has a specific reference in the source.
For me both strings (String1/String2) should have "." at the end of string (because it's a multi-line/paragraph string and has a "." in the middle.

**Comment by lurch** [comment]
> There are separate string

Yes, I realise that. I was just thinking-out-loud whether it would be possible to split the two strings into 3 separate (smaller) strings, as that _might_ ease the translation burden. :man_shrugging:  :man_shrugging:

**Comment by bovirus** [comment]
@procount 

Please change the source code for in multi-paragraph to add a  "." at the end of a multi-paragraph string. Ex

Would you like PINN to create one for you?
WARNING: This will erase all data on your SD card
Would you like PINN to create one for you?
WARNING: This will erase all data on your SD card.

OS(es) Downloaded with errors.
See debug log for details
OS(es) Downloaded with errors.
See debug log for details.

OS(es) Installed with errors.
See debug log for details
OS(es) Installed with errors.
See debug log for details.

Enables an SSH connection to the rescueshell in PINN. It cannot be used to control PINN, but having a shell is very useful to perform remote maintenance on any of the SD card partitions
Enables an SSH connection to the rescueshell in PINN. It cannot be used to control PINN, but having a shell is very useful to perform remote maintenance on any of the SD card partitions.

Thanks.

**Comment by procount** [comment]
Thanks. I've sorted those in a separate commit but had problems with laptop so I'll push them up separately.

**Comment by procount** [comment]
Implemented
