### ISSUE TITLE
PINN 3.3 does not work on Raspberry Pi 4

### ISSUE THREAD

**Issue by Lonerider2010** [procount/pinn#277]
Tried to run PINN 3.3 on Raspberry Pi 4, but does not work.
Did the following steps:
- Downloaded PINN 3.3 from SourceForge
- Extracted the ZIP file
- Copied the content on FAT32 formatted SanDisk Ultra 32 GB SDHC card
- Placed in the Raspi
- Attached monitor via HDMI, and mouse and keyboard via USB
- Attached the power
- The red LED turned on
- The green LED blinked for a short time, then turned off
- Nothing else happened.

**Comment by WallyCZ** [comment]
I have exactly the same problem. Pi 4B 4GB. Noobs 3.1 works without any problem.

**Comment by Lonerider2010** [comment]
Also no problem with Noobs lite 3.1.

**Comment by procount** [comment]
Ok. That's odd cos it did work fine. I'll check it out

**Comment by procount** [comment]
Sorry. It seems my last deployment left out a critical file.
Please can you re-download pinn-lite.zip and try again.
Please let me know if this fixes it.

**Comment by WallyCZ** [comment]
Yep, now it is working fine.

**Comment by procount** [comment]
Thanks for confirming.
I added an announcement to my thread and will release a new version to allow self-update to fix this issue automatically soon. For now, a manual download or forced update is required.
