### ISSUE TITLE
Advanced button non-intuitive

### ISSUE THREAD

**Issue by procount** [procount/pinn#30]
from 321
when clicking the Advanced button, the existing buttons dissappear, from a user perspective especially the caution one's, they might not find it intuitive to click the Advanced button again to restore the original buttons, so maybe the text on the Advanced button could change to something like Back to make it more obvious.

**Comment by typxxi** [comment]
Had the same issue 6 month ago in the beginning ...
now I am a bit more in the details and trained but still strange to me.

But: I can live with that.

**Comment by procount** [comment]
Functionality has now changed to a MORE> button since there are now 3 toolbars.
