### ISSUE TITLE
Please update LEDE image

### ISSUE THREAD

**Issue by varun-dhar** [procount/pinn#301]
Hi, PINN's current LEDE image is outdated, please update, as manual firmware upgrade is unsuccessful for me.

Thanks.

**Comment by procount** [comment]
Thanks for notifying me.
I have a few to update which I hope to do in the near future 9nce I've sorted out current issues.

**Comment by procount** [comment]
Why did you close this? Do you want me to forget about it?

**Comment by procount** [comment]
Updated to 18.06.04
