### ISSUE TITLE
Wiki: missing RPi4

### ISSUE THREAD

**Issue by ghost** [procount/pinn#304]
OSes supported by PINN and Model Names don't contain RPi 4

**Comment by procount** [comment]
Which OSes, for example?
Only Raspbian libreelec and raspex support rpi4 so far.

**Comment by lurch** [comment]
I think @RaspberryPiFan meant there's no Pi4 info on https://github.com/procount/pinn/wiki/OSes-supported-by-PINN or https://github.com/procount/pinn/wiki/Model-Names ?

**Comment by procount** [comment]
Oh yes.
I need to update those.

**Comment by lurch** [comment]
Why was this closed? :confused:

**Comment by procount** [comment]
Reopening to remind me to do it.

**Comment by procount** [comment]
First update done .Shame I can't shrink the text in the table.

**Comment by lurch** [comment]
Looks like you could put a space in "ubuntuMate1604LTS" which might shrink down the first column? And given that the Pi1 and the Pi0 use the same SoC, maybe they could be merged into a single column?

**Comment by procount** [comment]
It's a bit better, but I wonder if I just messed up my easy creation of this table from Matt's webpage 🤷‍♂

**Comment by lurch** [comment]
Sorry, I didn't realise it was autogenerated. Maybe move it from the wiki onto a gh-pages site? (which I guess would then allow you to have horizontally-scrollable tables) :man_shrugging:

**Comment by procount** [comment]
It's ok. I'd forgotten too, and have forgotten how I did it. Needs improvement (future task)
