### ISSUE TITLE
Can't shut down Pi

### ISSUE THREAD

**Issue by ZhuDaHai** [procount/pinn#315]
There is apparently no way to safely shutdown the PI from within PINN: no menu items or buttons to do so.

'shutdown' does not work within the console as well.

P.S. 'exit' from the console just locks up the system.

**Comment by procount** [comment]
No need. Just pull the plug, provided it has finished writing.

**Comment by procount** [comment]
Noobs & pinn run from RAM and endeavour to keep any disks fully synched and read-only whenever they can.

Shutdown is not implemented cos there is no need.
Use rebootp to reboot from the console.
