### ISSUE TITLE
Black Screen with PINN and Hyperpixel 4

### ISSUE THREAD

**Issue by rcrespir** [procount/pinn#320]
Hi, 

I have downloaded the last pinn-lite version,  extracted all on the SD Card and I have put it on my rpi 0 W. The pi is booting because I can see the leds flashing, but I have black screen on the display  (I have attached an hyperpixel 4 from pimoroni).  

I'm missing something?

Thanks, Rafa

**Comment by procount** [comment]
Did you add the hyperpixel support to PINN?

https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-with-pimoronis-hyperpixel-displays

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&p=1309584#p1309584

**Comment by rcrespir** [comment]
Ok, it worked , thanks
