### ISSUE TITLE
silentinstall over web

### ISSUE THREAD

**Issue by eroom1966** [procount/pinn#328]
Regarding https://github.com/procount/pinn/issues/196#

Can I ask for an example of how this is done ?
I have tried to reproduce, but it will not perform the silentinstall - I am clearly missing something
... help !!

Here is a dropbox link to my modified version of pinn-lite
https://www.dropbox.com/sh/acmskpcarlcr73r/AADA7Q0EJJb_Il9pj6q8Quq1a?dl=0

This links to my os_list.json here
http://pilotaware.lode.co.uk/downloads/OGN/net/os_list.json

and my recovery.cmdline is

runinstaller quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline alt_image_source=http://pilotaware.lode.co.uk/downloads/OGN/net/os_list.json silentinstall select="Raspbian,waitnetwork" no_default_source no_update nofirmware ssh lang=en

But it does not autoinstall, it goes interactive - clearly doing something wrong, but not sure what

Thx
Lee

**Comment by procount** [comment]
Could you post the output of /tmp/debug?

**Comment by eroom1966** [comment]
Aahh, I think I will need guidance on that
How do I go about capturing that 
Thx

**Comment by procount** [comment]
https://github.com/procount/pinn/wiki/Troubleshooting

I just tried your settings and it never finished waiting for the network. Maybe I broke something again. It's not a feature I often check.

**Comment by eroom1966** [comment]
If you need me to test anything, very happy to give it a go

**Comment by procount** [comment]
I think I've found it. 
It will need  a new release of PINN though.

**Comment by eroom1966** [comment]
Hey thats great news, you’re a star
Let me know when you have a release and I will give it a try

**Comment by eroom1966** [comment]
I just noticed you have a repo for the ciseco XRF product
What a really strange coincidence, an early version of the PilotAware product was using the ARF - a 500mw version of the XRF

Thx
Lee

**Comment by procount** [comment]
Yeah, I bought the Ciseco for the RPI and Arduino hoping to use them, so I downloaded all the stuff I could. When they disappeared, I read someone was looking for the documentation etc so I put it up.

BTW, I managed to silently install your PilotAware OS, but it won;t work on the Pi3B+ - Just 4 red flashes which means it can't find the firmware for the 3B+. 
You should probably change the name of the OS from Raspbian to PilotAware to avoid confusion with Raspbian.

**Comment by eroom1966** [comment]
> BTW, I managed to silently install your PilotAware OS, but it won;t work on the Pi3B+ - Just 4 red flashes which means it can't find the firmware for the 3B+.

Great news, can you let me have a pointer to the release with the fix
Thx
Lee

**Comment by procount** [comment]
Will do.
I need to package it up.

**Comment by procount** [comment]
https://sourceforge.net/projects/pinn/files/testing/pinn-331.zip/download
As this is beta software, please email me for the password to unzip it.

**Comment by eroom1966** [comment]
email request set to your sourceforge address

**Comment by eroom1966** [comment]
great job!
seems to do the trick
