### ISSUE TITLE
Add elementaryOS

### ISSUE THREAD

**Issue by bobbbay** [procount/pinn#342]
elementaryOS is a clean, beautiful OS. PINN would be nice with it. Not sure about compatibility, have to take a look, but an ISO is provided.

NOTE: Also not sure of legality, it is a pay-what-you-want, so downloading a free version for all PINN users is probably not what they would want...

All in all it's a nice OS though. Would love to see this in PINN.

Here's their [website](http://www.elementary.io), and here's their [Github account](https://github.com/elementary) if needed.

Thanks, Bobbbay

**Comment by procount** [comment]
It's for x86 computers. Not Arm compatible.
