### ISSUE TITLE
how to install Kali for pi4 from usb disk

### ISSUE THREAD

**Issue by wliu88ca** [procount/pinn#346]
I've donwloaded Kail from kali official site, but how can I get meta-data json file to install it?
https://images.offensive-security.com/arm-images/kali-linux-2019.4-rpi3-nexmon-64.img.xz

**Comment by procount** [comment]
You have to create them yourself, or copy (some of) those I created for earlier versions. 
You also have to convert the img file.
But have a look at https://forums.kali.org/showthread.php?44787-Partially-SOLVED-Installing-Kali-2019-2a-using-NOOBS-PINN&mode=hybrid before spending too much time on this....
