### ISSUE TITLE
New images for Raspberry pi 4?

### ISSUE THREAD

**Issue by rhunjadi** [procount/pinn#347]
Lineage OS 16 for RP4 

It's been released. Can you add it to the raspbarry pi 4 PINN image?

https://konstakang.com/devices/rpi4/LineageOS16.0/

Also if it could be possible to add weekly bulds of retropie?

https://files.retropie.org.uk/images/weekly/

Thank you very much!

**Comment by procount** [comment]
The last time I tried to add LineageOS16 I had some problems. I may try again when I have some spare time.

I have to convert each image to NOOBS format manually, which takes a while, so I'm not prepared to do that on a weekly basis, I'm afraid.

**Comment by rhunjadi** [comment]
Thank you for your quick replay. 

Hope u'll have succes with LineageOS16.

For the second one I was just having in mind the latest version for RP4. It's no problem...I'll just wait for the final relese of Retropie or try to convert one of the images manualy. It shoudn't be that hard. I understand your pain about weekly continuous (manual) integration process... :)

**Comment by Norde** [comment]
You can easily convert a classic image to a noobs/pinn one:

1) Get system img file
2) Note size and name of boot and root partition (in Mb)
> parted <system_img_file>.img
> print
> exit

3) Mount system img:
> sudo kpartx -av <system_img_file>.img

4) Tar boot and root partition:
> cd /media/$USER/<BOOT_partition_label>/
> bsdtar --numeric-owner --format gnutar -cpvf ~/<boot label>.tar .

&
(root partition need to be tared with root user)

> cd /media/$USER/<ROOT_partition_label>/
> sudo bsdtar --numeric-owner --format gnutar -cpvf ~/<root label>.tar .

5) Note the size of created files <root label>.tar and <boot label>.tar
> ls ~/ -l --block-size=1MB

6) Compress both .tar files:
> sudo xz -9 -e -v /tmp/<boot label>.tar ; sudo xz -9 -e -v ~/<root label>.tar

7) Eject and unmount system img file:
Eject partition using file explorer or umount /media/$USER/<partition_label>
Discard system img file:
> sudo kpartx -dv <system_img_file>.img

8) Now using existing noobs/pinns system image as exemple, put created boot and root.tar.xz and edit "partitions.json" file:
- For "label" input, write corresponding one to root and boot partition noted in 2)
- For "partition_size_nominal" size noted in 2) (You can round up)
- For "uncompressed_tarball_size", size of .tar file noted in 5) (You can also round up)

9) Edit "os.json" file to personnalise title, description and compatibilities


More informations:
https://github.com/raspberrypi/noobs#how-to-create-a-custom-os-version
https://github.com/raspberrypi/noobs/wiki/Adding-custom-OS-version-examples


Edit: updated instructions (previous ones were outdated)

(Edit by procount):
More instructions are available at:
https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-create-a-custom-os-version
https://github.com/procount/pinn/wiki/How-to-Create-a-Multi-Boot-SD-card-out-of-2-existing-OSes-using-PINN

**Comment by procount** [comment]
Finally, some success with LineageOS16. Still some work to do, but it's looking more promising now.

**Comment by rhunjadi** [comment]
First of all I would like to thank you for your instructions. Ill try them tonight. 
As for the Lineage...You see the light at the end of the tunnel. I really hope that this light is the sun...and not the train! :)

**Comment by Norde** [comment]
I updated instructions (previous ones were outdated).

**Comment by procount** [comment]
LineageOS 16.0 has now been added to PINN

**Comment by mjcc30** [comment]
Hello ! Good work ! 👍 
There are other images available for lineagos here : 
https://konstakang.com/devices/rpi4/
is it possible to add the android tv version ?
Thank you for your work

**Comment by procount** [comment]
I've been working on it. There have been some quite complex changes, but nearly there.

**Comment by matthuo333** [comment]
Can I add lineage18.1 (Android 11)? Because when running lineage17.1, when the wired network is not plugged in, the system always restarts. Not in 18.1. For this issue, the related lineage thread has been confirmed.
Or can you tell me how to customize and add a new system?
