### ISSUE TITLE
Sending CEC command with PINN

### ISSUE THREAD

**Issue by Norde** [procount/pinn#348]
While testing a CEC compatible TV I wondered if it could be possible for PINN to orders other devices  using cec-client (at pinn boot to power on devices or switch video/sound sources).

Would including cec-client at buildroot suffice?

If yes I could add a script to pinn_init.sh using config.txt for variables (and update the documentation accordingly).
A simple command like "echo 'cec-code' | cec-client" should suffice.

**Comment by procount** [comment]
Maybe. Not sure if it will conflict with PINN's use. Try it and see.

**Comment by Norde** [comment]
I need to familiarize myself with the builroot first.
I come back when I have done the tests :)

**Comment by procount** [comment]
BTW, I didn't include libcec/ cec_client in PINN for possible licensing reasons.

**Comment by Norde** [comment]
According to the official website, libcec  is dual licensed GPLv2/Commercial
http://libcec.pulse-eight.com/

**Comment by procount** [comment]
Yes, but see first post from Maxnet in https://github.com/raspberrypi/noobs/issues/128

**Comment by Norde** [comment]
Indeed.
Thank you for the details and sorry for this questions which had already been answered 😟
