### ISSUE TITLE
2nd screen doesn't work

### ISSUE THREAD

**Issue by ghost** [procount/pinn#353]
A second screen doesn't work with PINN, and if I'm only using one screen at HDMI1 it doesn't work, only HDMI0 works. RPi 4

**Comment by ghost** [comment]
Idk if this is fixed in 3.3.3

**Comment by procount** [comment]
No. You need to use hdmi-0. Same for NOOBS.
But there is already a request for dual display.
See https://github.com/raspberrypi/noobs/issues/572

**Comment by procount** [comment]
Fixed with PINN v3.5.2
