### ISSUE TITLE
CEC on RPi4

### ISSUE THREAD

**Issue by ghost** [procount/pinn#356]
https://github.com/procount/pinn/blob/9c9749e5f55d45f5c834c5ed285aced31cecedd9/recovery/main.cpp#L599

Seems like it doesn't work on RPi 4 (bcm2711), but I didn't test it since I don't own a CEC compatible device.

**Comment by lurch** [comment]
Does the note [here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md) apply?

> Note: As of the 4.9 kernel, all Pis report BCM2835, even those with BCM2836, BCM2837 and BCM2711 processors.

**Comment by ghost** [comment]
Haven't read that, sorry.
