### ISSUE TITLE
Add moOde Audio Player as new OS

### ISSUE THREAD

**Issue by phobos-dev** [procount/pinn#358]
Hi, I just wanted to ask if you could please consider adding moOde audio player as a new OS in the media section.

It's a dedicated audio station and it's features are compareable to Volumio. It's based on Raspbian and the only one I know which supports bluetooth (sender & receiver) out of the box.

With moOde also available as an installable OS one might easier evaluate the different audio stations. Also it would give me the possibility to switch between LibreELEC, Volumio and moOde.

Thank you very much for thinking about it and propably integrating.

Ressources:
https://moodeaudio.org/
https://github.com/moode-player
https://moodeaudio.org/#download
https://github.com/moode-player/moode/blob/master/www/setup.txt
https://moodeaudio.org/docs/SOURCES.html

**Comment by procount** [comment]
I will put it on my list

**Comment by phobos-dev** [comment]
Thank you very much!

**Comment by procount** [comment]
MoOde is now available in PINN.
