### ISSUE TITLE
Install PINN on a old laptop?

### ISSUE THREAD

**Issue by OxygenGS** [procount/pinn#361]
Hello,

Well i dont want to buy a new Raspberry PI, but instead use my old but still fast laptop.
Can I install PINN on it and from there use it the same way as on a PI?

Grts Roy

**Comment by lurch** [comment]
Nope, PINN is Raspberry-Pi-specific.
Even if PINN itself _could_ run on your laptop, it's only used to install Raspberry-Pi-OSes, so wouldn't be of much use :wink: 

What is it that you're wanting to achieve?

**Comment by OxygenGS** [comment]
Hmm.. that is to bad haha!
I want to use my old laptop to setup Pi hole, and I was wondering is PINN would also work on it if I would install Ubuntu or something.
