### ISSUE TITLE
Arch Linux Arm - Raspberry Pi 4 support

### ISSUE THREAD

**Issue by aTosser** [procount/pinn#368]
Can we add the arch-linux-arm for rpi4 builds?

https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-4

**Comment by lurch** [comment]
Related to the discussions in #58 ?

**Comment by procount** [comment]
Certainly it was the case back in 2018 when I last looked at their Arch version for the RPI3, but that was an aarch64 version. I've had a look at the current RPI3 and RPI4 versions and it seems both have gone back to 32 bit, so they don't use U-Boot anymore for RPi. I'll try and find some time to convert them.

**Comment by procount** [comment]
Updated all Arch

**Comment by 33Fraise33** [comment]
Hello, 

has this been added now? as I don't see arch support for the RPI4 in the OS list: 
https://github.com/procount/pinn/wiki/OSes-supported-by-PINN

**Comment by procount** [comment]
Yes. Sorry, I don't always remember to update that list. For a dynamic up to date list, go-to pinn.mjh.nz

**Comment by 33Fraise33** [comment]
> Yes. Sorry, I don't always remember to update that list. For a dynamic up to date list, go-to pinn.mjh.nz

Thanks for the reply, is it possible to update that page with a link to the site so people always have the latest version available?

**Comment by procount** [comment]
I will do. But if you already have PINN & are connected to the internet, you will always see the latest available versions ready to download. They automatically appear. Even Matt's page can be up to 24 hours out of date.
