### ISSUE TITLE
[Question] 2 times same OS ?

### ISSUE THREAD

**Issue by Cyberoliv** [procount/pinn#369]
Hi,

I would like to install Raspbian Lite (same base os) on 2 differents partitions.
The 2 partitions will have different roles and I don't want to mix ...

Unfortunately I can't do it.
Is it possible ?

**Comment by procount** [comment]
Yes.
Install 2 different projectspaces, then replace them with Raspbian Lite.

**Comment by Cyberoliv** [comment]
Oh yeah, I did not think about replacement after installation, I will try, thank you!

**Comment by Cyberoliv** [comment]
Feedback: Working perfectly 👍
