### ISSUE TITLE
OS Request: Please add Retropie 4.6 Beta for RPI 4

### ISSUE THREAD

**Issue by cochonez** [procount/pinn#371]
I love your work. It´s just genius. But I didn´t managed to install the image-pack from usb and my /os is already downsized to about 65mb. It would be great if you could add the Retropie 4.6 Beta for the RPI 4. Thanks a lot <3
https://github.com/RetroPie/RetroPie-Setup/releases/download/4.6/retropie-buster-4.6-rpi4.img.gz

**Comment by mrceleron** [comment]
Yes, that would be great!

Thanks a lot in advance :)

**Comment by procount** [comment]
In progress....

**Comment by procount** [comment]
4.6 Released. Please give it a whirl.
