### ISSUE TITLE
Bootselection by gpio

### ISSUE THREAD

**Issue by beatz0001** [procount/pinn#375]
Is it possible to switch between (2) installed os' by connecting a switch to gpio's of the pi?

Pos.1 > Boot OS1 (or Standard OS)
Pos.2 > Boot OS2

**Comment by procount** [comment]
I've not tried this myself.
I suppose you could write a small shell script to do this. It must be called `pinn_init.sh` and stored on the PINN recovery partition (i.e. /dev/mmcblk0p1)
You could get this to read the status of a GPIO pin and alter the setting of `default_partition_to_boot` in `/settings/noobs.conf` accordingly. For typical 2 partition OSes, you would change the value between 6 and 8 (see `/settings/installed_os.json` for the actual values used for your OSes).
See https://www.ics.com/blog/gpio-programming-using-sysfs-interface for details on how to use GPIO using sysfs.
Note that PINN uses the busybox provided shell (/bin/sh - based on the simpler ASH, not BASH).

**Comment by lurch** [comment]
Maybe https://github.com/raspberrypi/noobs/pull/389 helps? :man_shrugging:

**Comment by procount** [comment]
Good find! (Memory of an elephant again)
Is there actually an implementation in that PR (somewhere in the 5334 files that have changed)? Looks just like a request. Even if there is, I don't remember it being implemented. If not, it would require a rebuild of NOOBS/PINN, whereas the solution above can be done by a user without modifying PINN.

**Comment by lurch** [comment]
> Is there actually an implementation in that PR

I dunno - perhaps there _was_ an initial implementation that got lost in a "git rebase" that went wrong somewhere? :shrug: The initial request was in https://github.com/raspberrypi/noobs/issues/366

> whereas the solution above can be done by a user without modifying PINN.

:+1:

**Comment by beatz0001** [comment]
Thanks for your input.

I've built it and used the script from here: https://github.com/procount/pinn/issues/187

Afterwards I've installed two instances of picoreplayer. Everythings looks good. The output of pinn_init.sh confirms the selection of the different os's (also shown in the bootselection-window of 
pinn).

BUT: It ends up with the same configuration of picoreplayer ?? In the output of the shell (bootprocess) is always the recovery of picoreplayer configuration from mmcblk0p9 mentioned.

How is that possible?? I've also reinstalled both os' but the result is the same.

There are two identical installations of picoreplayer (renamed with alias) made with project spaces.

OS1 partition 6/7
OS2 partition 8/9

Any idea?

**Comment by procount** [comment]
Perhaps you could post your script here, along with with any config.txt and cmdline.txt files from picoreplayer to see if we can spot anything wrong?

**Comment by beatz0001** [comment]
### **RECOVERY**

**cmdline.txt > empty**

**pinn_init.sh >**

```
dir=$(pwd)

cd /sys/class/gpio

echo 18 > export
echo in > gpio18/direction
bootselection=$(cat gpio18/value)

mkdir /tmp/bootsel
mount -t auto /dev/mmcblk0p5 /tmp/bootsel

cd /tmp/bootsel


if [ "$bootselection" = "1" ]
then
   echo "Local LMS selected! Rock on!"
   rm noobs.conf.bak
   cp noobs.conf noobs.conf.bak
   rm noobs.conf
   cp noobs.conf.llms noobs.conf
   cat noobs.conf

else
   echo "Remote LMS selected! Don't stop the Rock!"
   rm noobs.conf.bak
   cp noobs.conf noobs.conf.bak
   rm noobs.conf
   cp noobs.conf.rlms noobs.conf
   cat noobs.conf

fi

cd $dir

sync

umount /tmp/bootsel
rmdir /tmp/bootsel

sleep 10
```

**recovery.cmdline >**

```
repo_list=http://raw.githubusercontent.com/procount/pinn-os/master/os/repo_list.json ssh bootmenutimeout=2 quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline loglevel=2 sdhci.debug_quirks2=4
```

### **SETTINGS**

**installed_os.json >**

```
[
 {
  "bootable" : true,
  "description" : "A Squeezebox Audio Device",
  "download_size" : 39818320,
  "folder" : "/settings/os/picoreplayer",
  "group" : "Media",
  "icon" : "/settings/os/picoreplayer/icon.png",
  "name" : "picoreplayer=picoreplayer-rlms",
  "partitions" : [
"/dev/mmcblk0p6",
"/dev/mmcblk0p7"
  ],
  "password" : "piCore",
  "release_date" : "2017-09-23",
  "supported_models" : [
"Pi Model",
"Pi 2",
"Pi Zero",
"Pi 3 Model B Rev"
  ],
  "supports_backup" : true,
  "url" : "https://sites.google.com/site/picoreplayer/home",
  "username" : "tc"
 },
 {
  "bootable" : true,
  "description" : "A Squeezebox Audio Device",
  "download_size" : 39818320,
  "folder" : "/settings/os/picoreplayer",
  "group" : "Media",
  "icon" : "/settings/os/picoreplayer/icon.png",
  "name" : "picoreplayer=picoreplayer-llms",
  "partitions" : [
"/dev/mmcblk0p8",
"/dev/mmcblk0p9"
  ],
  "password" : "piCore",
  "release_date" : "2017-09-23",
  "supported_models" : [
"Pi Model",
"Pi 2",
"Pi Zero",
"Pi 3 Model B Rev"
  ],
  "supports_backup" : true,
  "url" : "https://sites.google.com/site/picoreplayer/home",
  "username" : "tc"
 }
]
```

**noobs.conf.llms >**

```
[General]
# Boot Local LMS Server
default_partition_to_boot=8
display_mode=0
keyboard_layout=de
language=de
```

**noobs.conf.rlms >**

```
[General]
# Boot Remote LMS Server
default_partition_to_boot=6
display_mode=0
keyboard_layout=de
language=de`
```

### **PICORE1** 

**cmdline.txt >**
```
`dwc_otg.fiq_fsm_mask=0xF host=piCorePlayer dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p7 elevator=deadline rootwait quiet nortc loglevel=3 noembed smsc95xx.turbo_mode=N noswap cron consoleblank=0 waitusb=2
```

**config.txt >**

```
# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

[PI0]
initramfs pcp_8.01.gz followkernel
kernel kernel4950.img

[PI1]
initramfs pcp_8.01.gz followkernel
kernel kernel4950.img

[PI2]
initramfs pcp_8.01v7.gz followkernel
kernel kernel4950v7.img
total_mem=1024

[PI3]
initramfs pcp_8.01v7.gz followkernel
kernel kernel4950v7.img
total_mem=1024

[ALL]
cmdline cmdline.txt

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2


[ALL]
#----------------------------------------------------
dtparam=i2c=on,spi=on,i2s=on

#---pCP----------------------------------------------
# pCP does not use graphics chip by default, free up most memory
gpu_mem=16
initial_turbo=60
disable_pvt=1

# onboard audio overlay
dtparam=audio=on
audio_pwm_mode=2

#Disable Bluetooth on both rpi3 and rpi0W
dtoverlay=pi3-disable-bt

# uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=
#core_freq=
#sdram_freq=
#over_voltage=
#force_turbo=

# Force max current to USB
max_usb_current=1

# Remove audio hiss
# disable_audio_dither=1

# Screen rotation 0 => 0 degrees, 2 => 180 degrees
#lcd_rotate=2

#Custom Configuration Area, for config settings that are not managed by pCP.
#pCP will retain these settings during insitu-update
#---Begin-Custom-(Do not alter Begin or End Tags)-----
#---End-Custom----------------------------------------

# NOOBS Auto-generated Settings:

```

**os_config.json >**

```
{
 "bootable" : true,
 "description" : "A Squeezebox Audio Device",
 "flavour" : "picoreplayer",
 "group" : "Media",
 "imagefolder" : "/settings/os/picoreplayer",
 "keyboard" : "de",
 "language" : "de",
 "partitions" : [
"/dev/mmcblk0p6",
"/dev/mmcblk0p7"
 ],
 "release_date" : "2017-09-23",
 "videomode" : 0
}
```


### **PICORE2** 

**cmdline.txt >**

```
dwc_otg.fiq_fsm_mask=0xF host=piCorePlayer dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p9 elevator=deadline rootwait quiet nortc loglevel=3 noembed smsc95xx.turbo_mode=N noswap cron consoleblank=0 waitusb=2
```

**config.txt >**

```
# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

[PI0]
initramfs pcp_8.01.gz followkernel
kernel kernel4950.img

[PI1]
initramfs pcp_8.01.gz followkernel
kernel kernel4950.img

[PI2]
initramfs pcp_8.01v7.gz followkernel
kernel kernel4950v7.img
total_mem=1024

[PI3]
initramfs pcp_8.01v7.gz followkernel
kernel kernel4950v7.img
total_mem=1024

[ALL]
cmdline cmdline.txt

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2


[ALL]
#----------------------------------------------------
dtparam=i2c=on,spi=on,i2s=on

#---pCP----------------------------------------------
# pCP does not use graphics chip by default, free up most memory
gpu_mem=16
initial_turbo=60
disable_pvt=1

# onboard audio overlay
dtparam=audio=on
audio_pwm_mode=2

#Disable Bluetooth on both rpi3 and rpi0W
dtoverlay=pi3-disable-bt

# uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=
#core_freq=
#sdram_freq=
#over_voltage=
#force_turbo=

# Force max current to USB
max_usb_current=1

# Remove audio hiss
# disable_audio_dither=1

# Screen rotation 0 => 0 degrees, 2 => 180 degrees
#lcd_rotate=2

#Custom Configuration Area, for config settings that are not managed by pCP.
#pCP will retain these settings during insitu-update
#---Begin-Custom-(Do not alter Begin or End Tags)-----
#---End-Custom----------------------------------------

# NOOBS Auto-generated Settings:

```

**os_config.json >**

```
{
 "bootable" : true,
 "description" : "A Squeezebox Audio Device",
 "flavour" : "picoreplayer",
 "group" : "Media",
 "imagefolder" : "/settings/os/picoreplayer",
 "keyboard" : "de",
 "language" : "de",
 "partitions" : [
"/dev/mmcblk0p8",
"/dev/mmcblk0p9"
 ],
 "release_date" : "2017-09-23",
 "videomode" : 0
}
```

**Comment by beatz0001** [comment]
![Screenshot from 2020-05-16 11-29-33](https://user-images.githubusercontent.com/16361565/82119904-7902f100-9782-11ea-8de7-4d69691a65f6.png)

**Comment by beatz0001** [comment]
How can i mask # in comments? Every codeline with # at the beginning will be shown very large...

**Comment by procount** [comment]
Add 3 back ticks around text. I've done it for you around the whole text but you might want to edit to just put them around individual files.

EDIT: I see now you already put single ticks, so I've re-edited your post to convert them to 3 ticks.

**Comment by beatz0001** [comment]
Here are some pictures from the boot process...

**Comment by beatz0001** [comment]
OS1

![20200516_200414](https://user-images.githubusercontent.com/16361565/82127215-22151000-97b2-11ea-8536-af8d8309a9c6.jpg)

**Comment by beatz0001** [comment]
**### OS1**

![20200516_200414 - Kopie](https://user-images.githubusercontent.com/16361565/82127280-9e0f5800-97b2-11ea-944e-a4e42a098309.jpg)

![20200516_200423 - Kopie](https://user-images.githubusercontent.com/16361565/82127290-aff0fb00-97b2-11ea-910d-01fbde1958ce.jpg)

![20200516_200445 - Kopie](https://user-images.githubusercontent.com/16361565/82127302-c8611580-97b2-11ea-9d67-6ea98d2b3c13.jpg)

**Comment by beatz0001** [comment]
### **OS2**

![20200516_200519 - Kopie](https://user-images.githubusercontent.com/16361565/82127343-09f1c080-97b3-11ea-8418-7b44e51032d8.jpg)

![20200516_200537 - Kopie](https://user-images.githubusercontent.com/16361565/82127352-19710980-97b3-11ea-96c6-b64ad12009c8.jpg)

![20200516_200558 - Kopie](https://user-images.githubusercontent.com/16361565/82127357-268df880-97b3-11ea-88be-de4bafcd0e13.jpg)

**Comment by beatz0001** [comment]
Everthings seems to be like it should... (to me at least)

But in the last picture(s) there's in both cases the identical line:

> Restoring backup files /mnt/mmblk0p9/tce/mydata.tgz /

How is this possible? And how can I change this behaviour?

**Comment by beatz0001** [comment]
I edited the config files a llittle bit more. 
Now you can see it like I wanted it to be shown.

Thanks für the tip.

**Comment by procount** [comment]
Must be a Picore thing.
I note there's a line that is scanning for partitions to build /etc/fstab, so check out those files. 
Maybe Picore is not expecting 2 instances on 2 separate partitions :man_shrugging: 
Maybe it just uses the latest backup it finds.

**Comment by beatz0001** [comment]
What i don't understand: How is Picore1 able to know about any configuration on partition 9?

Do you think there's a workaround for this?

P.S. I'm NOT a linux hero!

**Comment by procount** [comment]
Post the contents of /etc/fstab from os1 & os2.
(Nothing to stop it loading the partitions of another OS, especially if it is scanning all partitions)

**Comment by lurch** [comment]
I agree with @procount - looks like everything is set up correctly from the "PINN side" but something in the "PiCore side" is picking up the wrong partition. Maybe you need to get in touch with the PiCore team to ask them to make it more compatible with PINN? :man_shrugging:

**Comment by vitouXY** [comment]
> 
> > Restoring backup files /mnt/mmblk0p9/tce/mydata.tgz /
> 
It seems that piCore when booting and looking for the correct partition uses the last result ...

Look at the scripts: `tc-config`, `tce-setup`, `tc-functions` and `tce-setdrive` in this repository: [[tinycorelinux/Core-scripts]](https://github.com/tinycorelinux/Core-scripts).
Or search for: `/etc/sysconfig/tcedir`.

Suerte :v:

**Comment by jharris1993** [comment]
There is an active solution to this located on PINN's sticky, authored by me - (99% of the credit should go to procount for his patient help!)
[https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&p=1843314#p1843314](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&p=1843314#p1843314)

With the attached script and associated config.txt file, (which you put in PINN's root directory, "RECOVERY"), you can use GPIO pins to select operating systems to boot.

Note that (at the present time) ***this only works if you are using a SD card***.  There are still issues with getting scripts to run when on USB media.

This script assumes you are using one of the last six physical GPIO pins, (35 to 40), to select one of five O/S's.  You can reduce that number or use any other GPIO pin you want so long as it's not being used for anything else.  (See the very important ***WARNING*** within that posting.)

I hope this helps.
