### ISSUE TITLE
keyboardtriggerenable vs keyboardtriggerdisable

### ISSUE THREAD

**Issue by schauveau** [procount/pinn#379]
In the configuration window for recovery.cmdline, the checkbox **keyboardtriggerenable** does not disable the SHIFT key as expected. 

The problem is of course that the name is incorrect. The expected behavior is obtained by changing it to **keyboardtriggerdisable** in accordance to the documentation.

**Comment by procount** [comment]
Well spotted! I will fix it in the next version

**Comment by procount** [comment]
Fixed in 3.3.4.2
