### ISSUE TITLE
USB MSD boot for Raspberry Pi 4

### ISSUE THREAD

**Issue by raspberrypisig** [procount/pinn#383]
From your comment here, https://github.com/raspberrypi/noobs/issues/588#issuecomment-635915722 , I am interested in your progress on this or should I wait for NOOBS to update. Just interested in getting PINN itself to boot from USB/SSD, will use autoboot.txt to boot the other OSes with updated start.elf/fixup.dat files.

**Comment by procount** [comment]
I can post a beta version if you'd like to try it out? Only the basic mods at the moment, but as you will be upgrading OSes yourself it should be sufficient. 
Why do you use autoboot.txt?

**Comment by procount** [comment]
Latest PINN v 3.3.4.2 will now allow PINN to boot from USB, but installed OSes may have to be modified by hand to support this boot mode.
