### ISSUE TITLE
Expirimental 64-bit Raspbian option

### ISSUE THREAD

**Issue by dominic-03** [procount/pinn#384]
Hello,
I've been trying for 2 days now to install the 64-bit Raspbian (I'm NOT going to call it Raspberry Pi OS) alongside the 32-bit version. I can't get the methods described [on the wiki](https://github.com/procount/pinn/wiki/How-to-Create-a-Multi-Boot-SD-card-out-of-2-existing-OSes-using-PINN) to work. Can the 64-bit expirimental version be added to the installation menu? It could probably be added under the 'testing' category.

Thanks.
--dominic03

**Comment by procount** [comment]
i'll take a look for you.
PINN  already supports a debian64 test version, or there's sakaki's nspawn64 version which should be very similar.

**Comment by procount** [comment]
Raspio64 has now been added to the testing category
