### ISSUE TITLE
Can't install raspios64 on PINN 3.3.4.2

### ISSUE THREAD

**Issue by breadteam** [procount/pinn#389]
I'm on PINN v3.3.4.2 - Built: Jun 17 2020

When I try to install raspios64 under the Testing tab, I get an error. A window comes up titled "Download error" it says:

Error downloading meta file
http://downloads.sourceforge.net/project/pinn/os/raspios64/raspio64.png
[Close]

Maybe this link should be https:// ??

Is there a way for me to change that myself? Where do I do that?

**Comment by procount** [comment]
Should be fixed now.

**Comment by breadteam** [comment]
Thank you!
