### ISSUE TITLE
Add the 'fatlabel' command to the command shell

### ISSUE THREAD

**Issue by busywait** [procount/pinn#399]
The command shell has the e2label command, but not the fatlabel command (previous called dosfslabel).

This would have been useful (but not essential or even sufficient) in fixing up a change to the Manjaro cmdline.txt which currently expects certain partition names.

**Comment by procount** [comment]
You could use the mlabel command instead, which is included.

**Comment by busywait** [comment]
Ah, sorry, my google skills failed me looking for alternatives. Should I close this issue?

**Comment by procount** [comment]
No worries. In linux there are normally 3 ways to do anything. But PINN is pretty minimal and typically only provides 1 way to do it, usually via busybox.
