### ISSUE TITLE
Error installing Arch

### ISSUE THREAD

**Issue by rmast** [procount/pinn#4]
When installing OpenElec, LibreElec, OSMC and Archlinux and an extra partition on a 16gig SD card for a RPi1 only two systems get installed and this message appears:
![img_20160806_131629 1](https://cloud.githubusercontent.com/assets/3341558/17456562/0fbbe8d6-5bdc-11e6-9486-016682a57840.jpg)

**Comment by procount** [comment]
Sorry, I've been away. That doesn't look quite right.... I'll look into it.

**Comment by procount** [comment]
The partition_setup.sh scripts had got their line endings mangled in Arch. I've updated them and done a test download of Arch for the RPi1 and it works ok now. No need to update PINN, just re-install the OSes you want.
