### ISSUE TITLE
Boot delay keeps messing up

### ISSUE THREAD

**Issue by pandalatte** [procount/pinn#407]
Hi everybody!

I have PINN installed on Pi3 B, with Raspbian and LibreELEC.
The boot menu (OS selection) delay is set for 10 seconds.

But without any reason it has began booting without any delay.
A wallpaper splash and then immediately it starts booting the default OS.
It happened once a few weeks ago, I just rolled back from my backup.
But today it happened again.

Where can I find the file that holds the delay value? 
Will it work if I fix it and set the Read-Only flag?

Thanks!

**Comment by procount** [comment]
Did you tick one of the Sticky default boxes alongside one of your installed OSes? Press SHIFT when PINN boots, to get to the recovery screen, press ESC to get to the boot menu, and untick any selected OS.

**Comment by procount** [comment]
Is this issue now fixed?
