### ISSUE TITLE
recovery.cmdline.new

### ISSUE THREAD

**Issue by noafterglow** [procount/pinn#415]
What is the purpose of recovery.cmdline.new?

**Comment by procount** [comment]
I can't remember. I think it is (or was) something to do with a particular self-update. It may not be needed anymore, but I,ll check.

**Comment by procount** [comment]
See https://github.com/procount/pinn/blob/master/changes.md#v252

**Comment by noafterglow** [comment]
Note I used a WIRED connection.
_______________
Ihor Lys, PhD
Founder, CTO
617-470-2740
