### ISSUE TITLE
Is Windows IoT still supported?

### ISSUE THREAD

**Issue by theycallmevirgo** [procount/pinn#428]
It's not in my install menu or the OS list json

How may I go about installing it?

Thanks so much 

Joe

**Comment by procount** [comment]
AFAIK, Microsoft haven't updated the NOOBS version of Windows IoT for some time.
The last version issued is only available on the PI2 and Pi3, so if you have a different model like the PI4, it will not be shown as available.
I don't know what the current state of Win IoT is like, but if they have subsequently supported the PI4, you will have to install it without NOOBS or PINN.

**Comment by theycallmevirgo** [comment]
Ah, I see. I am in fact on Pi 4 (I need USB3) so I will try BerryBoot.  

Thanks so much for the info

Joe

**Comment by procount** [comment]
Good luck, but I think you might have the same issue with Win IoT on Berryboot too.

**Comment by theycallmevirgo** [comment]
They support local install from ISO, which I prefer anyhow.

**Comment by theycallmevirgo** [comment]
Do you get alerts from messages here? How?

**Comment by lurch** [comment]
> you might have the same issue with Win IoT on Berryboot too.

Indeed: https://github.com/maxnet/berryboot/issues/269

Also, after a bit of searching I found https://www.iottechtrends.com/install-windows10-iot-core-raspberry-pi/ which claims that Win 10 IoT _can_ be installed on the Pi4, but the commenters on that article said that they couldn't get it working.
https://www.techrepublic.com/article/windows-10-iot-core-on-the-raspberry-pi-4-will-microsoft-support-the-35-computer/ also says that Win 10 IoT doesn't run on the Pi4.

> Do you get alerts from messages here? How?

https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/about-notifications
