### ISSUE TITLE
3G modem?

### ISSUE THREAD

**Issue by Henrietta1989** [procount/pinn#43]
I have Raspberry 3 which don't have any OS installed. I can't figure out how to use PINN with 3G modem so i can download OS images.

**Comment by procount** [comment]
There are no drivers in PINN for 3G modems. I only added some wifi drivers and ethernet drivers. Do you know which modem you have, what chipset it uses and which driver it uses?

EDIT: To be honest, 3G modems don't look so easy to support as they need additional configuration, so I don't think I will be including them.

You could just use a PC to download the OSes you need and put them on your SD card with PINN in the /os folder, or put them on a USB stick in a /os folder and plug it in before you boot PINN.

**Comment by Henrietta1989** [comment]
sudo lsusb
05c6:1000 Qualcomm, Inc. Mass Storage Device

**Comment by procount** [comment]
For future reference:
http://raspberrypi.stackexchange.com/questions/4314/can-i-use-usb-dongle-to-connect-raspberry-pi-to-internet

https://www.thefanclub.co.za/how-to/how-setup-usb-3g-modem-raspberry-pi-using-usbmodeswitch-and-wvdial
