### ISSUE TITLE
GPT

### ISSUE THREAD

**Issue by eu41** [procount/pinn#432]
I used a GPT partition scheme on my SSD and copied PINN on the first FAT32 partition. PINN booted successfully from the USB connected SSD, but it recreated on the disk its own MSDOS partitioning scheme for installing the OS.

Now that Raspberry Pi 4 is capable of booting from a USB connected SSD, would it be too difficult to switch to GPT instead of MSDOS partitionning? This would allow creating many partitions on a SSD for a multitude of OSes, including BSD varieties. Those OSes could be easily booted through GRUB, as openSUSE does.

**Comment by lurch** [comment]
Duplicate of #413 ?

**Comment by eu41** [comment]
Yes, it looks similar to #413.
I see from that that thread that it is actually more difficult than I thought to convert to GPT.
I will try another way, without using PINN.
