### ISSUE TITLE
[OS Request] Add Ubuntu Desktop 20.10

### ISSUE THREAD

**Issue by lucid-dreams** [procount/pinn#437]
Hi, I'd like to request adding the new Ubuntu Desktop 20.10 64-bit image for the Raspberry Pi 4:

Download: https://ubuntu.com/download/raspberry-pi

Direct link:  https://ubuntu.com/download/raspberry-pi/thank-you?version=20.10&architecture=desktop-arm64+raspi

**Comment by procount** [comment]
If you install the 20.10 64 bit version through PINN, you will find it already is the desktop version.
Sorry the description is not quite correct, I will update it soon.
