### ISSUE TITLE
xbian? (pretty-please!)

### ISSUE THREAD

**Issue by boderson** [procount/pinn#45]
any chance for adding this one to pinn? imho *might be* the most advanced kodi build for pi, would be good to have it.

rgds,b.

**Comment by procount** [comment]
I'll look into it. Might have to wait til after 2.4 update.

**Comment by procount** [comment]
Looks like there may be plans to include it soon anyway....
https://sourceforge.net/projects/xbian/files/noobs/

**Comment by procount** [comment]
Xbian is now included.
