### ISSUE TITLE
Remote selection of the loaded OS

### ISSUE THREAD

**Issue by Goldenweiser** [procount/pinn#450]
Hello, Procount!
I successfully installed PINN and tested it.  Please tell, is it possible to remotely control the selection of OS’es to be loaded?  maybe vnc or ssh?  we are working to change the sticky default to noobs.  Maybe you can offer an easier way to boot another operating system each time?
Thank you so much !

**Comment by lurch** [comment]
https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-pinn-headlessly-vnc
