### ISSUE TITLE
I can't run Lakka or Debian64 installed with PINN

### ISSUE THREAD

**Issue by cpcbegin** [procount/pinn#457]
I install some systems in my new raspberry Pi 400 using PINN but when I select to run Lakka or Debian 64 show the enclosed error. 
![IMG_20201229_101018](https://user-images.githubusercontent.com/10259216/103344548-2ff07a80-4a8f-11eb-967c-57276859f37d.jpg)

**Comment by procount** [comment]
Are you trying to boot these from USB? Even if not, both of these were created prior to the Pi400 coming out so need new firmware to boot on a Pi400 (as the error message indicates). Even then, it may not be sufficient.
Try updating their start.elf and fixup.dat files from the latest Raspbian image and they _may_ then work.

Note that these are marked as suitable for the Pi4, but that this also includes the Pi400, which is not always appropriate. If updating the firmware does not work, you will have to wait until the maintainers update their image to include the additional drivers for the Pi400.

**Comment by cpcbegin** [comment]
No, I try to boot from microSD.
