### ISSUE TITLE
Cannot Sign into insider while installing windows loT (insider)

### ISSUE THREAD

**Issue by Custom9409** [procount/pinn#459]
When I select the windows loT option and click install. It installs a few things and then prompts me with a sign in to install windows loT insider message. I try to click the button but it wont take me to the sign in page.

**Comment by procount** [comment]
I thought Microsoft abandoned Windows IoT on the RPi a long time ago, especially the NOOBS version.
I suspect you will get the same problem if you try to install it with NOOBS.
If you really want to install it, you might be best to install it directly, but I've never done that.
Sorry, but I think that OS is dead and I won't be doing anything to fix the installation.

**Comment by lurch** [comment]
@Custom9409 If you need any help with Windows IoT, I suspect you'll need to ask Microsoft...
