### ISSUE TITLE
Lineageos 17.1 (Android TV) Link is offline on Sourceforge

### ISSUE THREAD

**Issue by childx** [procount/pinn#460]
If i try to install Android TV over the Tab Media then re starts and try 22MB and then re write that the File on Sourceforge is not found and that he cannot install it.

**Comment by procount** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?p=1793137#p1793137

**Comment by procount** [comment]
I found and fixed an issue, so this should be ok now.
