### ISSUE TITLE
OS chooser menu not working

### ISSUE THREAD

**Issue by Custom9409** [procount/pinn#463]
I install Manjaro KDE and Raspbian. When it finished (without any errors) I rebooted. It  flashes the menu for half a second and disappears. 15 seconds latter it boots into Raspbian.

**Comment by procount** [comment]
My guess is that you have ticked the check box next to Raspbian on the Boot menu.
Boot PINN again, press the shift key for the recovery menu, Esc to go to the boot menu, and remove any ticked checkboxes.
