### ISSUE TITLE
[OS request] FydeOS

### ISSUE THREAD

**Issue by Heclalava** [procount/pinn#469]
I saw a great review of FydeOS on YouTube and I'm busy testing it on a SD. As much as I like Lineage OS it's not without its bugs. As I love to multiboot into my Pi, I'd love to be able to have FydeOS as one of the available operating systems alongside RetroPie etc. I much prefer FydeOS as an Android media system over Lineage OS. Could you please add FydeOS to the list of available operating systems?

EDIT: Could you use the FydeOS from https://releases.fydeos.io/11.4/rpi4-fydeos as the one from GitHub doesn't allow for installation of Google play store. Whereas this specific version I linked to does.

**Comment by brunoga** [comment]
FWIIW, I think this would be great.

**Comment by procount** [comment]
Not possible to add. Please see #703
