### ISSUE TITLE
Use of terms NOBS in PINN translation

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#48]
@procount

Please check that in the strings of translation there some mentions to NOOBS.
I believe that any NOOBS reference should be change as PINN.
Please check if necessary please change in master and in the translations.

**Comment by procount** [comment]
Thanks for spotting this. I have now replaced all instances of NOOBS with PINN (I hope)
I noticed that I had not updated the TS files properly, so I have pushed a new version.
Please can you check your last PR translations, I think they may need updating.
Thanks.

**Comment by bovirus** [comment]
@procount

I'm afraid but in the new master language I lose many strings that I already tramslated (also if theese strings didn't contaiN PINN term). What's the matter?

Now I hsve to start again to do the same translation.

But is not the right way to redo the same job more than one time.

**Comment by procount** [comment]
Sorry for that. I'm still learning with these translations.....Thanks for the PR.

**Comment by bovirus** [comment]
@softastur
@aldatsa
@cescp
@qsypoq
@qsypoq
@fonic
@sople1
@Akkiesoft
@kadamski
@ResonantWave
@Mangero
@diorray
@s8321414

Please update your translation for PINN 2.4 as much as possible. Thanks.

**Comment by aldatsa** [comment]
Basque translation updated: #51

**Comment by bovirus** [comment]
@procount 

Could you please update basque & zh_tw translation (pull requests)? Thanks.

**Comment by procount** [comment]
Thanks for updated eu, it and zh translations which are now merged into v2.4b & released
