### ISSUE TITLE
(Allow to) Increase font size

### ISSUE THREAD

**Issue by redm123** [procount/pinn#484]
I run PINN on my TV screen (1080p), which is not that small, but I'm usually a few meters away. From that distance the texts in PINN are somewhat hard to read. It would be great if there was a knob somewhere to increase fontsize (and probably the entire window). It should be easily accessible. Maybe in that language bar at the bottom?
Or the fancy version: if a TV is detected make it bigger by default.
(I wonder what it would look like on a 4K TV?)

**Comment by procount** [comment]
Try pressing +/- keys.

**Comment by procount** [comment]
https://github.com/procount/pinn/blob/master/README_PINN.md#display-customisation
https://www.raspberrypi.org/forums/viewtopic.php?p=1607700#p1607700

**Comment by redm123** [comment]
Ah ok, thanks, I missed that from the docs. Still leaves the discoverability in the UI... ;)
