### ISSUE TITLE
PINN v3.5.5 Backup Bugs

### ISSUE THREAD

**Issue by annaclets** [procount/pinn#488]
I can confirm from tests I have made that PINN v3.5.5 indeed solves issue #447. There are, however, three minor backup bugs that I have observed:

1. Backup of lineage completes successfully, but fails during restore because in partitions.json the filesystem_type for "system" and "vendor" are specified as "ext4". Correcting these to "raw" solves it. (_This should solve issue_ #470)

2. Restored backup of ubuntu 2010 results in no permission/unauthorized access of mounted drives. Applying the fix suggested by @lurch solves it: **sudo setfacl -m user:pi:r-x /media/pi**

3. Backup of recalbox (PINN maintained) succeeds and includes the "share" partition. Restore, however, succeeds for partitions "recalbox" and "overlay", but not for "share" which remains unformatted.

**Comment by procount** [comment]
Thanks for your testing. I will look into those issues.
Which Lineage version did you test?

**Comment by annaclets** [comment]
lineage17-rpi4

**Comment by annaclets** [comment]
The solution to the abovementioned bug no. 3 would depend on PINN's ability to restore an **exfat** partition. Is this even possible?

**Comment by procount** [comment]
I believe this is now resolved.
