### ISSUE TITLE
"Error Parsing repolist.json" and "Please Wait while PINN initializes" loads for a long time.

### ISSUE THREAD

**Issue by Wizard451345** [procount/pinn#491]
I get these errors when I log in into PINN, though I can still ignore it and boot and use all the menu. Why do I get these messages? Also the OS's from the repolist are not showing, I can only see Raspberry Pi OS and LibreElec. Using PINN v3.5.5 if that helps idk, im a noob :)

**Comment by procount** [comment]
Have you connected PINN to the internet via ethernet or wifi?
"Please wait while PINN initializes" is not an error indication. It is just waiting for an internet connection.
"Error parsing repo_list.json" is an error and suggests it is not downloading form the internet correctly.

**Comment by Wizard451345** [comment]
> Have you connected PINN to the internet via ethernet or wifi?
> "Please wait while PINN initializes" is not an error indication. It is just waiting for an internet connection.
> "Error parsing repo_list.json" is an error and suggests it is not downloading form the internet correctly.

Yes, PINN is connected to the the internet via Wi-Fi and I am able to connect to it via SSH and VNC remotely via my phone. :/

**Comment by Wizard451345** [comment]
![Screenshot_20210312-105650.png](https://user-images.githubusercontent.com/44507272/110972540-b6dc9180-8321-11eb-8a70-69b8a6a2ee15.png)

**Comment by lurch** [comment]
Wow, world's biggest phone? :wink: :laughing: 

EDIT: More seriously, if you're able to connect to PINN from your phone over WiFi, it just shows that they're both successfully connected to the same local-network, it doesn't necessarily mean that PINN is able to connect to the internet if it e.g. has DNS or routing problems? :shrug:

**Comment by Wizard451345** [comment]
> Wow, world's biggest phone? :wink: :laughing: 
> 
> EDIT: More seriously, if you're able to connect to PINN from your phone over WiFi, it just shows that they're both successfully connected to the same local-network, it doesn't necessarily mean that PINN is able to connect to the internet if it e.g. has DNS or routing problems? :shrug: 

Browser Works fine:
![Screenshot_20210312-115051.png](https://user-images.githubusercontent.com/44507272/110978647-446faf80-8329-11eb-8a5a-661c45987f0b.png)

**Comment by lurch** [comment]
Hmmm, how very strange! :confused: 

Are you able to view `http://raw.githubusercontent.com/procount/pinn-os/master/os/repo_list.json` (which is specified [here](https://github.com/procount/pinn/blob/master/recovery/cmdline.txt) ) in PINN's web-browser?

**Comment by Wizard451345** [comment]
> Hmmm, how very strange! :confused: 
> 
> Are you able to view `http://raw.githubusercontent.com/procount/pinn-os/master/os/repo_list.json` (which is specified [here](https://github.com/procount/pinn/blob/master/recovery/cmdline.txt) ) in PINN's web-browser?

Yes, I'm in!
![Screenshot_20210312-134727.png](https://user-images.githubusercontent.com/44507272/110990872-8a347400-8339-11eb-9232-e346accc8734.png)

**Comment by lurch** [comment]
That looks fine. Is PINN itself still not working?

**Comment by Wizard451345** [comment]
No :/
Probably the best choice is to reload it with pinn again. Will take while as I have RPI OS on it and have to reinstall everything. Will do it from usb.

**Comment by Wizard451345** [comment]
... I did nothing for over a month and it decided to work now...?

wat
![Screenshot_20210312-154003.png](https://user-images.githubusercontent.com/44507272/111001553-9de7d680-8349-11eb-9e4f-8df30ce86c5d.png)
