### ISSUE TITLE
alt_image_source JSON example

### ISSUE THREAD

**Issue by myxxmikeyxx** [procount/pinn#500]
Could I see an example of how to make one of these?
I really want to make one so I can add OctoPrint as an option to install.

**Comment by procount** [comment]
http://raw.githubusercontent.com/procount/pinn-os/master/os/os_all.json
See also
https://github.com/procount/pinn/wiki/JSON-fields
and
https://github.com/procount/pinn/wiki/How-to-Create-a-Multi-Boot-SD-card-out-of-2-existing-OSes-using-PINN

**Comment by myxxmikeyxx** [comment]
Thank you very much! That's exactly what I needed

**Comment by myxxmikeyxx** [comment]
Do you happen to know any good resources on how to break an img file into boot and root tarballs?
I'm very new to all this.

**Comment by procount** [comment]
kpartx?

**Comment by myxxmikeyxx** [comment]
I shall give it a look, thank you

**Comment by myxxmikeyxx** [comment]
If possible, could someone take a look at this and tell me what I'm doing wrong?
https://github.com/myxxmikeyxx/OctoPrint-Repo
I added `alt_image_source=https://raw.githubusercontent.com/myxxmikeyxx/OctoPrint-Repo/master/os_list_v3.json
I changed it to raw but still don't see it. 
Also the download links for the Tar Balls I based it off the os_all.json and I uploaded it to source forge and made sure the download work.

**Comment by myxxmikeyxx** [comment]
When I do repo=https://raw.githubusercontent.com/myxxmikeyxx/OctoPrint-Repo/master/os_list_v3.json it shows the attached img.
![problem](https://user-images.githubusercontent.com/1766849/114119384-881df080-98b8-11eb-8275-db65e3fa6e56.PNG)

**Comment by myxxmikeyxx** [comment]
"GROUP" 
Downloaded  "GROUP" : "/tmp/overrides.json" 
Error Downloading   QUrl( "https://raw.githubusercontent.com/myxxmikeyxx/OctoPrint-Repo/master/os_list_v3.json
" )   reply:  203  httpstatus:  404 
libpng warning: Unknown iTXt compression type or method
libpng warning: Unknown iTXt compression type or method
Number of bootables =  0 
Number of bootables =  0

**Comment by myxxmikeyxx** [comment]
After looking at the link it had an enter /newline character.
I changed my recovery.cmdline to look like this:
`quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline repo_list=http://raw.githubusercontent.com/procount/pinn-os/master/os/repo_list.json loglevel=2 sdhci.debug_quirks2=4 alt_image_source=https://raw.githubusercontent.com/myxxmikeyxx/OctoPrint-Repo/master/os_list_v3.json ssh vncshare`
