### ISSUE TITLE
[OS Update Request] LineageOS 18.1 Android TV (Android 11)

### ISSUE THREAD

**Issue by g0dReVeN** [procount/pinn#502]
Can we please get version 18.1 of LineageOS Android TV by KonstaKang -> [https://konstakang.com/devices/rpi4/LineageOS18-ATV/](url)

**Comment by shivasiddharth** [comment]
@procount , Is there a guide to prepare LineageOS for PINN. I will try and get the files ready for the community.

**Comment by shivasiddharth** [comment]
@procount, Can you look into this please ?

**Comment by procount** [comment]
Now added.
