### ISSUE TITLE
[OS Update Request] Update Retropie 4.6 to 4.7.1

### ISSUE THREAD

**Issue by DerangedPineapple** [procount/pinn#505]
PINN has Retropie 4.6 available to be installed but that version cannot be used with usb ssd installation according retropie docs as they added usb boot support in version 4.7

Also version 4.6 is almost year old (ancient) so it would be nice to have newest version available and to be able to use usb boot.

My plan is/was to use libreELEC 10 (currently using nightly after manually updating it after installing 9.2.6) and newest retropie which is 4.7.1 booting them from usb ssd but currently I cannot really progress any further.

I assume I could follow your wiki guide to backup OS's and put them manually, I just need to figure out how to get bsdtar installed and how and where to wget  those proper *.json files for libreELEC 10 and Retropie 4.7.1

**Comment by DerangedPineapple** [comment]
I wonder if this issue could be worked on in the near future. I don't want any time table but just an hint if something might happen regarding getting retropie updated.

I have switched to Recalbox for now but would really like to hop back on retropie.

**Comment by procount** [comment]
I have converted it but not tested it.
If you would like to test it for me, I can make it available for you and if it is ok I can release it generally.

**Comment by DerangedPineapple** [comment]
I would definitely like to test it out if possible, I just installed my pi 4 from the scratch with LE and Recalbox so I can test with different usb ssd.

**Comment by procount** [comment]
Try adding `alt_image_source="http://raw.githubusercontent.com/procount/pinn-os/master/os/os_retropie.json"` to recovery.cmdline, or add it to the PINN config-edit options

**Comment by DerangedPineapple** [comment]
Ok I have tested it and in short (I do apologise for the unnecessary meme image but I just could not resist):
![XJyemeI](https://user-images.githubusercontent.com/3087661/115989041-f0611780-a5c4-11eb-9063-ab03118c4419.jpg)

I installed LibreELEC 9.2.6 and Retropie 4.7.1 to usb ssd successfully without any issues. Only the thumbnail is missing from OS listing under Games tab.

Next I try to update LE from 9.2.6 to 9.95.2 (LE 10 Beta2) even if the manual update is not supported not recommended. I just need to utilize both hdmi ports (one for picture and other one for sound) and get HDR and HBR audio support also.

Maybe this USB SSD installation fixes the RPi4 boot-back problem as well that happens with SD cards. I have to test NOOBS Companion add-on if that works

Anyways, thank you very much for this, highly appreciated!

**Comment by jjlankinen** [comment]
Small update for users that wish to use latest LE and Retropie with NOOBS companion add-on. As it is known the boot {partition} does not work in PI 4 when using SD cards but when using USB (SSD or sticks) it seems to work just fine.

Maybe @matthuisman could update hes guide regarding boot-back with NOOBS Companion add-on. I take it that the Pinn system resize website (https://pinn.mjh.nz/) will be update soonish regarding this Retropie update as I still have to figure out other things like resizing the partitions as when using 120gb SSD LE ends up taking half and it is a bit too much in my case.

Also LE update to latest 9.95.2 was successful via LibreELEC add-on using correct update channel.

I think this issue can be closed now.

**Comment by DerangedPineapple** [comment]
Small update for users that wish to use latest LE and Retropie with NOOBS companion add-on. As it is known the boot {partition} does not work in PI 4 when using SD cards but when using USB (SSD or sticks) it seems to work just fine.

Maybe @matthuisman could update hes guide regarding boot-back with NOOBS Companion add-on. I take it that the Pinn system resize website (https://pinn.mjh.nz/) will be update soonish regarding this Retropie update as I still have to figure out other things like resizing the partitions as when using 120gb SSD LE ends up taking half and it is a bit too much in my case.

Also LE update to latest 9.95.2 was successful via LibreELEC add-on using correct update channel.

I think this issue can be closed now.

**Comment by procount** [comment]
Matt's resize website will not be aware of this new OS untill I release it fully. Remember that you had to change the cmdline to be able to see it.

**Comment by DerangedPineapple** [comment]
Oh I know that you need to fully release it first. 

I merely meant that the Matt's website should or might be updated after your release. Bad wording on my part :)

Anyways, million thanks for you continued support on this matter!

**Comment by DerangedPineapple** [comment]
I was wondering if you are not too busy to release the Retropie 4.7.1 so Matt's website might offer it in a future. I need to adjust the partition sizes for LE and Retropie as half for Retropie and half for LE is not really a good solution currently when using  alt_image_source.

Anyways, no hurry just asking whether it could be possible in the near future to get "official" release.

**Comment by matthuisman** [comment]
my site will automatically pull in the latest OS's once a day around 3am NZ time I think.
So once it's in PINN - within 24 hours - you should see it on the resize app

**Comment by procount** [comment]
Retropie 4.7.1 added to PINN.
Just give it a while for the mirrors to synchronise and Matt's website to update.

**Comment by DerangedPineapple** [comment]
Thank you for the addition. 

Highly appreciated! Will be testing it out soon.

**Comment by DerangedPineapple** [comment]
Not trying to be annoying here but @matthuisman  's website has not been updated yet after Retropie 4.7.1 release for PINN was made.

It's been a few days so it should not be matter of synchronisation of mirrors. 

Sorry to pollute this repo for issues not directly related to PINN, I just have not found correct place to report that Matt's website has not been updated yet.

**Comment by matthuisman** [comment]
@procount 

https://github.com/procount/pinn-os/blob/master/os/os_all.json
seem to link to files that don't exist

Eg
"os_info":         "http://downloads.sourceforge.net/project/pinn/Retropie3/os.json"
"os_info":         "http://downloads.sourceforge.net/project/pinn/Retropie4/os.json",
"os_info":         "http://downloads.sourceforge.net/project/pinn/Retropie1/os.json",
"icon":            "http://downloads.sourceforge.net/project/pinn/Retropie1/Retropie1.png",

they should be http://downloads.sourceforge.net/project/pinn/os/Retropie3/os.json
etc etc

that'll be why PINN Resize icons are broken but none of the info has been updated as it uses os_info for that.

@DerangedPineapple
once the above urls are fixed - it should pop-up :)
I think you'll find even trying to install them via PINN wouldn't work due to above issue

**Comment by procount** [comment]
Oops! Sorry for that. I didn't update the URLs properly when moving them from testing to os.
Should be fixed now after Matt's webpage has refreshed itself.

**Comment by matthuisman** [comment]
Page has updated now :)
