### ISSUE TITLE
Backup Raspbian error

### ISSUE THREAD

**Issue by KilliK69** [procount/pinn#507]
Hello.
I am trying to backup Raspbian using PINN's option, but I am getting this error:
![Picture_2021 04 05_16 13 29](https://user-images.githubusercontent.com/10569527/113577603-306a5580-962a-11eb-9a63-e452d968fe86.jpg)

I guess it has to do with the OS's obsolete name. There is also a similar issue here: 
https://github.com/procount/pinn/issues/398
but the difference is that my OS still has the old Raspbian name.

Is there something I can do to fix this? PINN is updated to its latest version.

**Comment by procount** [comment]
Here are some instructions you can try:
1. boot into PINN as normal.
2. Enter the recovery shell using ctrl-alt-f2, login with root/raspberry
3. `cd /settings/Raspbian`
4. backup your existing script with `cp partition_setup.sh partition_setup.bak`
5. download a new script with `wget http://raw.githubusercontent.com/procount/pinn-os/master/partitions/Raspbian/partition_setup.sh`
6. `sync`
7. `rebootp`

**Comment by KilliK69** [comment]
hello, procount, thank you for your reply.
I tried your guide, but I am stuck at step 3. When I press `cd /settings/Raspbian`, I get the error: `cd: can't cd to /settings/Raspbian`

**Comment by procount** [comment]
Probably a spelling error.
`cd /settings`
`ls`
choose the folder that is most appropriate for your OS.

**Comment by KilliK69** [comment]
ok, got it, it is actually `cd /settings/os/Raspbian`

**Comment by procount** [comment]
Oh, yes. Sorry, I was going off my memory, which isn't always reliable :wink:

**Comment by KilliK69** [comment]
it is ok, I tried the ls command to find the folder by myself but it was only showing a dot. I guess settings is a hidden folder.

but now I am getting another error, when I apply the cp command.
the error is:
`cp: can't create 'partition_setup.bak': Read-only file system`

**Comment by procount** [comment]
Just check you are in /settings/os/Raspbian. That should be writeable.
If it still doesn't work, post the output of `mount`

**Comment by KilliK69** [comment]
ok, I think the problem was with me connecting through Putty/SSH. I tried again using directly the k/m, and it didnt give me any errors this time. 

The .bak file was created but the .sh file is still in the folder, the wget command worked but it saved the .sh from the repository, as partition_setup.sh.1. 

I assume this needs to overwrite the old partition_setup.sh file before I continue with the rest of the commands?

**Comment by procount** [comment]
yes

**Comment by KilliK69** [comment]
it worked perfectly. I finally completed the backup. Now I am going try what we discussed here:
https://www.raspberrypi.org/forums/viewtopic.php?p=1846767&sid=46f4217aebe5aaabdbd37e36d46206ac#p1846767

thank you very much for this great tool and all your help, procount.
