### ISSUE TITLE
Allow for custom resolutions

### ISSUE THREAD

**Issue by psmpm** [procount/pinn#508]
My display has a strange quirk that if it does not turn on with a 16:9 input, it will not detect any input at all. Obviously, this could be solved by using a different monitor, but I think it would be best if PiNN just had customizable resolution, instead of the 0-4 display mode thing.

**Comment by procount** [comment]
You can set your own custom resolution in config.txt, just like you can in Raspberry PiOS.

**Comment by psmpm** [comment]
> You can set your own custom resolution in config.txt, just like you can in Raspberry PiOS.

so the config.txt file in the "RECOVERY" partition, right?

**Comment by procount** [comment]
yes.
But be aware of the conditional filters in that file.
See https://www.raspberrypi.org/documentation/configuration/config-txt/conditional.md for details to make sure you put your config statements in the right place.

**Comment by procount** [comment]
Closing, as it seems to be resolved, but please reopen if you still have an issue
