### ISSUE TITLE
Volumio is not booting from PINN on Raspberry Pi 4 8GB

### ISSUE THREAD

**Issue by radcko** [procount/pinn#519]
Hi!
I've just flashed PINN v3.5.5 on my new Raspberry Pi 4 8GB and I installed LibreELEC and Volumio. LibreELEC is starting but Volumio is not booting (see picture below). The latest Volumio version (v2.882) is running perfect when flashed alone on SD card. The Volumio version which can be installed from PINN is the most recent one (v2.882) or is an older Volumio version?
Thank you!

![RPi4_PINN_Volumio_01](https://user-images.githubusercontent.com/84272631/118396229-d9a36300-b64e-11eb-8a7b-8f55f9da00d1.jpg)
![RPi4_PINN_Volumio_02](https://user-images.githubusercontent.com/84272631/118396230-dad49000-b64e-11eb-9b3e-a7501faef0d8.jpg)

**Comment by lurch** [comment]
I think the `start4.elf: is not compatible` means that the `start4.elf` in your Volumio boot partition is too old to boot on your Pi4?
Hopefully this is something that @procount will be able to fix easily? :crossed_fingers:

**Comment by radcko** [comment]
Is it something I can fix myself or requires more than very basic Linux konwledge? :)

**Comment by lurch** [comment]
You could try mounting the Volumio boot partition from your PINN card, and copying across the start4.elf from the Volumio standalone version?

**Comment by radcko** [comment]
I will try try this, thank you!

**Comment by radcko** [comment]
I ran Ubuntu from an USB stick and I replaced `start4.elf` in Volumio PINN with the the `start4.elf` from Volumio standalone version. When I boot Volumio from PINN I can pass the boot screen but Volumio doesn't start, I have a black screen.

Maybe to try to replace also `fixup4.dat`? 

_Edit:_

I replaced also `fixup4.dat`. The good news is that Volumio is starting, the bad news is Volumio is not detecting my USB DAC (which is visible when using the standalone version). I have only Audio Jack and HDMI audio outputs.

So I assume there's something more to do than this ...

**Comment by lurch** [comment]
> The good news is that Volumio is starting

Hooray! Well done for fixing your non-booting problem.

> the bad news is Volumio is not detecting my USB DAC (which is visible when using the standalone version)

Perhaps that's simply down to the version of Volumio in PINN being older than the standalone version? :shrug:

**Comment by radcko** [comment]
> Perhaps that's simply down to the version of Volumio in PINN being older than the standalone version? 🤷

I don't think so, I used my USB DAC with older versions of Volumio from PINN but with my RPi3. I had this issue with Volumio when I installed PINN on RPi4.

Maybe this problem will be solved if the most recent version of Volumio could be added to PINN, I don't know.

**Comment by procount** [comment]
Ping @matthuisman - I think Volumio is one of yours. Any chance you could update it?

**Comment by matthuisman** [comment]
Current pinn volumio version is 2.779.
I'll try update to 2.882.
I thought 2.779 should boot on pi4 tho...

It is one of the trickier OS's. 
Requires editing the initrd

**Comment by radcko** [comment]
> I'll try update to 2.882.
> I thought 2.779 should boot on pi4 tho...

Thank you!
Unfortunately it doesn't boot. If I can help with something...

**Comment by matthuisman** [comment]
2.882 is up now :)
and tested on pi4 as well.

i had tested 2.779  on a Pi4 back when created...
so maybe the Pi firmware has changed since then which required the OS to have newer elfs

Please close this issue :)

**Comment by procount** [comment]
Thanks Matt. Could it be because he had a Pi4 8GB?

**Comment by matthuisman** [comment]
oh yeh maybe...

I swear my Pi4 acts differently recently.
It never used to show that bootloader screen with QR code...
but i did to a full upgrade in raspbian - so maybe the firmware was updated?

**Comment by radcko** [comment]
> 2.882 is up now :)
> and tested on pi4 as well.

Oh yeah, it's working like a charm. 🤩 No problems at all with both USB audio output and HifiBerry Digi+ Pro digital outputs.
Thank you very much! 👍

Case closed! 😊

**Comment by lurch** [comment]
@matthuisman Yes, doing an `apt upgrade` in Raspbian will update your Pi4's EEPROM https://www.raspberrypi.org/documentation/hardware/raspberrypi/booteeprom.md (to [2020-09-03](https://github.com/raspberrypi/rpi-eeprom/blob/master/rpi-eeprom-update#L38) ).
