### ISSUE TITLE
Black screen | PINN haven't started

### ISSUE THREAD

**Issue by hinzpak** [procount/pinn#523]
Hi PINNers! I am following all the steps, downloading and extracting PINN to the SDcard. My problem comes right after putting the SDcard into the pi4. There was a colorful screen with gradient but then it turns all black. The name of the SDcard changed to "RECOVERY" after I put it back on my mac, which I believe something was running, just that there was nothing (all black) when I put the card into pi4. any idea? Thanks!

**Comment by hinzpak** [comment]
ok solved by switching to another HDMI port, like NOOBS
https://raspberrypi.stackexchange.com/questions/101842/noobs-stuck-at-rainbow-screen-raspberry-pi-4

**Comment by procount** [comment]
That's odd. If you are using an up to date version of PINN, it should now auto-detect which HDMI port is connected, provided you have the HDMI cable connected before you power on.

**Comment by hinzpak** [comment]
Yea weird. But thats wht i have experienced with the latest download hours ago. So just switch the hdmi port whenever got stuck in the rainbow screen on PINN
