### ISSUE TITLE
Installation issue with lineage18-rpi4-atv

### ISSUE THREAD

**Issue by shivasiddharth** [procount/pinn#527]
When installing the lineage18-rpi4-atv, it says that system.xz and vendor.xz are missing. If I rename the system.tar.xz and vendor.tar.xz to system.xz and vendor.xz, the installation goes through, but the OS never loads. It sets the Pi on a boot loop. Everytime I choose to boot lineage18-rpi4-atv, the Pi reboots.

**Comment by shivasiddharth** [comment]
Ok. I have managed to resolve the issue. Apparently there is an issue with the system and vendor files that have been uploaded to source forge. You may update the repo with these files https://mega.nz/file/uwpmQZwZ#5c76OkdZcI5P-Ac9T3rvxdYsbRFWDtUCKN_pNlV5Eis I have tested it and its working.

**Comment by procount** [comment]
Those files are not ready for release yet.
System and Vendor images must be img.xz files, which they currently are not.

**Comment by shivasiddharth** [comment]
I have generated those img.xz files. The files in the https://github.com/procount/pinn/issues/527#issuecomment-860048312 link have been tested and its working. I have modified the partitions JSON file as well.
