### ISSUE TITLE
Raspberry pi 7" touchscreen display do not rotate

### ISSUE THREAD

**Issue by gdemoor** [procount/pinn#537]
After installing the latest pinn update the raspberry pi 7" touchscreen display do not rotate anymore. How can i solved this.

**Comment by procount** [comment]
Which model of Pi?

**Comment by procount** [comment]
How did you rotate it before?
Please see https://www.raspberrypi.org/documentation/configuration/config-txt/video.md
It seems there may have been some config.txt changes in the firmware.
Try "display_lcd_rotate"

**Comment by gdemoor** [comment]
The configuration file has been overwritten after the update. display_lcd_rotate was missing in the config.txt

**Comment by procount** [comment]
Please see https://github.com/procount/pinn/issues/536#issuecomment-874158642 which should fix this in future.
