### ISSUE TITLE
RTAndroid partitioning script error

### ISSUE THREAD

**Issue by win8linux** [procount/pinn#55]
I'm encountering an issue with installing RTAndroid. The install fails with this error:
`cpio: invalid option -- o`

This occurs after the following part of the partition setup script:
`cpio -o -H newc`

**Comment by procount** [comment]
Could you please try it with pinn-23a.zip?
You will find it in the archive folder on sourceforge. Ignore any request to update to the latest version when it starts! ;-)

PINN 2.4 was a complete rewrite to align with NOOBS 2.4, so it is possible I missed something. Please report back if that works and if so I should be able to fix pinn 2.4 correctly.
Thanks.

**Comment by win8linux** [comment]
I just tried installing RTAndroid with PINN 2.3a and it works! This issue seems to specifically affect PINN versions 2.4 onwards. Maybe something with the cpio/busybox binary?

**Comment by procount** [comment]
Thanks for confirming. I will fix it in the next release

**Comment by win8linux** [comment]
Is there a plan to around when the new release is uploaded or is it on a "when it's ready" kind of timeline?

**Comment by procount** [comment]
I have tested the fix and it works. If you are desperate I can upload a test version. 

Right now I am working on a new feature so it will be released when it is ready.

**Comment by win8linux** [comment]
Sure. that'd be nice! :+1:

**Comment by procount** [comment]
I put pinn-241d.zip in the sourceforge testing folder.
If you have a chance to confirm it is now ok, I would be grateful.

**Comment by win8linux** [comment]
I apologize for replying late; I was tending to my sick mum (vertigo) for a couple of days.

Anyhow, I've tested RTAndroid on PINN 2.4.1d successfully without issue.

**Comment by procount** [comment]
No need to apologize. We all have additional constraints....
Thanks for testing.
