### ISSUE TITLE
Resizing OSes after install

### ISSUE THREAD

**Issue by sz55net** [procount/pinn#551]
I have a LibreELEC and RPi OS install set up on an SD card, along with 2 Project Spaces. I'd like to increase the size of the RPi OS install and shrink LibreELEC. Can I do this using GParted or a similar tool?

**Comment by procount** [comment]
yes.

**Comment by lurch** [comment]
(Vaguely) similar discussion in #549

**Comment by sz55net** [comment]
Thanks! That's all I needed to know.
