### ISSUE TITLE
XBian is not installed with "ERROR 404: Not Found"

### ISSUE THREAD

**Issue by borderite** [procount/pinn#557]
I tried to install XBian on RPi 3B using pinn. My attempt failed with the "OS(es) installed with errors" message. The debug log shows that pinn fails to retreive the XBian boot file, and it seems that the URL of the file shown in the log is incorrect. I would greatly appreciate your fixing the problem.

For your information I have attahced the photo of the log.

Thanks!!

![IMG_20210908_162540075_HDR](https://user-images.githubusercontent.com/14339406/132601090-d3d02928-c168-4a18-8d0a-368a9f40cb74.jpg)

**Comment by procount** [comment]
Sorry for the long delay.
It looks like they have upgraded Xbian for RPi4 compatibility and the Rpi3 version has disappeared.
I shall have to find out if it is still available and also support the RPi4 version.

**Comment by Borjatgalan** [comment]
Today this error is still ocurring.

**Comment by procount** [comment]
Sorry, I've not had time to look at this yet.

**Comment by procount** [comment]
URL updated. Installed on Pi4/PiZero2 ok.
