### ISSUE TITLE
unable to re-use runinstaller option remotely

### ISSUE THREAD

**Issue by narspt** [procount/pinn#567]
Hi, I decided to re-partition the sd card of a RPi I control remotely (using 'vncshare' on PINN) by adding 'runinstaller' option and reboot, however after reboot I did completely lost remote connectivity (wifi), then I connected a TV on that RPi to see what happened and found just a question dialog on top of PINN wallpaper saying that there are existing OS's and asking if I really want to initialize the card (this seems new on 3.6.1.2)... the problem is that on this state wifi is apparently not initialized and then there is no way to proceed remotely. Using PINN 3.6.2.

**Comment by procount** [comment]
Sometimes new features just conspire against me! :wink:
I added the feature to maintain wifi setting across a "runinstall" action precisely so you could refresh your setup remotely.
And then I added the feature to check the presence of existing OSes to prevent accidental destruction, but as you say, the network is not up at that time, so it blocks the first feature.
It looks like I need to add another option to bypass the OS check!

**Comment by narspt** [comment]
And I had the idea of doing this for some time now, but never did it before... had to do it now that you just added this check lol
Thanks for the fast reply!

**Comment by lurch** [comment]
> It looks like I need to add another option to bypass the OS check!

Would adding yet-another-option be easier than just rearranging the "startup order" so that wifi (and VNC) is initialised before asking the user if they definitely want to delete all their OSes? :man_shrugging:

**Comment by procount** [comment]
The network seems to take an age to start and I wouldn't  want it to slow down the startup for all use cases. But I guess it's worth looking at.

**Comment by lurch** [comment]
> I wouldn't want it to slow down the startup for all use cases

Good point. Perhaps it's only worth "waiting for network" if the SSH or VNC options have also been enabled? Or maybe it's worth adding an explicit "wait for network" option? (which IIRC is also an option that Raspberry Pi OS has?)

IMHO a "wait for network" option feels far more generic than a "bypass the OS check" option :wink:

**Comment by procount** [comment]
If I can start the network in parallel, just earlier, it will just be the user who has to wait when they need to.

**Comment by procount** [comment]
It turns out I've already included the `forceruninstaller` option that you can add to recovery.cmdline in v3.6.2. This option prevents the dialog box occurring and will force the card to be repartitioned regardless.
I shall document it shortly.

**Comment by narspt** [comment]
Thanks! Will try it soon.
