### ISSUE TITLE
Update to match noobs 3.7?

### ISSUE THREAD

**Issue by m-roberts** [procount/pinn#568]
NOOBS 3.7 release is [here](https://github.com/raspberrypi/noobs/commit/5de0ec896cefff9f095d3243ee41bcce392ce0ef), which contains new firmware - including, I believe, support for 8GB Pi 4 (if I recall).

**Comment by procount** [comment]
I think 8GB pi4 has been supported for a while.
Pinn 3.7 is in testing as it required a new build environment. Should be available soon.

**Comment by m-roberts** [comment]
> I think 8GB pi4 has been supported for a while.

Oops - I thought I couldn't get PINN to work on mine, but NOOBS 3.7 did.

> Pinn 3.7 is in testing as it required a new build environment. Should be available soon.

Great! Is there a list of changes anywhere?

**Comment by procount** [comment]
https://sourceforge.net/projects/pinn/files/

**Comment by m-roberts** [comment]
Sorry, I meant for NOOBS/PINN 3.7

**Comment by procount** [comment]
The link above was for the latest Pinn, currently 3.6.2. It will be updated when I make 3.7 available, but then the note will probably be just to match noobs latest firmware/kernel & build environment.
I don't think there is a specific change log for noobs, unless you look at the github commits.

**Comment by EctoOne** [comment]
Just a small note. I've been using PINN on a Pi 4 8gb for like one and a half years now.

I had some issues that caused the Pi not to boot when I had a Monitor connected which was turned off. But that was fixed in one of the updates.

**Comment by m-roberts** [comment]
> Just a small note. I've been using PINN on a Pi 4 8gb for like one and a half years now.
> 
> I had some issues that caused the Pi not to boot when I had a Monitor connected which was turned off. But that was fixed in one of the updates.

Thanks for this. It seems I was way off. At any rate, updating to latest firmware is usually a good move!

**Comment by procount** [comment]
PINN is now up to v3.7.3 so I think we can close this now.
