### ISSUE TITLE
Install os

### ISSUE THREAD

**Issue by slaygirlz** [procount/pinn#569]
Is there a way to install another os instead over writing all the os installed

**Comment by procount** [comment]
Yes. It is documented in the manual.
Have a look in particular at:

https://github.com/procount/pinn/blob/master/README_PINN.md#project-spaces

https://github.com/procount/pinn/blob/master/README_PINN.md#reinstall-individual-oses

https://github.com/procount/pinn/blob/master/README_PINN.md#replace-individual-oses

**Comment by slaygirlz** [comment]
I don’t think so what I mean that berryboot allows you to install an os without Berryboot removing anything on the sd card 

or the links you send are right

but what are the down sides tho

**Comment by procount** [comment]
PINN is based on NOOBS and it works in a different way to Berryboot.
The idea with NOOBS/PINN is that it allocates all the drive space to the selected OSes, so there is never any space left to install something else later - you always need to replace an existing OS.

**Comment by slaygirlz** [comment]
Ohhh ok what happens if I use project space will it let me not reinstall any os?

**Comment by procount** [comment]
A projectspace is an empty OS that you can use to reserve space for a future OS. You can replace the projectspace at a later date with a different OS.
It is a bit limited because the future OS must have the same partition layout as the projectspace (a boot and a root partition), but that covers about 80% of them. Just don't expect to install something like Android in them because they need 4 partitions.

**Comment by slaygirlz** [comment]
I’m confused 

How do I config projects space tho
I’m new to pinn

**Comment by slaygirlz** [comment]
Do you have a video to how to use them?

**Comment by procount** [comment]
No I don't have any videos. Maybe I should become a Youtuber!

You don't really config a project space. Depending on how big your drive is, just install 1 or 2 projectspaces, along with any OSes that you want to a fresh drive.
Later, when you want to install another OS, just select the OS you want, then select a free installed ProjectSpace from the maintenance menu and select Replace. Choose the new OS from the drop down list and replace the projectspace with your new OS. Done.

**Comment by slaygirlz** [comment]
You should be a YouTuber 
If you did it will make it easy to use them

**Comment by lurch** [comment]
IMHO the easiest way to get to learn how to use NOOBS / PINN if you aren't sure what you're doing (after reading the documentation), is to take a spare SD card (that you're happy to completely overwrite) and just spend an afternoon experimenting / playing with it, to get a feel for how the different features work. :slightly_smiling_face:

**Comment by slaygirlz** [comment]
dang ok i wish there was videos to know of but ok i will use a different sd card and play with it
