### ISSUE TITLE
Ssh

### ISSUE THREAD

**Issue by Daigo1317** [procount/pinn#572]
How ti use shh on pinn?

**Comment by procount** [comment]
It is documented in the manual at https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-access-the-shell-or-ssh-into-pinn
Please note that SSH is for administration type low level tasks and cannot be used to operate PINN remotely (e.g. choosing which OS to boot, except by modifying setting files).
If you want to control the GUI of PINN remotely/headlessly, then you need the `vncshare` option, normally in combination with `forcetrigger`. See https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-pinn-headlessly-vnc
