### ISSUE TITLE
Missing Instruction: How to uninstall an OS

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#574]
Dear @procount ,

please include instructions in README.MD on how to uninstall an installed operating system.

best regards

**Comment by procount** [comment]
You can't. You can only replace it with another. 
It can be hidden from the menu if you make it non-bootable. Is that sufficient?

The idea with NOOBS was to allocate all drive space at initialisation. It was not designed to remove OSes and add more later on. PINN has improved on that with the ability to reinstall or replace individual OSes, or to reserve space with Project Spaces which can later be replaced by another OS.

**Comment by Tabaluga** [comment]
Thanks for your explanation. Now I understood this behavior and design.. Indeed I've searched already for some clues within the NOOBS documentation but found .. as you imagine .. nothing at all about this. Perhaps add this into the getting started guide / FAQ. best regards

**Comment by lurch** [comment]
@procount Is it possible to "replace" an installed OS with a ProjectSpace? If so, would that count as "uninstalling" an OS? :wink:

**Comment by procount** [comment]
Wow! Why did I never think of that?
Yes, for OSes with a "standard" partition layout
