### ISSUE TITLE
Missing Information: Download Locations of OS-Files

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#576]
Dear @procount ,

please include information in the README.MD where the supported operating systems can be downloaded manually without using PINN, which files PINN needs and where these files have to be stored for an offline installation.

I'm using PINN offline.

best regards

**Comment by procount** [comment]
You need to be online to get the list of OSes in the first place as this is downloaded. If you are online, it is easiest to just download them with PINN.

If you are OFFLINE and want to download them with another computer, then you can start off at the list of Repositories https://github.com/procount/pinn-os/blob/master/os/repo_list.json and follow each link to the list of OSes, and look inside that for the location of the OS folders to download. (You can find this link in the Edit Options dialog from the Maintenance menu)

https://github.com/procount/pinn/blob/master/README_PINN.md#download
https://github.com/procount/pinn/blob/master/README_PINN.md#local-images-on-usb-stick
