### ISSUE TITLE
Missing Information: Set Bookmark to PINN Website for Browser

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#579]
Dear @procount ,

please add bookmark to PINN Website for the browser.

best regards

**Comment by procount** [comment]
I don't have a specific website for PINN. Do you mean my pages on Sourceforge, Github, or the Sticky forum post?

**Comment by Tabaluga** [comment]
I'm sorry I mean a bookmark in the browser within PINN.

best regards

**Comment by procount** [comment]
Yes, but what page should this bookmark link to?

**Comment by Tabaluga** [comment]
Perhaps this repo or the wiki would be great.

In the past I searched some information about mac adress, project spaces .. found no documentation within PINN and tried the browser to read the online documentation / wiki / guides. best regards

**Comment by procount** [comment]
p3.7.4
