### ISSUE TITLE
Bug: Exit Button

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#580]
Dear @procount ,

the exit button is not working, if no os is installed.

best regards

**Comment by procount** [comment]
This is a feature from NOOBS.
The exit button takes you to the BootSelection dialog. If there is no OS installed, there was no need to go there, so it is disabled.
In PINN, if you go to one of the other menus, you can press ESC to get to the bootselection dialog even if there are no OSes loaded, but the only thing you can do from there is reboot.
If you want to powerdown, just pull the power lead out.

**Comment by Tabaluga** [comment]
Thanks for your explanation. Perhaps add this into the getting sarted guide / FAQ. best regards
