### ISSUE TITLE
Idea: Move the Changelog

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#583]
Dear @procount ,

please move the Changelog into an own file, or perhaps you can use something like the [release notes](https://github.com/atom/atom/releases) of the atom editor.

They even included (connected) these information upon their [main website](https://atom.io/releases).

best regards

**Comment by procount** [comment]
Like this file: [config.md](https://github.com/procount/pinn/blob/master/changes.md) maybe?

**Comment by Tabaluga** [comment]
Yes. This looks great. perhaps you could merge both files. Best regards

**Comment by procount** [comment]
Both files? What is the other file you mean?
There is already a history.md file, a changes.md file, a readme.md file on sourceforge and the first post on my sticky forum post contains a complete log too. I don't think I need any more change logs.

**Comment by Tabaluga** [comment]
Thanks for your explanation and please excuse my missing knowledge.
To be honest I'm browsing from my phone, the user-agent is set to mobile and the code section is not expanded at all. 
I read through the readme.md, found the change-history and thought that it might be a good idea to move this into an new independent file.
Since the time of reading I didn't had the knowledge of the other changes.md and history.md files.
best regards

**Comment by procount** [comment]
No worries :smile:

**Comment by lurch** [comment]
Perhaps it's worth removing the "Change History" part of README.md, and just linking to one of the other files instead? :shrug:

**Comment by Tabaluga** [comment]
:+1:
