### ISSUE TITLE
Missing Option: Boot into Recovery

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#584]
Dear @procount ,

please insert `boot into recovery` option in boot menu.

best regards

**Comment by procount** [comment]
Do you mean to reboot back into PINN, or to boot into the recovery shell (Ctrl-alt-f2)?

**Comment by Tabaluga** [comment]
The second option: boot into recovery shell (Ctrl-alt-f2). best regards

**Comment by procount** [comment]
I presume you want this to be able to access it from the TV remote without a keyboard?
But the recovery shell needs a keyboard as it is an external program and won't work with the virtual keyboard.
If you have a keyboard, you can press ctrl-alt-f2.

The other alternative is to remote in from an external PC/mobile phone with SSH if you enable it.
