### ISSUE TITLE
Missing Instruction: How to setup, config and use ProjectSpace(s)

### ISSUE THREAD

**Issue by Tabaluga** [procount/pinn#585]
Dear @procount ,

please add additional information about the ProjectSpaces.

> ProjectSpaces are empty OSes that can be used to reserve space for a future OS to be installed into.

This explanation is not very helpful to me. I want to install three OSes:

1. libreelec
2. alpine (later)
3. retropie (later)

How many ProjectSpaces do I need to create?

How to install the OSes into the ProjectSpaces?

best regards

**Comment by procount** [comment]
Install LIbreElec + 2 projectSpaces
Later, replace a ProjectSpace with your required OS.

**Comment by Tabaluga** [comment]
Thanks for your explanation. This helped me a lot. Perhaps add this into the getting started guide / FAQ. best regards

**Comment by procount** [comment]
https://github.com/procount/pinn/blob/master/README_PINN.md#project-spaces ?

**Comment by Tabaluga** [comment]
Thanks for your explanation. I've read this already but it was unclear to me when do I need to install ProjectSpaces. best regards

**Comment by procount** [comment]
documentation improved
