### ISSUE TITLE
add suport to pi zero w 2

### ISSUE THREAD

**Issue by zaballa** [procount/pinn#589]
it would be wonderfull to have support for this model, recalbox an retropie for pi zero doesnt work

**Comment by lurch** [comment]
FYI there's a big difference between PINN itself (i.e. the installer-GUI) working on the Pi Zero 2 W, and each of the OSes installed by PINN (e.g. recalbox or retropie) supporting the Pi Zero 2 W. The latter is something that each individual OS needs to fix themselves.
(Although as the Pi Zero 2 W is so similar to the Pi 3B from a software PoV, I think each OS "just" needs updated firmware and a new DTB?)

**Comment by procount** [comment]
PINN is already compliant. The other OSes will be updated in PINN as their maintainers update them.
