### ISSUE TITLE
Is PINN the way forward?

### ISSUE THREAD

**Issue by vanfanel** [procount/pinn#594]
Hi there,

I discovered today that NOOBS has been retired.
I need a multiboot solution for a couple of GNU/Linux + Risc OS systems on the same SD that I can trust for the years to come. Is PINN that solution? Will it's development continue now that NOOBS is not being developed anymore?

Thanks!

**Comment by procount** [comment]
PINN is a fork of NOOBS, so it is compatible and familiar, just with more features.
I have no plans to stop supporting it for the foreseeable future.

**Comment by vanfanel** [comment]
@procount Thanks a lot for the work you seem to put on this.
Yes, this seems to be the way to go! :)
