### ISSUE TITLE
About Recalbox

### ISSUE THREAD

**Issue by sefaozsoy** [procount/pinn#601]
I can't install RecalBox on my Rpi 1. First I tried the "USE THIS ONE" (old version) did not even start downloading. Secondly, I tried the current (8.0). Downloaded but setup failed. (PINN latest version)

**Comment by procount** [comment]
Is it working ok now?

**Comment by sefaozsoy** [comment]
> Is it working ok now?

The old one was not starting to download. It's fixed now. Thanks
