### ISSUE TITLE
PINN 2.4.2 beta - problem on language file 

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#61]
@procount 

Thanks for the new beta (2.4.2)

I made an update to Italian language update. But please check before to apply.
I download the master branch and apply the command

**_lupdate recovery.pro_**

It found a new string and changed many windows reference in the language file (compare original language and my proposal).
When you release a new version I think that it's better that you run always

**_lupdate recovery.pro_**

before to compress new version and upload it to have all language s updated

Please check if I did it in the right way.

Thanks.

**Comment by procount** [comment]
PR merged. Thanks.
