### ISSUE TITLE
Git merge conflict has been inadvertently committed

### ISSUE THREAD

**Issue by lurch** [procount/pinn#616]
See https://github.com/procount/pinn/blob/master/recovery/translation_zh_TW.ts#L842-L859
This results in `lrelease error: Parse error at .../pinn/recovery/translation_zh_TW.ts:842:2: Unexpected '<'.` when you try to run `updateqm.sh`.

EDIT: and also means that `BUILDME.sh` fails with `RCC: Error in 'icons.qrc': Cannot find file 'translation_ca.qm'`.
My temporary workaround was to remove `translation_zh_TW.qm` from `recovery/icons.qrc` and remove `translation_zh_TW.ts` from `recovery/recovery.pro`.

**Comment by procount** [comment]
How did that go unnoticed?

(How come you are doing some late night building?)

**Comment by lurch** [comment]
Also, https://github.com/procount/pinn/blob/master/README_PINN.md#run-build-script says "If your build machine also has some QT5 components, it is useful to export QT_SELECT=4 before building to ensure the QT4 component versions are selected." so perhaps [this line](https://github.com/procount/pinn/blob/master/recovery/updateqm.sh#L3) ought to be removed? Or is that only causing me a problem because I was trying to run `updateqm.sh` on Ubuntu 16.04 ?

**Comment by lurch** [comment]
> (How come you are doing some late night building?)

PINN is a project that I know takes **ages** to build, so I thought I'd use it to "benchmark" my (new-ish) laptop against my (old-ish) desktop :laughing:

**Comment by procount** [comment]
Not sure I ever run `updateqm.sh`, but that line looks errant. I moved development from Ubuntu 14.04 to 20.04 now to match RPF build server.

**Comment by lurch** [comment]
Probably not worth "fixing" if it's only old Ubuntu versions that are affected.

**Comment by procount** [comment]
Fixed by 3.8

**Comment by lurch** [comment]
https://github.com/procount/pinn/blob/master/recovery/translation_zh_TW.ts#L842-L859 still looks wrong?

**Comment by procount** [comment]
I should probably push the commit up, I suppose..... :wink:
