### ISSUE TITLE
Kindly update Lineage OS builds.

### ISSUE THREAD

**Issue by ghost** [procount/pinn#617]
Hi there, kindly update lineage os builds of konstakang.  
(Lineage 18 ATV)

**Comment by procount** [comment]
I've only just updated them and now he has another 6 releases - I can't keep up! :wink:
OK I'll see what I can do....

**Comment by lurch** [comment]
Perhaps it's worth trying to convince the Lineage developer(s) to produce "PINN compatible" builds themselves, since there's clearly quite a large demand for it...?

**Comment by ghost** [comment]
> I've only just updated them and now he has another 6 releases - I can't keep up! 😉 OK I'll see what I can do....

Yeah, kindly update Twister too,

**Comment by ghost** [comment]
> Perhaps it's worth trying to convince the Lineage developer(s) to produce "PINN compatible" builds themselves, since there's clearly quite a large demand for it...?

Yeah, he told to ask PINN dev, stuck in a ∞ loop lol.

**Comment by procount** [comment]
Lineage 17/18/19 updated. Please report any issues.

**Comment by ghost** [comment]
Hi, did you update the main files? 
I see only some jsons are updated.

Will surely report issues.

**Comment by procount** [comment]
Yes.
Where are you looking? 
I'm experimenting with a more seamless upgrade process so that I can easily roll back if there are any problems.

**Comment by ghost** [comment]
It's in OS next folder, right? 
I don't have extra USB currently so will check it in a day or two. 

Konstang has released January update on LineageOS 18/19, and when I looked in your version it was November which is old.

So I wanted to know if LineageOS 18/19 in PINN are updated to January.

**Comment by procount** [comment]
Maybe you are looking the wrong place. They should all be current, at least for now ;)

os/17 is the only November dated one.
os/18 is Dec 21
os/19 is Dec 21
os_next/17 is Dec 21
os_next/18 is Jan 22
os_next/19 is Jan 22

![image](https://user-images.githubusercontent.com/4853137/151967414-0b61147e-e096-410a-8c63-0e5c91c819f5.png)

If the new ones are ok, I will migrate them to the os folder

**Comment by ghost** [comment]
Okay,
Will test LOS18 and tell you in some days, so I can directly download them from Pinn on pi4? or have to do something special?

**Comment by procount** [comment]
Yes you can download them directly from PINN.
Although, some people are reporting some bad transfers from the sourceforge hosting site at the moment. 
If you experience errors, try installing multiple times. Or even downloading them to a separate USB drive via PINN or manually (see the README_PINN.md file) and install them from a local copy if you get persistent errors.

**Comment by mikuzz** [comment]
Hi procount,
yesterday I was able to install Lineage 19 (14.01.2022)
The installation was fine as usual, I didn't get further in the
installation of gapps and all others apps for the moment.

**Comment by procount** [comment]
Closing now the latest LineageOS's are available and PINN is updated to back them up properly
