### ISSUE TITLE
Raspberry Pi OS 64 bit (Desktop and Lite) out of BETA - request for an images

### ISSUE THREAD

**Issue by godzinilla** [procount/pinn#623]
Hello @procount !

Raspberry Foundation at 28th of January 2022 finally pulled the 64 bit images out of the beta program. Images for Desktop and Lite are available. So it is time to prepare these images for the PINN :)

https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

More info on their news website:
https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

**Comment by lurch** [comment]
I _believe_ @XECDesign is currently working on the 64-bit Raspberry Pi OS images for NOOBS (?), and once he's done that they'll automatically appear in PINN as well.

**Comment by XECDesign** [comment]
Should've already been in NOOBS yesterday.

**Comment by lurch** [comment]
Oh cool! Are they not appearing in PINN @godzinilla ?

**Comment by godzinilla** [comment]
> 

Images are available :) Sorry, did not checked it before creating an issue :O
