### ISSUE TITLE
Add an easy way to forget WiFi ?

### ISSUE THREAD

**Issue by MopheusDG** [procount/pinn#627]
Hi, I've connected my PINN to WiFI and I want to forget my connecting now, is there any simple way to do it ?

Thanks.

**Comment by procount** [comment]
Press Ctrl-Alt-F2 to get to the recovery shell.
Login with username `root` and password `raspberry`
type the following:
```
rm /settings/wpa_supplicant.conf
sync
rebootp
```

**Comment by MopheusDG** [comment]
Thanks @procount. Works perfectly.

**Comment by procount** [comment]
Re-opening just to remind me to improve this ;)

**Comment by procount** [comment]
New DELETE button added to wifi dialog in p3.8.3 will now forget the wifi connection.
