### ISSUE TITLE
Move OS non-tarball files to Git?

### ISSUE THREAD

**Issue by matthuisman** [procount/pinn#63]
Hi @procount 

Would it be possible for you to move your OS non-tarballs to GIT?

I found that you can't hotlink Sourceforge images for starters.
Which leads to this uglieness

![image](https://cloud.githubusercontent.com/assets/6225961/26517991/7ae01dbc-42f9-11e7-8afe-d84a3d872a79.png)

Also, having a git history of partition_setup / os.json / partitions.json wouldn't hurt either :)

I think you already do this for Arch OS.

Then just have the tar-balls on sourceforge.

What you think?

**Comment by procount** [comment]
I didn't know you can't hotlink sourceforge files. Is it because of its redirections and mirrors? I know I had to add extra support in for sourceforge and fake a user-agent inthe request.
But it is convenient to put all the meta files for each OS in one location for maintainability. I am processing about 25 different OSes now, so it needs to be easy to deploy.

I'm not too bothered about history of the meta files, but I do like the statistics that sourceforge gives me. Arch was the first OS I added, but I don't host the tarballs, so it is a bit different and it will be updated soon to match the others.
I will have a think about the icons.....

**Comment by matthuisman** [comment]
Yeh, the redirect causes the issues with the icons

Note:
I have just added KANO_OS (I saw someone request it on your PINN sourceforge)
https://bitbucket.org/matthuisman/pinn-os/raw/master/os_list_v3.json

They have a noobs zip package, so was pretty easy :)
Unfortunately they don't host the boot and root separately so I needed to extract these and upload to sourceforge.

**Comment by procount** [comment]
On PINN sourceforge? I've not seen it. The only issue I had there was about OSMC....
Anyway, thanks for adding KANO.

BTW have you checked if your OSes work with Autoboot? If not, they might need a new RPI-firmware.
I have created a script that will process most distro images now and pull them apart into the right format.

**Comment by matthuisman** [comment]
For the icons, I mean hotlinking (not in PINN itself).
They work fine when showing in PINN.

I could make my cache script to also download the icons and store on my server.
Then the web-app can show those.
I just wanted it as light on my server resources as possible - that's all :)
But, I guess they are pretty small...

Update

I now cache the images and serve them locally (so no hotlinking required) :

**Comment by matthuisman** [comment]
@procount 

I have just added RasPlex OS :)
http://www.rasplex.com/

Is there somewhere you want me to contact you when I add a system?

Also, are you able to rename the provider from "Raspberry Pi" to "NOOBS" in your repo file?
https://github.com/procount/pinn-os/blob/master/os/repo_list.json
NOOBS makes more sense to me.

And I have also made a new page which is just a basic list of available systems
**http://noobs.matthuisman.nz/?l**

Note: the ?l parameter (without that - it's the main app)

By default it will show all PINN systems for all boards..
You can narrow down to a board by parsing b=Pi[number] (0,1,2 or 3)

eg. **http://noobs.matthuisman.nz/?l&b=Pi3**

To show just NOOBS sysyems, you add i=n
eg. **http://noobs.matthuisman.nz/?l&b=Pi3&i=n**

It might be a good way that you can link to a list of PINN systems :)
eg. from your forum post or sourceforge .

New systems will be pulled in 1am NZ time each night :)
(Systems are considered new for 7 days after they are first added from the cache script)
