### ISSUE TITLE
PINN added to official RPI Imager!

### ISSUE THREAD

**Issue by RanchoHam** [procount/pinn#632]
Congratulations on PINN being added to the official RPI Imager.  

I would suggest you include that installation method on the README.md, since it is buried under Misc utility images -> PINN -> PINN (Released 2022-02-09).

**Comment by procount** [comment]
I already mentioned it here -> https://forums.raspberrypi.com/viewtopic.php?t=142574
and here -> https://forums.raspberrypi.com/viewtopic.php?p=1974662#p1974662
But yes, I need to extend some more. 
If you have a Pi4 with the latest boot loader, it even works with the beta network install. So just plug in your Pi4 to the internet, boot it without any SD cards etc then use the network RPI imager to install PINN to an SD card and then download whatever OSes you want!
