### ISSUE TITLE
Raspberry Pi OS 64-bit Bullseye back-up not working

### ISSUE THREAD

**Issue by RanchoHam** [procount/pinn#638]
I used to be able to back-up RaspiOS Buster 64-bit instance, but the current Bullseye 64-bit installation cannot be backed up.

**Comment by procount** [comment]
You should be able to back it up. What error messages are you getting? Any useful info in the debug log?

**Comment by RanchoHam** [comment]
Error dialog reads:
"Warning:  Unsupported Operating System(s) detected.  PINN currently cannot backup the following OSs correctly:
Raspberry Pi OS (64-bit)"
The debug log does not look helpful to me but here it is anyway.  (BTW I had to rename with .txt to it for GitHub to accept it.)
[debug.txt](https://github.com/procount/pinn/files/8279639/debug.txt)

**Comment by procount** [comment]
Whilst connected to the internet, reboot PINN twice, and then you should find Raspberry Pi OS (64-bit) can be backed up.

**Comment by lurch** [comment]
"Have you tried turning if off and on and off and on again?" :rofl:

**Comment by procount** [comment]
Just "to be sure, to be sure"! :wink:

**Comment by RanchoHam** [comment]
> 

JOY!!!!!!! on at least one machine.  I have to go check the other one at the office.

**Comment by RanchoHam** [comment]
> "Have you tried turning if off and on and off and on again?" 🤣

Multiple times on multiple machines after multiple software updates.

**Comment by procount** [comment]
> Just "to be sure, to be sure"! 😉

It is St. Patrick's Day after all.

> Multiple times on multiple machines after multiple software updates.

The reason for rebooting twice (assuming PINN is already running) is that Raspberry Pi OS (64-bit) is missing some flags to say it could be backed up in os.json, so I have to override it, but that entry was missing. So on the first boot PINN will download the new overrides, but they are not effective until the next reboot.

In an offline situation where overrides cannot be updated, it may be necessary to add
```
"supports_backup" : true,
```
to "/settings/os/Raspberry_Pi_OS_(64-bit)/os.json"
