### ISSUE TITLE
[OS Update Request] Update Retropie 4.7.1 to 4.8

### ISSUE THREAD

**Issue by MathieuG61** [procount/pinn#639]
Happy [Pi Day](https://en.wikipedia.org/wiki/Pi_Day)! After a long wait, we are pleased to announce the release of RetroPie 4.8.
[https://retropie.org.uk/news/](url)

**Comment by daveweber** [comment]
Woud like to see this change as well!

**Comment by procount** [comment]
4.8 is now available
