### ISSUE TITLE
Share SSH keys between OS's

### ISSUE THREAD

**Issue by NumberOneGit** [procount/pinn#647]
What would be the preferred method of sharing SSH keys between PINN, RPOS and other installed OS's?  Should I create an authorized_keys file in the /settings/dropbear folder?

**Comment by procount** [comment]
Nearly. See https://github.com/procount/pinn/blob/master/README_PINN.md#secure-remote-access

**Comment by NumberOneGit** [comment]
Thanks!  I'm not sure how I missed that.  

I wanted to use the same private key across multiple OS's and used these steps:

Generate ECDSA key pair and duplicate before conversion.
Convert ECDSA private key to PEM format:  "ssh-keygen -p -m pem -f ssh_host_ecdsa_key" 
Then to dropbear: "dropbearconvert openssh dropbear ssh_host_ecdsa_key dropbear_ecdsa_host_key".   

The PEM formatted key is only used as an intermediary in the conversion process then discarded.  I'm using the original generated ECDSA key for my other OS's.
