### ISSUE TITLE
CEC control - Arrows to select items (on "Select OS to Boot" window)

### ISSUE THREAD

**Issue by JeromeGH** [procount/pinn#65]
First, let me say thank you for this excellent project... I have also tried with noobs and berryboot, but Pinn works better for me.

Now I have 2 OS installed, "Libreelec" and "Recalbox", and I use my Sony-TV-Remote to select which one to boot.  According to [this page](https://github.com/procount/pinn/blob/master/README_PINN.md#cec-control-v211-onwards), its possible to use the arrows as mouse, and also "Channel Up/Down" buttons for "previous/next list item". Sadly, in my case this last option its not working.

My request would be to use the arrows to directly select OSs on the "Select OS to Boot" window (less clicks to select the OS), like in Berryboot ;)

Best regards

Jerome

**Comment by procount** [comment]
I decided to go for the lowest common denominator which should allow most features to be used by most TVs since each manufacturer implements CEC differently.

Maybe I will allow the buttons to be programmable in the future so you can do what you want....

**Comment by JeromeGH** [comment]
I can confirm now that my sony remote works fine ("Channel Up/Down" buttons for "previous/next list item")... only a little change was necessary in the tv configutarion  ;)

**Comment by procount** [comment]
That's great to hear. Please could you share your configuration change for other users?

**Comment by JeromeGH** [comment]
Sony Bravia 42w805a:

Settings --> Channels & Inputs --> BRAVIA Sync Setting --> Device Control Keys --> **Tunning and Menu Keys**

With this configuration now I can use the Channel Keys to control other things (Pinn, Kodi, etc) via CEC.

Best regards

Jerome

**Comment by jcbone** [comment]
Hi!

I have the same problem, I only get mousepointer movement with my remote (by Philips) via CEC. Which is a little annoying. :-) If you could add the option to program the keys or maybe add a switch to remap the arrow keys from mouse to keyboard arrows, that would be niiiice.

Thanks, Jörg

**Comment by procount** [comment]
The reason this topic was closed is because programmable keys have now been implemented, as long ago as last May 2018 in v2.8.1.
Please see the announcement here -> https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574&p=1314246#p1314246
Follow the links to the instructions and wiki page and make sure you have upgraded to the latest version of PINN.
If you have a new issue that the methods provided don't work on your Philips TV, please start a new topic, but I hope reading the above linked information will resolve your issue.

**Comment by jcbone** [comment]
Thanks! That's nice.
