### ISSUE TITLE
Arch2 (Arch Linux) is using removed links

### ISSUE THREAD

**Issue by drone540** [procount/pinn#650]
Hey it appears that the Arch Linux for Raspberry Pi 3 (and anything else referring to Arch2) is still referencing ARMv6 install links and cannot be installed by PINN as ARMv6 is no longer a supported platform.

Please update the image from this:
http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-armv7-latest.tar.gz

**Comment by techpixel** [comment]
Took me a while, but I found where it was calling the old link: 
https://github.com/procount/pinn-os/blob/c63b133b5f5ff17d5e030ee44b7a304d2e58fe4d/os/Arch2/partitions.json#L19

Try installing it manually using the provided os metadata.

**Comment by techpixel** [comment]
If you are using a Raspberry Pi 4B, you can try the Arch4 install using ARMv8: https://sourceforge.net/projects/pinn/files/os/Arch4/

**Comment by procount** [comment]
I have removed the ARM6 version and updated ARCH2 for all ARM7 models.
ARM8 (64-bit) uses UBoot, so it will require more work, and may not be suitable for conversion.

**Comment by techpixel** [comment]
Experiencing issues. Unable to get `boot_arch.tar.xz`.

**Comment by procount** [comment]
I think there are some issues with Sourceforge mirrors. If you repeat it might work.
I seem to be having intermittent issues if sourceforge chooses the deac-riga mirror.

**Comment by procount** [comment]
sourceforge should be working properly again now.
