### ISSUE TITLE
Update Lineage 19 Builds.

### ISSUE THREAD

**Issue by ghost** [procount/pinn#658]

**Comment by Ganeshgana426235** [comment]
I have successfully flashed lineage os 12 version  to my sd card 
But  when I am starting the raspberry Pi 4 b model  
It is not booting and showing blanck screen.. How can I solve this problem please help me

**Comment by procount** [comment]
Have you read the Lineage FAQ?
https://konstakang.com/devices/rpi4/LineageOS19/
