### ISSUE TITLE
Improve docs (adding new OSes later)

### ISSUE THREAD

**Issue by jose1711** [procount/pinn#661]
In `README_PINN.md`:
> When PINN installs OSes to a drive, it allocates all of the available drive space to the OSes by expanding the partitions. It is not possible to add any OSes later because there will be no remaining space.

What if `gparted` is used to resize the current partitions and make a space for new partitions? Is this something that PINN could handle? Or you strongly discourage from doing so (because of multiple implications).

**Comment by procount** [comment]
The original NOOBS concept (that PINN followed) was to install all OSes at once and to expand the partitions to fill all available space. Even reinstallation of an OS in NOOBS required a wipe of all the OSes. There was therefore no need to support the installation of subsequent OSes. This applies no matter which tools are used to resize partitions.

I have made improvements in PINN to allow reinstallation of individual OSes, replacement with other OSes with the same partition layout and the use of ProjectSpaces to reserve space for future OSes.

So far I have steered clear of supporting partition resizing and rearrangement as per the capabilities of gparted as this would be quite a large restructuring of the code base and is quite complex. It may mean the renumbering of all partitions, requiring all partition numbers to be tracked and re-running the partition_setup script for each OS with the new numbers etc. Adding support to move partitions around also carries a certain amount of risk of being able to destroy someone's installation so it needs to work reliably. Maybe one day I will get there, but there are several obstacles to overcome on the way to get there. 

EDIT: PINN cannot currently handle adding a new OS into empty space. If you want to do this, you would have to do it manually, which puts the responsibility on you if you get it wrong :wink:

**Comment by jose1711** [comment]
Thank you for a detailed answer. Please note that I am not really expecting PINN to handle the resizing/moving partitions. So the question really stands like this:
  - I use PINN to install several OSes
  - after some time as the filesystems grow there is a need to resize (shrink some, extend others) some of them
  - this adjustment will happen outside of PINN, using `gparted` and offline (in a SDcard reader)
  - are there any hidden risks? Like could PINN corrupt data if there was a change in partition layout?

**Comment by procount** [comment]
Resizing partitions using Gparted (shrinking or expanding) is not a problem for PINN. Of course you need to make sure the partition size is still large enough for the OS to work correctly.
PINN works by partition numbers on an SD card or by PARTUUIDs on a USB drive, so as long as you don't change the partition number order, it will be fine. 
If you change these, then PINN may not boot the right OS, and the OS may not be able to find its other partitions.

I've not tried this specifically, but if you do need to change partition order, updating /settings/installed_os.json with the new correct partitions and then re-running the partition setup scripts for the appropriate OSes from the fix up menu should fix it.

**Comment by jose1711** [comment]
Thank you again, that answers my question entirely.
