### ISSUE TITLE
RUNINSTALLER - initialize drive (blocking)

### ISSUE THREAD

**Issue by eroom1966** [procount/pinn#662]
Hi All

I have installed a new version of pinn, and I am trying to create an unattended install, which is currently blocking with a popup saying 

RUNINSTALLER - Initialise Drive
There are existing OSes installed Are you sure you want to initialise the crive
Yes | No

The answer is YES, but as it is unattended - I need to automate the response, otherwise the install will hang awaiting input
how do I overcome this ?

Searching issue list for other answers ....
Thx
Lee

**Comment by eroom1966** [comment]
I see an option forceruninstaller, trying this now, I presume this is an option to runinstaller, rather than an alternate command ?

**Comment by eroom1966** [comment]
answering my own question - this seems to fix the unattended installation

**Comment by lurch** [comment]
Forgive me for saying, but it sounds like you're trying to do things with PINN that it wasn't really designed to do?

**Comment by eroom1966** [comment]
@lurch @procount 

I think this was originally one of the intentions, here is a discussion from 2019 where I discussed this use model with the developer
https://github.com/procount/pinn/issues/343
@lurchm, actually you commented on that very thread !

I have it working again having updated the version, and used the additional command line option

FTAOD - if you have remote devices in the field, which you cannot attend to install a new/modified OS, then this is a very good method of maintenance

thx
Lee
