### ISSUE TITLE
Could you please add Ubuntu Desktop 22.04 LTS?

### ISSUE THREAD

**Issue by name01019** [procount/pinn#668]
Ubuntu has been updated to 22.04
https://ubuntu.com/download/raspberry-pi

**Comment by CallMeAryan** [comment]
+1

**Comment by gadido30** [comment]
+1

**Comment by paulwratt** [comment]
not sure if this helps some

http://cdimage.ubuntu.com/ubuntu-server/jammy/daily-preinstalled/current/

**Comment by AlarmingBox** [comment]
yes please add it. was getting some errors upgrading from the previous version. Apparently 22.04 is the first version of Ubuntu Desktop certified for Raspberry Pi 4. 
https://ubuntu.com/blog/whats-new-for-raspberry-pi-ubuntu-22-04-lts

**Comment by lurch** [comment]
ping @waveform80 to see if there's any interest at Canonical for providing Ubuntu in NOOBS/PINN-format tarballs?

**Comment by procount** [comment]
OK it's coming! Basic conversion is done but needs some tidy up.

**Comment by procount** [comment]
Ubuntu 22.04.1 Desktop for Pi4 is now available for installation.

**Comment by miguelgargallo** [comment]
Yes please, still 2023 without server option on PINN menu, Ubuntu 22.04.2 LTS (Jammy Jellyfish) server

**Comment by procount** [comment]
Ubuntu 22.04.2 Desktop & Server versions now added.

**Comment by miguelgargallo** [comment]
Thanks

**Comment by miguelgargallo** [comment]
Oh! and EndeavourOS? it's magic! its the Arch alternative!? Thanks in advance

**Comment by procount** [comment]
EndeavourOS does not have an RPI image and creating it is quite lengthy, even after a PINN install.
Could you install Arch and then install the desktop on top?

**Comment by miguelgargallo** [comment]
That's what I did ❤️

**Comment by procount** [comment]
Great!
I'm not having much luck creating a PINN version.
Would a version without desktop be sufficient?
