### ISSUE TITLE
Cant Press Backup Button 

### ISSUE THREAD

**Issue by Retro-Devils** [procount/pinn#670]
So ive made a Retropie os and a Android 11 os. Installed through PINN and everything . Now i wanna backup but i cant press the button, its just grey.

**Comment by Retro-Devils** [comment]
So i probably just missed this lol. But i was successful after formatting my usb drive to fat32 and making a folder named os on it .

**Comment by Retro-Devils** [comment]
So i got a backup error when i finally was able to backup. Any help?

**Comment by procount** [comment]
What was the backup error? (See troubleshooting on the wiki)

**Comment by Retro-Devils** [comment]
ill pull error from log now

**Comment by Retro-Devils** [comment]
says "error writing ......... Disk Full? 

it a 2 tb usb images are on a 256 gb card.

**Comment by procount** [comment]
FAT32 is limited to 4GB files. Maybe try formatting it as EXT instead.

**Comment by Retro-Devils** [comment]
ok ok . ill try now

**Comment by Retro-Devils** [comment]
worked great!!
