### ISSUE TITLE
ssh to pinn boot

### ISSUE THREAD

**Issue by The-Exterminator** [procount/pinn#676]
How can i ssh to the boot menu from my PC. ??? so i dont need USB keybord and mouse

**Comment by procount** [comment]
Ssh is for a text interface but the boot menu is graphical so you must use vnc. I suggest to add vncshare and forcetriggee. See https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-pinn-headlessly-vnc

**Comment by The-Exterminator** [comment]
> Ssh is for a text interface but the boot menu is graphical so you must use vnc. I suggest to add vncshare and forcetriggee. See https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-pinn-headlessly-vnc

i can now ssh to the pinn, but how can i start the pinn menu, so i can choise it from my pc. ???

**Comment by procount** [comment]
Like I said above, you can't from ssh. You must use VNC.
Download a vnc client such as tightvnc or realvnc for your PC and use that instead of ssh.
