### ISSUE TITLE
New Norwgian language available

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#68]
@procount 

I asked to some friends that partecipate to other software project to help me with PINN language file.

The first one that answered is Øistein Rian  that send me the Norwegian language.

I added it and craeted a pull request.

I'm so sorry but I forgot to modify recovery.pro to add Norwegian language.
Please modify it.

**Comment by procount** [comment]
Thanks. Will add soon ( few days or so)

**Comment by procount** [comment]
done
