### ISSUE TITLE
New Arabic language available

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#69]
@procount 

I added Arabic language

I modified the recovery.pro to add translation_ar.ts and translation_no.ts

Is it possible to add in recovery.pro

    translation_en.ts \

to have an empty English language file useful for new translation?

**Comment by procount** [comment]
AR is is the ISO-3166-1 2 alpha code for Argentina. Please see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

Do you mean AE for United Arab Emirates?, 
And is this the correct flag?
![ae](https://cloud.githubusercontent.com/assets/4853137/26792855/b039c9d8-4a13-11e7-8d40-05a046c8f3d3.png)

**Comment by bovirus** [comment]
@procount 

Yes sure. United Arab Emirates.
The flag should be OK.

https://en.wikipedia.org/wiki/Flag_of_the_United_Arab_Emirates

**Comment by procount** [comment]
Done
