### ISSUE TITLE
Loop OS booting

### ISSUE THREAD

**Issue by CrysK** [procount/pinn#701]
Would it be possible to automatically select the next (different) OS at every new boot? If yes, how?

Example:
OS1 and OS2 are installed. When OS1 is started, the next time in PINN OS2 is selected as default and vice versa.

**Comment by procount** [comment]
I guess you could write a script to do that.
The last selected boot partition is stored in /settings/noobs.conf as "default_partition_to_boot=6".
If you write an initialisation script (see https://github.com/procount/pinn/blob/master/README_PINN.md#initialisation-shell-script) then you could change it on every boot to another value.
Or you could write a script to run in each OS when it is booted to change this setting to point to the other OS.

**Comment by CrysK** [comment]
Thanks for your quick reply. That gives me two good options:
- either directly in PINN via "pinn_init.sh", but then it is only changed blindly (which is ok for me in 99% of the cases).
- or in the real OS, but then with a real switch to the other OS at the next boot (which is also documented, eg. https://wiki.libreelec.tv/configuration/startup-shutdown#shutdown.sh)

I will try this. From my side the topic is done. 

Thanks a lot!
