### ISSUE TITLE
Os not showing in menu

### ISSUE THREAD

**Issue by HexEvee** [procount/pinn#706]
Recently, I've been trying two things. One, move my custom Os into PINN. Second, more importantly, I was just setting up a new PINN install, and wanted to install win98-pi, but it will not show up in menu. Any help?

**Comment by procount** [comment]
Did you read my answer to your previous question?
Which model of Pi do you have?
There is a manual for PINN which might help you at https://github.com/procount/pinn/blob/master/README_PINN.md
Also there are some tutorial instructiosn on my wiki on how to install custom OSes.

**Comment by HexEvee** [comment]
I have a 4b

**Comment by HexEvee** [comment]
Thank you!
