### ISSUE TITLE
RPi 4B PINN not starting on USB SSD

### ISSUE THREAD

**Issue by ajl199** [procount/pinn#710]
Non issue: PINN was malfunctioning in various interesting and inconsistent ways when booting off a USB SSD. Turns out I had a dodgy power supply.

**Comment by procount** [comment]
Ahh, that would explain a lot!
Many issues on the forums are often solved with a better power supply :)

**Comment by procount** [comment]
I've converted OpenPlotter32 for you. Next will be OpenPlotter64 then BBN, Hopefully have it done in a few days, provided I can find enough free time.

**Comment by ajl199** [comment]
Thank you! I really appreciate that.

**Comment by procount** [comment]
OpenPlotter & BBN are now available. You will find the in the new Sailing tab.

**Comment by ajl199** [comment]
Brilliant! Thank you. Unfortunately, I do have one more problem as shown in the attached image. When I go back into PINN to replace project spaces with those OSes, in its main menu, only the installed OSes are shown, with no tabs. It's definitely got an internet connection because the built in Arora browser can see the internet, but the Reload Repos button doesn't help.

Am I doing something wrong, or is there a known cause of this? I've not got anything important set up yet, so it wouldn't be the end of the world if it's a mystery and I have to start again.

In case relevant (not sure why it would be), I created a custom recovery.cmdline using pinn.mjh.nz:

`runinstaller quiet ramdisk_size=32768 root=/dev/ram0 init=/init vt.cur_default=1 elevator=deadline no_group no_default_source select="allnetwork" disablesdimages alt_image_source=http://pinn.mjh.nz/os_list.json?raspberrypios64-bit=30810&datapartition=775743&projectspace-1=30419&projectspace-2=30685&projectspace-3=30684&projectspace-4=30559 loglevel=2 sdhci.debug_quirks2=4`

![PINNnoTabs](https://user-images.githubusercontent.com/46404662/222956800-fc451a14-f0b9-4ecc-8fe4-826654a890c3.jpg)

**Comment by procount** [comment]
By using Matt's webpage to determine the partition sizes, you have restricted PINN's view of available OSes to only those that you selected on the webpage. So you need to make some changes to recovery.cmdline.

The easiest thing to do is to restore recovery,cmdline by replacing recovery.cmdline with recovery.cmdline.new.

**Comment by ajl199** [comment]
Ah! Now the penny drops about how Matt's page works. Switched recovery.cmdline back and all is well.

Thank you again for doing this.
