### ISSUE TITLE
Restore Raspberry Pi OS (64 bit) image with Auto Mount issues

### ISSUE THREAD

**Issue by Hiforever** [procount/pinn#712]
Restore Raspberry Pi OS (64 bit) image with Auto Mount issues.  While auto-mounted storages (be it USB drives or SD Card partitions) still appear in the document explorer, there is nothing in \media\pi (or whatever user) and result in an error.

I am using Raspberry pi 4 and Pinn lite version 3.8.4.   The same problem with other versions of Pinn lite.

**Comment by procount** [comment]
Can you expand a bit more on this issue? I don't understand where the priblem is. Is it an issue in Raspberry Pi Os or in PINN? If in Raspios, does it occur if you install without PINN?

**Comment by Hiforever** [comment]
1.   Raspios (64bit) was installed through PINN with no problem.  All auto-mount drives were mounted under \media\pi
2.   The same Raspios was backup using PINN with no error
3.   The OS was restored, in the same partition with PINN, using the backup created in step 2 above, those drives still shown up in the doucment explorer.  
4.   However, if you click on any of these drives, the explorer reported an error with nothing mounted under \media\pi.   I tried to disable the auto-mount, reboot and enable again but it is still not working.

**Comment by procount** [comment]
Ah ok. Got it.

**Comment by procount** [comment]
This seems to be an extension to issue #447 which I thought was fixed a while ago.
A quick workaround is to unmount all the drives, then delete the /pi folder in /media (or whatever your user name is).
I don't think a reboot is necessary, but can't harm.
Then attach a USB device and the /media/pi folder will be created with the correct permissions.
I shall look into a more permanent fix.

**Comment by Hiforever** [comment]
This is resolved.  Thank you very much

**Comment by procount** [comment]
I have released v3.8.5.3 which should restore the ACL permissions of OS backups properly.
