### ISSUE TITLE
Utility to check and repair SD card.

### ISSUE THREAD

**Issue by lavinkabul** [procount/pinn#713]
I am using PINN on Raspberry pi 4B. I have two operating systems installed, Debian and Batocera. A couple of times in my house there was an emergency power outage. After that, errors occurred on the micro SD card. Last time, after a power outage, Debian booted normally, and Batocera stopped detecting almost all the ROMs on the disk after booting (about 95% of the ROMs were gone). To repair bad sectors on an SD card, I used the DiskGenius program on Windows. Is it possible to include a program for testing and repairing a disk in PINN? Or maybe there are some other means of verification as part of PINN?

**Comment by procount** [comment]
On the Maintenance Menu there is a Fixup option which includes a File System Check that runs e2fsck over selected OSes.
See https://github.com/procount/pinn/blob/p3.8.5/README_PINN.md#how-to-fix-an-os

**Comment by lavinkabul** [comment]
Thank you very much. I didn't know about it, now everything will be much easier!
