### ISSUE TITLE
Firmware not found

### ISSUE THREAD

**Issue by Yeag4** [procount/pinn#718]
Whenever i try to boot my rapberry pi with pinn it says firmware not found, even though I've followed the directions exactly.

**Comment by procount** [comment]
Is this your first time using Pinn?
Which midel of RPi are you using?
Which version of Pinn have you installed?
How did you install Pinn?
Did you insrall to SD card or a usb drive?
Can you install other OSes like Raspberry PiOS using RPi Imager?

**Comment by Yeag4** [comment]
yes, this is my first time using Pinn
raspberry pi 4 model b
The newest one, don't know the exact name
installed it via sourceforge
installed on to sd card
yes, I can install raspberry pi os for the RPI imager.

**Comment by procount** [comment]
You're probably doing something wrong as you have to format the SD card particularly before installing from the zip file, especially if it is a large SD card.
I suggest you try to install from RPi Imager as this is a much easier way.
In Rpi Imager, when you select Choose OS, go to the "Misc utility images" and then the PINN section where you will find the latest version of PINN to install to your SD card.

**Comment by Yeag4** [comment]
ok, i will see if that works

**Comment by Yeag4** [comment]
that appears to have worked
