### ISSUE TITLE
Host pinn-lite.zip on GitHub releases

### ISSUE THREAD

**Issue by matthewruzzi** [procount/pinn#729]
Can you host pinn-lite.zip for each release on GitHub releases along with pinn-lite.img.zip?

**Comment by procount** [comment]
Any particular reason why this is preferred for you?

**Comment by matthewruzzi** [comment]
The GitHub interface is easier to use and I trust GitHub more than Sourceforge and I would prefer it if pinn hosted files on GitHub instead of Sourceforge so all of the files related to pinn could be in one place.

**Comment by procount** [comment]
I copied pinn-lite.zip there too

**Comment by matthewruzzi** [comment]
Thanks
