### ISSUE TITLE
Will AOSP Work

### ISSUE THREAD

**Issue by dismal002** [procount/pinn#731]
https://konstakang.com/devices/rpi4/AOSP13/

**Comment by 88572** [comment]
Probably not.
![image](https://github.com/procount/pinn/assets/82726593/87633234-f7f6-4060-8ef3-59f16b53d559)

**Comment by dismal002** [comment]
Well the other Android builds are from the same developer. Konstakang developed the lineage os builds so I dont see a problem with it.

**Comment by 88572** [comment]
Did we get permission to use it though?

**Comment by dismal002** [comment]
I think so anyway I saw lineage os 20 was pushed. I tried to do it myself here https://uploadnow.io/f/CKxCH84. But official support would be greatly appreciated

**Comment by procount** [comment]
I will take a look once I have finished LineageOs20.

**Comment by procount** [comment]
AOSP13-rpi4 has been added
