### ISSUE TITLE
Could you please add LineageOS 20?

### ISSUE THREAD

**Issue by name01019** [procount/pinn#734]
KonstaKANG has released Lineage OS 20.0 for RPi4

Lineage OS (KonstaKANG) 20.0 for RPi4
https://konstakang.com/devices/rpi4/LineageOS20/

Lineage OS ATV (KonstaKANG) 20.0 for RPi4
https://konstakang.com/devices/rpi4/LineageOS20-ATV/

**Comment by procount** [comment]
Already added on 1st July 😄

**Comment by name01019** [comment]
My bad! I should have checked natively. I usually just look at https://pinn.mjh.nz/list/ to check if the distro is listed
