### ISSUE TITLE
Local OS source format to install multiple OS's

### ISSUE THREAD

**Issue by 89carrot** [procount/pinn#735]
I'd like to be able to install LibreElec and Batocera offline using the PINN installer. Is it possible to obtain the install sources for these OS's and others so I don't have to rely on downloading them from the repository? 

Thank you

**Comment by procount** [comment]
Please see https://github.com/procount/pinn/blob/master/README_PINN.md#download

**Comment by 89carrot** [comment]
That will work perfectly. Thank you for the quick response!
