### ISSUE TITLE
Rasplex for RPi3

### ISSUE THREAD

**Issue by anotherbob67** [procount/pinn#742]
Trying to dual boot retropie and Rasplex. I'm having issues with the current rasplex image. Rasplex image is for p2 and has issues with shared libraries showing up on my 3b+. RasPlex-1.8.0.0b-573b6d73-RPi3bplus.arm.img.gz works well. Is it possible to add?

**Comment by matthuisman** [comment]
i have just added RasPlex for Pi3B+. Please try

**Comment by matthuisman** [comment]
@procount think this can be closed now :)

**Comment by procount** [comment]
Thanks
