### ISSUE TITLE
Headless rpi boot partition switch

### ISSUE THREAD

**Issue by JavierCCC** [procount/pinn#757]
Hi. I'm a happy pinn user. The only issue i found is the need for connecting a keyboard or mouse (and a monitor/TV) to my rpi everytime i need to switch the booted OS. Is there any way to modify the "next boot" partition in order to be able to switch OSes in headless mode?

**Comment by procount** [comment]
Yes.
Please see https://github.com/procount/pinn/blob/master/README_PINN.md#how-to-use-pinn-headlessly-vnc
And #756 
You can also change the boot partition from your booted OS by mounting the settings partition and modifying noobs.conf manually. Or provide the partition number in recovery.cmdline.
