### ISSUE TITLE
PINN keeps restarting after OS selection

### ISSUE THREAD

**Issue by IBilly75** [procount/pinn#767]
With RPI 4 I have the latest PINN with following OSes installed:

- Batocera RPi4
- Recalbox7
- Libreelec
- Volumio
- OSMC PI4

Suddently when I select any of the last 3 OS, system restarts after 1-2 seconds, and gets back to PINN OS selection.

Any idea what may have gone wrong in PINN? I have official 3A power adapter.

I guess this is not OS related issue, since it affects 3 OSs the same way.

Below you can see all my logs.

Any help would be very welcome!

Many thanks

[debug.txt](https://github.com/procount/pinn/files/13726843/debug.txt)
[dmesg.txt](https://github.com/procount/pinn/files/13726844/dmesg.txt)
[log.txt](https://github.com/procount/pinn/files/13726845/log.txt)

**Comment by procount** [comment]
Assuming your attached log files are correct, there are some inconsistencies between the actual partitions listed by fdisk in log.txt and the contents of installed_os.json. I don't know how this can have occurred. Have you mnually messed with the partitions or altered the installed_os.json file at all?

**Comment by procount** [comment]
Closing as no response
