### ISSUE TITLE
Updating Manjaro Releases from 20.04 to 23.02 [Update Submission]

### ISSUE THREAD

**Issue by Dimensional** [procount/pinn#769]
I've recently downloaded, installed, extracted, etc 4 of the 6 Raspberry Pi versions of Manjaro. The current release for the Pi is 23.02. I have taken the time to test and verify that all of them boot after converting to PINN. 

The 4 flavors built and tested are KDE Plasma, GNOME, MATE, and XFCE. Attached below is a link to where I have them saved. Having these should provided some resolution for anyone who is using an out dated version and running into update problems because of lost compatibility between packages. It's a known problem I've seen where after a while, a package that gets updated is technically replaced, and said replacement breaks compatibility with another that depended on the original, causing any sort of update to fail until this incompatibility is manually rectified, leading to further headaches.

This is why I've grab the versions and got them converted for the official PINN Repo. Feel free to verify and make adjustments. I've updated the release notes to match the official information, updated the os.json info, put in the sha checksums for the partitions.json, and I've left alone the Nominal Partition Size for the boot partition, leaving room for updates and initramfs stuff.

I'll probably have this updated once the RPi release of Manjaro 23.1.1 is published, since the x86_64 was published only a few days ago.

https://drive.proton.me/urls/9977WFHZ74#HWdVIKomzO9A

**Comment by procount** [comment]
I have released these 4 OSes.
Thanks.
