### ISSUE TITLE
Fix Typo in Date and Time option

### ISSUE THREAD

**Issue by RedZebra123H** [procount/pinn#774]
When you hover your mouse over the date and time option in the Archival menu, it says "Set Data & Time". I do not know if this was meant to be or if this is an error. Also I am using v3.8.7.
![IMG_0704](https://github.com/procount/pinn/assets/155842336/0b88eebf-373e-4a3e-bfa3-5b25d29d6d7d)

**Comment by procount** [comment]
Well spotted!
I have fixed it locally, so it should be in the next release
