### ISSUE TITLE
Libreelec 9.28

### ISSUE THREAD

**Issue by JanSykor** [procount/pinn#778]
Is it possible to add version Libreelec 9.28 or Libreelec 9.26 image to **Legacy** bookmark?
Reason is that for Pi2 and Pi3 for some people is this version better then last versions due to better optimisation for HEVC video decoding.
Thank you
Jan

**Comment by procount** [comment]
I'm working with the LibreELEC maintainers to update their offerrings in PINN.

**Comment by JanSykor** [comment]
If there will be some problem I have from the past downloaded from Pinn version 9.2.6, so I can save it somewhere.
Thanks
Jan

**Comment by procount** [comment]
It's ok I have it.

**Comment by procount** [comment]
LibreELEC-rpi2_926 has just been added.

**Comment by JanSykor** [comment]
Dear @procount 
Thank you very much - it is working. I only expected position in Legacy tab, but Media is also OK
Only Info button for this is not working - is it possible to add to the file this address?
https://libreelec.tv/2020/11/02/libreelec-leia-9-2-6/

Thanks 
Jan

**Comment by procount** [comment]
info URL is now updated.
