### ISSUE TITLE
When I want to install os,I encounter with a problem as followed : http://raw.githubusercontent.com/procount/pinn-os/master/os/os all.json not connected 

### ISSUE THREAD

**Issue by WangXinis** [procount/pinn#779]

**Comment by WangXinis** [comment]
![WechatIMG3091](https://github.com/procount/pinn/assets/31101495/596ddcc0-d45e-4f0a-bda1-aa099720231c)

**Comment by procount** [comment]
It looks like you have a problem downloading the list of operating systems.
Clearly your RPi 3B is connected to your network and you are accessing it via VNC, but can your RPi access the internet?
If you click on Close, and click on Close when the wifi dialog appears, does the list of OSes eventually appear? In this case, try setting the networktimeout setting to 30 seconds or more to give it more time before it times out.
Can you download the file manually through your web browser?

**Comment by procount** [comment]
Closing as no response. Feel free to reopen if needed.
