### ISSUE TITLE
No Indication of What is Happening During Update

### ISSUE THREAD

**Issue by zaxlofful** [procount/pinn#785]
When updating on my Raspberry Pi 2B to the latest version (3.8.7d), the screen just kinda grays out and gives no indication of what is happening.

Initially it has a window saying "downloading update," then that just disappears and the screen is greyed out.

It should say something along the lines of "currently, upgrading this will take a few minutes and then the system will reboot."

Otherwise, people (like me) could think that it's locked up or just bugged and might pull the plug. I have been having a lot of freezing issues lately, so if I hadn't looked away for a second, I would have just pulled the power to start over.

**Comment by procount** [comment]
Implemented better info messages.
Will be included in next release.
