### ISSUE TITLE
Ubuntu Install Error

### ISSUE THREAD

**Issue by cyber-distillery** [procount/pinn#786]
I'm trying to install Ubuntu 22.04 Desktop and am getting an error indicating it could not find label system-boot. I'll post the debug logs soon as I can.

However, the strange thing is that my Kali Linux installion works fine.

I have PINN installed on SD card and OS installed on nvme argon kit.

Version: 3.8.7
Device: Raspberry Pi 4 - 8G

**Comment by procount** [comment]
Which Pi model?
Which version of PINN?

**Comment by procount** [comment]
So I guess your NVMe drive is connected via USB?

**Comment by cyber-distillery** [comment]
> So I guess your NVMe drive is connected via USB?

Yes, that is correct.

**Comment by cyber-distillery** [comment]
@procount I managed to solve the issue. I think what had happened is that when trying to install Ubuntu, I actually mistakenly selected the SD card instead of my NVME.

I saw my SD card had system-boot and writable which I believe isn't supposed to be there. I formatted my SD card and re-imaged PINN. Now it works!

Sorry for the hassle.
