### ISSUE TITLE
Wrong selection of keyboard

### ISSUE THREAD

**Issue by JanSykor** [procount/pinn#788]
Hi @procount 
When I tested last version 3.8.7.d and select Czech language , the keyboard is selected "us"
I am sure, that in previous version (3..7.c) it was working and selection of Czech language select "cz" keyboard.
I think that problem is in difference in ISO marking "cs" and keyboard marking "cz", so I prepare change in your file.
Unfortunately I am not sure if this change is enough.
Please check it
best regards
Jan
[languagedialog.zip](https://github.com/procount/pinn/files/14234149/languagedialog.zip)

**Comment by procount** [comment]
Sorry for that. I will check and correct.

**Comment by procount** [comment]
Fixedin 3.8.7f
