### ISSUE TITLE
Hidden wifi network adding to PINN OS console

### ISSUE THREAD

**Issue by naidu72** [procount/pinn#790]
Hello,

I want to add hidden wifi network PINN OS.
Is there any  document or step to make work?

**Comment by procount** [comment]
PINN does not use Network Manager, but uses the older wpa_supplicant method to configure the wifi.
You may handcraft a wpa_supplicant.conf file and include it on PINN's recovery partition for it to be used.

**Comment by naidu72** [comment]
Thanks it working with following wpa_supplicant.conf changes 

https://github.com/asparatu/raspberrypi-wpa-supplicant.conf/blob/master/wpa_supplicant.conf
