### ISSUE TITLE
Errors installing LibreELEC

### ISSUE THREAD

**Issue by overkillcaraudio** [procount/pinn#792]
Hi, PINN is a great utility. I’ve been using it with not many problems. I’m new here. 
I’m getting this error with the LibreELEC OS. It doesn’t happen in noobs. It says to check the debug. 
it looks like something isn’t where it’s supposed to be. Some other guy wrote about this in the reviews so it’s not just me. Although I know that this it the right place to raise the issue.
Here’s a pic of the bottom of the dubug. 
Please check it out and let us know what you think.
Thanks for the product.
![IMG_4178](https://github.com/procount/pinn/assets/85889263/8d64c233-5f9e-4844-88f3-b59609cd1994)

**Comment by procount** [comment]
The file does not currently exist. I suspect it is because LibreELEC 12 is being released and I have some updating to do for them.
I expect it will be fixed shortly.

**Comment by overkillcaraudio** [comment]
Cheers for the update. I’ll work out another way for now. I just wanted to check the problem wasn’t on my end. I’m teaching myself a lot from this, Thanks again for your work.


On 9 Mar 2024, at 10:30 pm, procount ***@***.***> wrote:

﻿

The file does not currently exist. I suspect it is because LibreELEC 12 is being released and I have some updating to do for them.
I expect it will be fixed shortly.

**Comment by JanSykor** [comment]
Hello
I have same problem with Libreelec. I think Libreelec 12 not yet release, because Kodi 21 is just RC1
It can be problem on Libreelec site, or the image is saved on Pinn servers?
Where is saved Pinn debug log which Is mentioned in error message?

Thanks
Jan

**Comment by procount** [comment]
Rpi4 System.tar.xz file has temporarily disappeared from the LibreELEC servers.
Their maintainer is not able to fix it for a week.
I've been able to put a temporary fix in for now for v 11.0.6

**Comment by JanSykor** [comment]
It is working now
Thanks for your quick action
Jan
P.S. for the future use - where I can find installation debug log ?

**Comment by procount** [comment]
Sorry, I meant to answer that, but forgot :(
It's in `/tmp/debug`
See also https://github.com/procount/pinn/wiki/Troubleshooting

**Comment by overkillcaraudio** [comment]
Awesome, thanks again.

On 11 Mar 2024, at 2:29 am, procount ***@***.***> wrote:

﻿

Sorry, I meant to answer that, but forgot :(
It's in /tmp/debug
See also https://github.com/procount/pinn/wiki/Troubleshooting
