### ISSUE TITLE
Not updating of PINN

### ISSUE THREAD

**Issue by JanSykor** [procount/pinn#801]
Yesterday I saw that is there new update of PINN and I try it.
It was updated from original beta version to version 3.8.9d and after reboot I have update message again, try it again, but it was not updated to 3.8.9.f and I have again message about new update.
I am not sure if it is known problem or not. If not, I can try found some logs.
Thanks
Jan

**Comment by procount** [comment]
I'm working on the update procedure and a new version. It should have stopped announcing a new version now.

**Comment by procount** [comment]
v3.8.8 released in preparation for pi5 upgrade.
