### ISSUE TITLE
Update pinn-lite

### ISSUE THREAD

**Issue by bovirus** [procount/pinn#81]
@procount 

Could you please update pinn-lite in sourceforge with latest changes in Github repository?

Please every time that you make a changes in Github compile it and post the updated pinn-lite in Sourceforge.

Thanks.

**Comment by procount** [comment]
Sorry, I was waiting for the next release, but it is taking longer than expected. I will look to post it up soon. Very busy at the moment.

**Comment by procount** [comment]
done. Forum post coming soon....
