### ISSUE TITLE
include libreelec for kodi 20 on pinn

### ISSUE THREAD

**Issue by BENDER35** [procount/pinn#814]
hello

I comment on the topic, I have already released the update for Kodi 21, but in a group of an addon that I use (which I am not going to say), they tell me that the version for Kodi 21 is going to take a while, so my question is, will it take? Could you include the latest version of libreelec compatible with kodi 20 in pinn? Is it so that if the installation of 20 that I have (I have a raspberry pi 3) fails, it could be easily restored.

All the best

Rodrigo

**Comment by procount** [comment]
So in summary, if I understand you correctly, you want me to include the previous version of LibreElec that used Kodi 20, in addition to the latest version, so that you can use a particular addon?

**Comment by BENDER35** [comment]
> So in summary, if I understand you correctly, you want me to include the previous version of LibreElec that used Kodi 20, in addition to the latest version, so that you can use a particular addon?

hello

The addon that the creators say will take a while to become compatible with Kodi 21 is Moe's TV (included in Luar), an addon that allows you to watch Spanish on-demand television.

Greetings

**Comment by procount** [comment]
OK I'll see what I can do.

**Comment by procount** [comment]
LibreElec v11 has been restored in the Legacy category
