### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kimasplund** [procount/pinn#829]
Would it be possible to add the feature to boot a custom iso file from usb or network?

**Comment by procount** [comment]
1. PINN does not boot iso or img files. They must first be converted to .tar.xz files per partition. PINN will then install these to the PINN boot drive.
2. PINN has no control over which drive is booted. This is determined by the firmware and the BOOT_ORDER. PINN can only select which partition is booted on the boot drive. If you want to use PINN to select an Os on the USB or NVME drive, then PINN must also be on that drive and the drive must be the boot drive.

**Comment by lurch** [comment]
If you want to "boot from network" then see https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#network-booting
Or perhaps you're looking for https://www.raspberrypi.com/documentation/computers/getting-started.html#install-over-the-network ?
