### ISSUE TITLE
Retropie isnt booting up for PINN

### ISSUE THREAD

**Issue by ThePseudoSudo** [procount/pinn#830]
I am really new to the whole Raspberry Pi community and I found that PINN is an easy to use multiboot system. I am trying to get raspberry OS on it with retropie but every time I try to boot into retropie, I am met with a balck screen with a qr code in the top right with a line at the bottom saying that i need newer software. I have tried everything to a factory reset to upgrading the bootloaders. nothing works. I think you may have used the wrong version of Retropie in this. I am using the Pi 4 B.

**Comment by procount** [comment]
It was the right version at the time 😉 but is now a bit old. I will be updating it to 4.8 soon.

**Comment by ThePseudoSudo** [comment]
Ok. Thank you. How will I know when you add it? Will it be on the GitHub update files? Also, will it be updated in the Pi Imager or will I have to redownload Pi Imager to refresh the operating systems?

**Comment by procount** [comment]
Hmm. 
It looks like I had already converted Retropie 4.8 and released it some time ago (see #639) but I think it got dropped. I hope that was not because there was a problem with it. Anyway, it is now re-released. Please try re-installing it (after checking it shows v4.8)

**Comment by ThePseudoSudo** [comment]
How do i get the updated PINN? Is it updated on the Raspberry Pi Imager or do I need to get it from here and run a custom firmware in Pi Imager?

**Comment by procount** [comment]
PINN is not updated, only the list of OSes. Just use the PINN you have already installed.
Press shift after it boots when it tells you to in the top left corner when the colourful wallpaper is shown to get into the recovery menu.
Use the reinstall option (see https://github.com/procount/pinn/blob/master/README_PINN.md#reinstall-individual-oses).
If you don't know how to use PINN, please read the rest of that webpage to understand the whole of its features. If you're still not sure after that, then please come back with more questions.

**Comment by ThePseudoSudo** [comment]
Thank you so much. The Retropie works great.
