### ISSUE TITLE
[feature request] shutdown button

### ISSUE THREAD

**Issue by andriilive** [procount/pinn#844]
I didn't found anything in PINN Readme about how to simply power of, if no actions needed. Searched for `shutdown` and `turn off` `power`

**Comment by procount** [comment]
Unless you are in the middle of a disk transaction, like installing or downloading an OS, just pull the plug. PINN runs from a ramdisk and keeps its partitions read-only whenever possible.

**Comment by andriilive** [comment]
Double `esc` works on 3.9.2
