### ISSUE TITLE
[OS REQUEST] fydeOS

### ISSUE THREAD

**Issue by martinvdv05** [procount/pinn#848]
So basically if you don't know fydeOS, its pretty much a fork of chromeOS for other pc's, laptops, vm's and sbc's.
https://fydeos.io/download/sbc

**Comment by procount** [comment]
FydeOS is not suitable for PINN. Please see
#703
#469 
#665
#726

**Comment by JP1967** [comment]
Please add FydeOs install support for PI5

**Comment by procount** [comment]
See above
