### ISSUE TITLE
How to boot to different USB drives?

### ISSUE THREAD

**Issue by mdallanegra** [procount/pinn#86]
I want to be able to boot to different USB drives without reinstalling each time or installing all OS’s in one Drive. Mostly because I like to try different operating systems for the Raspberry Pi and I don’t want to change the SD card every time I want to try a new distro or just use any of them. 

The thing is that i’d like to have in one pen-drive Raspbian installed and in other Ubuntu Mate, even I want to have LibreELEC on the SD Card, and when I want to use each of this OSs I press Shift on boot and select one. But I haven't been able to do that, and I don't have the knowledge necessary to make any changes on PINNs code. 

I’d like to learn more to do that., I know a little bit of C, C++ and Python, but its not enough. If someone could give me a hint or tell me where to look, it would be awesome. And if someone want to add my suggestion to PINN I’d be very pleased too. 

Thanks.

**Comment by procount** [comment]
That might be a bit tricky to do - to have several bootable USB devices installed at once and to be able to choose any OS from any of them. If you have an RPi3 and have enabled USB BOOT, you could install a different OS on each USB stick and then switch OSes by just inserting the appropriate USB stick. But I don;t think I can cope with multiple bootable USB devices.
